// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyModule.proto

#ifndef PROTOBUF_ArmyModule_2eproto__INCLUDED
#define PROTOBUF_ArmyModule_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace main {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ArmyModule_2eproto();
void protobuf_AssignDesc_ArmyModule_2eproto();
void protobuf_ShutdownFile_ArmyModule_2eproto();

class DispatchOfficerRequest;
class DispatchOfficerResponse;
class RemoveOfficerRequest;
class RemoveOfficerResponse;
class SetLordRequest;
class SetLordResponse;
class DispatchSoldierRequest;
class DispatchSoldierResponse;
class ChangePositionRequest;
class ChangePositionResponse;
class ChangeOfficerRequest;
class ChangeOfficerResponse;
class ChangeCurrentTeamRequest;
class ChangeCurrentTeamResponse;
class BatchChangeOfficerRequest;
class BatchChangeOfficerResponse;

// ===================================================================

class DispatchOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  DispatchOfficerRequest();
  virtual ~DispatchOfficerRequest();

  DispatchOfficerRequest(const DispatchOfficerRequest& from);

  inline DispatchOfficerRequest& operator=(const DispatchOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DispatchOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DispatchOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DispatchOfficerRequest* other);

  // implements Message ----------------------------------------------

  DispatchOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DispatchOfficerRequest& from);
  void MergeFrom(const DispatchOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ssid = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsidFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // optional int32 position = 2;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 2;
  inline ::google::protobuf::int32 position() const;
  inline void set_position(::google::protobuf::int32 value);

  // optional int32 teamId = 3;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 3;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DispatchOfficerRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  ::google::protobuf::int32 position_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static DispatchOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class DispatchOfficerResponse : public ::google::protobuf::MessageLite {
 public:
  DispatchOfficerResponse();
  virtual ~DispatchOfficerResponse();

  DispatchOfficerResponse(const DispatchOfficerResponse& from);

  inline DispatchOfficerResponse& operator=(const DispatchOfficerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DispatchOfficerResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DispatchOfficerResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DispatchOfficerResponse* other);

  // implements Message ----------------------------------------------

  DispatchOfficerResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DispatchOfficerResponse& from);
  void MergeFrom(const DispatchOfficerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DispatchOfficerResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static DispatchOfficerResponse* default_instance_;
};
// -------------------------------------------------------------------

class RemoveOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  RemoveOfficerRequest();
  virtual ~RemoveOfficerRequest();

  RemoveOfficerRequest(const RemoveOfficerRequest& from);

  inline RemoveOfficerRequest& operator=(const RemoveOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const RemoveOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RemoveOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RemoveOfficerRequest* other);

  // implements Message ----------------------------------------------

  RemoveOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RemoveOfficerRequest& from);
  void MergeFrom(const RemoveOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 position = 1;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 1;
  inline ::google::protobuf::int32 position() const;
  inline void set_position(::google::protobuf::int32 value);

  // optional int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.RemoveOfficerRequest)
 private:
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 position_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static RemoveOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class RemoveOfficerResponse : public ::google::protobuf::MessageLite {
 public:
  RemoveOfficerResponse();
  virtual ~RemoveOfficerResponse();

  RemoveOfficerResponse(const RemoveOfficerResponse& from);

  inline RemoveOfficerResponse& operator=(const RemoveOfficerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const RemoveOfficerResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RemoveOfficerResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RemoveOfficerResponse* other);

  // implements Message ----------------------------------------------

  RemoveOfficerResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RemoveOfficerResponse& from);
  void MergeFrom(const RemoveOfficerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.RemoveOfficerResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static RemoveOfficerResponse* default_instance_;
};
// -------------------------------------------------------------------

class SetLordRequest : public ::google::protobuf::MessageLite {
 public:
  SetLordRequest();
  virtual ~SetLordRequest();

  SetLordRequest(const SetLordRequest& from);

  inline SetLordRequest& operator=(const SetLordRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const SetLordRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SetLordRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SetLordRequest* other);

  // implements Message ----------------------------------------------

  SetLordRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SetLordRequest& from);
  void MergeFrom(const SetLordRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ssid = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsidFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // optional int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.SetLordRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static SetLordRequest* default_instance_;
};
// -------------------------------------------------------------------

class SetLordResponse : public ::google::protobuf::MessageLite {
 public:
  SetLordResponse();
  virtual ~SetLordResponse();

  SetLordResponse(const SetLordResponse& from);

  inline SetLordResponse& operator=(const SetLordResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const SetLordResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SetLordResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SetLordResponse* other);

  // implements Message ----------------------------------------------

  SetLordResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SetLordResponse& from);
  void MergeFrom(const SetLordResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.SetLordResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static SetLordResponse* default_instance_;
};
// -------------------------------------------------------------------

class DispatchSoldierRequest : public ::google::protobuf::MessageLite {
 public:
  DispatchSoldierRequest();
  virtual ~DispatchSoldierRequest();

  DispatchSoldierRequest(const DispatchSoldierRequest& from);

  inline DispatchSoldierRequest& operator=(const DispatchSoldierRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DispatchSoldierRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DispatchSoldierRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DispatchSoldierRequest* other);

  // implements Message ----------------------------------------------

  DispatchSoldierRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DispatchSoldierRequest& from);
  void MergeFrom(const DispatchSoldierRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ssid = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsidFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // optional int32 color = 2;
  inline bool has_color() const;
  inline void clear_color();
  static const int kColorFieldNumber = 2;
  inline ::google::protobuf::int32 color() const;
  inline void set_color(::google::protobuf::int32 value);

  // optional int32 teamId = 3;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 3;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DispatchSoldierRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_color();
  inline void clear_has_color();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  ::google::protobuf::int32 color_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static DispatchSoldierRequest* default_instance_;
};
// -------------------------------------------------------------------

class DispatchSoldierResponse : public ::google::protobuf::MessageLite {
 public:
  DispatchSoldierResponse();
  virtual ~DispatchSoldierResponse();

  DispatchSoldierResponse(const DispatchSoldierResponse& from);

  inline DispatchSoldierResponse& operator=(const DispatchSoldierResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DispatchSoldierResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DispatchSoldierResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DispatchSoldierResponse* other);

  // implements Message ----------------------------------------------

  DispatchSoldierResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DispatchSoldierResponse& from);
  void MergeFrom(const DispatchSoldierResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DispatchSoldierResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static DispatchSoldierResponse* default_instance_;
};
// -------------------------------------------------------------------

class ChangePositionRequest : public ::google::protobuf::MessageLite {
 public:
  ChangePositionRequest();
  virtual ~ChangePositionRequest();

  ChangePositionRequest(const ChangePositionRequest& from);

  inline ChangePositionRequest& operator=(const ChangePositionRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ChangePositionRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ChangePositionRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ChangePositionRequest* other);

  // implements Message ----------------------------------------------

  ChangePositionRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ChangePositionRequest& from);
  void MergeFrom(const ChangePositionRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 from = 1;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 1;
  inline ::google::protobuf::int32 from() const;
  inline void set_from(::google::protobuf::int32 value);

  // optional int32 to = 2;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 2;
  inline ::google::protobuf::int32 to() const;
  inline void set_to(::google::protobuf::int32 value);

  // optional int32 teamId = 3;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 3;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.ChangePositionRequest)
 private:
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_to();
  inline void clear_has_to();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 from_;
  ::google::protobuf::int32 to_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static ChangePositionRequest* default_instance_;
};
// -------------------------------------------------------------------

class ChangePositionResponse : public ::google::protobuf::MessageLite {
 public:
  ChangePositionResponse();
  virtual ~ChangePositionResponse();

  ChangePositionResponse(const ChangePositionResponse& from);

  inline ChangePositionResponse& operator=(const ChangePositionResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ChangePositionResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ChangePositionResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ChangePositionResponse* other);

  // implements Message ----------------------------------------------

  ChangePositionResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ChangePositionResponse& from);
  void MergeFrom(const ChangePositionResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.ChangePositionResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static ChangePositionResponse* default_instance_;
};
// -------------------------------------------------------------------

class ChangeOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  ChangeOfficerRequest();
  virtual ~ChangeOfficerRequest();

  ChangeOfficerRequest(const ChangeOfficerRequest& from);

  inline ChangeOfficerRequest& operator=(const ChangeOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ChangeOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ChangeOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ChangeOfficerRequest* other);

  // implements Message ----------------------------------------------

  ChangeOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ChangeOfficerRequest& from);
  void MergeFrom(const ChangeOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sourceId = 1;
  inline bool has_sourceid() const;
  inline void clear_sourceid();
  static const int kSourceIdFieldNumber = 1;
  inline ::google::protobuf::int32 sourceid() const;
  inline void set_sourceid(::google::protobuf::int32 value);

  // optional int32 targetId = 2;
  inline bool has_targetid() const;
  inline void clear_targetid();
  static const int kTargetIdFieldNumber = 2;
  inline ::google::protobuf::int32 targetid() const;
  inline void set_targetid(::google::protobuf::int32 value);

  // optional int32 teamId = 3;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 3;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.ChangeOfficerRequest)
 private:
  inline void set_has_sourceid();
  inline void clear_has_sourceid();
  inline void set_has_targetid();
  inline void clear_has_targetid();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 sourceid_;
  ::google::protobuf::int32 targetid_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static ChangeOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class ChangeOfficerResponse : public ::google::protobuf::MessageLite {
 public:
  ChangeOfficerResponse();
  virtual ~ChangeOfficerResponse();

  ChangeOfficerResponse(const ChangeOfficerResponse& from);

  inline ChangeOfficerResponse& operator=(const ChangeOfficerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ChangeOfficerResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ChangeOfficerResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ChangeOfficerResponse* other);

  // implements Message ----------------------------------------------

  ChangeOfficerResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ChangeOfficerResponse& from);
  void MergeFrom(const ChangeOfficerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.ChangeOfficerResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static ChangeOfficerResponse* default_instance_;
};
// -------------------------------------------------------------------

class ChangeCurrentTeamRequest : public ::google::protobuf::MessageLite {
 public:
  ChangeCurrentTeamRequest();
  virtual ~ChangeCurrentTeamRequest();

  ChangeCurrentTeamRequest(const ChangeCurrentTeamRequest& from);

  inline ChangeCurrentTeamRequest& operator=(const ChangeCurrentTeamRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ChangeCurrentTeamRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ChangeCurrentTeamRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ChangeCurrentTeamRequest* other);

  // implements Message ----------------------------------------------

  ChangeCurrentTeamRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ChangeCurrentTeamRequest& from);
  void MergeFrom(const ChangeCurrentTeamRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 teamId = 1;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 1;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.ChangeCurrentTeamRequest)
 private:
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static ChangeCurrentTeamRequest* default_instance_;
};
// -------------------------------------------------------------------

class ChangeCurrentTeamResponse : public ::google::protobuf::MessageLite {
 public:
  ChangeCurrentTeamResponse();
  virtual ~ChangeCurrentTeamResponse();

  ChangeCurrentTeamResponse(const ChangeCurrentTeamResponse& from);

  inline ChangeCurrentTeamResponse& operator=(const ChangeCurrentTeamResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ChangeCurrentTeamResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ChangeCurrentTeamResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ChangeCurrentTeamResponse* other);

  // implements Message ----------------------------------------------

  ChangeCurrentTeamResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ChangeCurrentTeamResponse& from);
  void MergeFrom(const ChangeCurrentTeamResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 teamId = 2;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.ChangeCurrentTeamResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static ChangeCurrentTeamResponse* default_instance_;
};
// -------------------------------------------------------------------

class BatchChangeOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  BatchChangeOfficerRequest();
  virtual ~BatchChangeOfficerRequest();

  BatchChangeOfficerRequest(const BatchChangeOfficerRequest& from);

  inline BatchChangeOfficerRequest& operator=(const BatchChangeOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const BatchChangeOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BatchChangeOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BatchChangeOfficerRequest* other);

  // implements Message ----------------------------------------------

  BatchChangeOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BatchChangeOfficerRequest& from);
  void MergeFrom(const BatchChangeOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 teamId = 1;
  inline bool has_teamid() const;
  inline void clear_teamid();
  static const int kTeamIdFieldNumber = 1;
  inline ::google::protobuf::int32 teamid() const;
  inline void set_teamid(::google::protobuf::int32 value);

  // repeated int32 officerIds = 2;
  inline int officerids_size() const;
  inline void clear_officerids();
  static const int kOfficerIdsFieldNumber = 2;
  inline ::google::protobuf::int32 officerids(int index) const;
  inline void set_officerids(int index, ::google::protobuf::int32 value);
  inline void add_officerids(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      officerids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_officerids();

  // @@protoc_insertion_point(class_scope:main.BatchChangeOfficerRequest)
 private:
  inline void set_has_teamid();
  inline void clear_has_teamid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > officerids_;
  ::google::protobuf::int32 teamid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static BatchChangeOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class BatchChangeOfficerResponse : public ::google::protobuf::MessageLite {
 public:
  BatchChangeOfficerResponse();
  virtual ~BatchChangeOfficerResponse();

  BatchChangeOfficerResponse(const BatchChangeOfficerResponse& from);

  inline BatchChangeOfficerResponse& operator=(const BatchChangeOfficerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const BatchChangeOfficerResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BatchChangeOfficerResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BatchChangeOfficerResponse* other);

  // implements Message ----------------------------------------------

  BatchChangeOfficerResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BatchChangeOfficerResponse& from);
  void MergeFrom(const BatchChangeOfficerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.BatchChangeOfficerResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArmyModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArmyModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArmyModule_2eproto();
  friend void protobuf_ShutdownFile_ArmyModule_2eproto();

  void InitAsDefaultInstance();
  static BatchChangeOfficerResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// DispatchOfficerRequest

// optional int32 ssid = 1;
inline bool DispatchOfficerRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DispatchOfficerRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DispatchOfficerRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DispatchOfficerRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 DispatchOfficerRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.DispatchOfficerRequest.ssid)
  return ssid_;
}
inline void DispatchOfficerRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchOfficerRequest.ssid)
}

// optional int32 position = 2;
inline bool DispatchOfficerRequest::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DispatchOfficerRequest::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DispatchOfficerRequest::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DispatchOfficerRequest::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline ::google::protobuf::int32 DispatchOfficerRequest::position() const {
  // @@protoc_insertion_point(field_get:main.DispatchOfficerRequest.position)
  return position_;
}
inline void DispatchOfficerRequest::set_position(::google::protobuf::int32 value) {
  set_has_position();
  position_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchOfficerRequest.position)
}

// optional int32 teamId = 3;
inline bool DispatchOfficerRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DispatchOfficerRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DispatchOfficerRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DispatchOfficerRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 DispatchOfficerRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.DispatchOfficerRequest.teamId)
  return teamid_;
}
inline void DispatchOfficerRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchOfficerRequest.teamId)
}

// -------------------------------------------------------------------

// DispatchOfficerResponse

// required int32 state = 1;
inline bool DispatchOfficerResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DispatchOfficerResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DispatchOfficerResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DispatchOfficerResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 DispatchOfficerResponse::state() const {
  // @@protoc_insertion_point(field_get:main.DispatchOfficerResponse.state)
  return state_;
}
inline void DispatchOfficerResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchOfficerResponse.state)
}

// required int32 teamId = 2;
inline bool DispatchOfficerResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DispatchOfficerResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DispatchOfficerResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DispatchOfficerResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 DispatchOfficerResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.DispatchOfficerResponse.teamId)
  return teamid_;
}
inline void DispatchOfficerResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchOfficerResponse.teamId)
}

// -------------------------------------------------------------------

// RemoveOfficerRequest

// optional int32 position = 1;
inline bool RemoveOfficerRequest::has_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RemoveOfficerRequest::set_has_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RemoveOfficerRequest::clear_has_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RemoveOfficerRequest::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline ::google::protobuf::int32 RemoveOfficerRequest::position() const {
  // @@protoc_insertion_point(field_get:main.RemoveOfficerRequest.position)
  return position_;
}
inline void RemoveOfficerRequest::set_position(::google::protobuf::int32 value) {
  set_has_position();
  position_ = value;
  // @@protoc_insertion_point(field_set:main.RemoveOfficerRequest.position)
}

// optional int32 teamId = 2;
inline bool RemoveOfficerRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RemoveOfficerRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RemoveOfficerRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RemoveOfficerRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 RemoveOfficerRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.RemoveOfficerRequest.teamId)
  return teamid_;
}
inline void RemoveOfficerRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.RemoveOfficerRequest.teamId)
}

// -------------------------------------------------------------------

// RemoveOfficerResponse

// required int32 state = 1;
inline bool RemoveOfficerResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RemoveOfficerResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RemoveOfficerResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RemoveOfficerResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 RemoveOfficerResponse::state() const {
  // @@protoc_insertion_point(field_get:main.RemoveOfficerResponse.state)
  return state_;
}
inline void RemoveOfficerResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.RemoveOfficerResponse.state)
}

// required int32 teamId = 2;
inline bool RemoveOfficerResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RemoveOfficerResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RemoveOfficerResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RemoveOfficerResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 RemoveOfficerResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.RemoveOfficerResponse.teamId)
  return teamid_;
}
inline void RemoveOfficerResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.RemoveOfficerResponse.teamId)
}

// -------------------------------------------------------------------

// SetLordRequest

// optional int32 ssid = 1;
inline bool SetLordRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SetLordRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SetLordRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SetLordRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 SetLordRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.SetLordRequest.ssid)
  return ssid_;
}
inline void SetLordRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.SetLordRequest.ssid)
}

// optional int32 teamId = 2;
inline bool SetLordRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SetLordRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SetLordRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SetLordRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 SetLordRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.SetLordRequest.teamId)
  return teamid_;
}
inline void SetLordRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.SetLordRequest.teamId)
}

// -------------------------------------------------------------------

// SetLordResponse

// required int32 state = 1;
inline bool SetLordResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SetLordResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SetLordResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SetLordResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 SetLordResponse::state() const {
  // @@protoc_insertion_point(field_get:main.SetLordResponse.state)
  return state_;
}
inline void SetLordResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.SetLordResponse.state)
}

// required int32 teamId = 2;
inline bool SetLordResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SetLordResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SetLordResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SetLordResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 SetLordResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.SetLordResponse.teamId)
  return teamid_;
}
inline void SetLordResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.SetLordResponse.teamId)
}

// -------------------------------------------------------------------

// DispatchSoldierRequest

// optional int32 ssid = 1;
inline bool DispatchSoldierRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DispatchSoldierRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DispatchSoldierRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DispatchSoldierRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 DispatchSoldierRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.DispatchSoldierRequest.ssid)
  return ssid_;
}
inline void DispatchSoldierRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchSoldierRequest.ssid)
}

// optional int32 color = 2;
inline bool DispatchSoldierRequest::has_color() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DispatchSoldierRequest::set_has_color() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DispatchSoldierRequest::clear_has_color() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DispatchSoldierRequest::clear_color() {
  color_ = 0;
  clear_has_color();
}
inline ::google::protobuf::int32 DispatchSoldierRequest::color() const {
  // @@protoc_insertion_point(field_get:main.DispatchSoldierRequest.color)
  return color_;
}
inline void DispatchSoldierRequest::set_color(::google::protobuf::int32 value) {
  set_has_color();
  color_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchSoldierRequest.color)
}

// optional int32 teamId = 3;
inline bool DispatchSoldierRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DispatchSoldierRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DispatchSoldierRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DispatchSoldierRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 DispatchSoldierRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.DispatchSoldierRequest.teamId)
  return teamid_;
}
inline void DispatchSoldierRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchSoldierRequest.teamId)
}

// -------------------------------------------------------------------

// DispatchSoldierResponse

// required int32 state = 1;
inline bool DispatchSoldierResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DispatchSoldierResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DispatchSoldierResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DispatchSoldierResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 DispatchSoldierResponse::state() const {
  // @@protoc_insertion_point(field_get:main.DispatchSoldierResponse.state)
  return state_;
}
inline void DispatchSoldierResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchSoldierResponse.state)
}

// required int32 teamId = 2;
inline bool DispatchSoldierResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DispatchSoldierResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DispatchSoldierResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DispatchSoldierResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 DispatchSoldierResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.DispatchSoldierResponse.teamId)
  return teamid_;
}
inline void DispatchSoldierResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.DispatchSoldierResponse.teamId)
}

// -------------------------------------------------------------------

// ChangePositionRequest

// optional int32 from = 1;
inline bool ChangePositionRequest::has_from() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangePositionRequest::set_has_from() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangePositionRequest::clear_has_from() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangePositionRequest::clear_from() {
  from_ = 0;
  clear_has_from();
}
inline ::google::protobuf::int32 ChangePositionRequest::from() const {
  // @@protoc_insertion_point(field_get:main.ChangePositionRequest.from)
  return from_;
}
inline void ChangePositionRequest::set_from(::google::protobuf::int32 value) {
  set_has_from();
  from_ = value;
  // @@protoc_insertion_point(field_set:main.ChangePositionRequest.from)
}

// optional int32 to = 2;
inline bool ChangePositionRequest::has_to() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangePositionRequest::set_has_to() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangePositionRequest::clear_has_to() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangePositionRequest::clear_to() {
  to_ = 0;
  clear_has_to();
}
inline ::google::protobuf::int32 ChangePositionRequest::to() const {
  // @@protoc_insertion_point(field_get:main.ChangePositionRequest.to)
  return to_;
}
inline void ChangePositionRequest::set_to(::google::protobuf::int32 value) {
  set_has_to();
  to_ = value;
  // @@protoc_insertion_point(field_set:main.ChangePositionRequest.to)
}

// optional int32 teamId = 3;
inline bool ChangePositionRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChangePositionRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChangePositionRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChangePositionRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 ChangePositionRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.ChangePositionRequest.teamId)
  return teamid_;
}
inline void ChangePositionRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangePositionRequest.teamId)
}

// -------------------------------------------------------------------

// ChangePositionResponse

// required int32 state = 1;
inline bool ChangePositionResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangePositionResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangePositionResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangePositionResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 ChangePositionResponse::state() const {
  // @@protoc_insertion_point(field_get:main.ChangePositionResponse.state)
  return state_;
}
inline void ChangePositionResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.ChangePositionResponse.state)
}

// required int32 teamId = 2;
inline bool ChangePositionResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangePositionResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangePositionResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangePositionResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 ChangePositionResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.ChangePositionResponse.teamId)
  return teamid_;
}
inline void ChangePositionResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangePositionResponse.teamId)
}

// -------------------------------------------------------------------

// ChangeOfficerRequest

// optional int32 sourceId = 1;
inline bool ChangeOfficerRequest::has_sourceid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeOfficerRequest::set_has_sourceid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeOfficerRequest::clear_has_sourceid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeOfficerRequest::clear_sourceid() {
  sourceid_ = 0;
  clear_has_sourceid();
}
inline ::google::protobuf::int32 ChangeOfficerRequest::sourceid() const {
  // @@protoc_insertion_point(field_get:main.ChangeOfficerRequest.sourceId)
  return sourceid_;
}
inline void ChangeOfficerRequest::set_sourceid(::google::protobuf::int32 value) {
  set_has_sourceid();
  sourceid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeOfficerRequest.sourceId)
}

// optional int32 targetId = 2;
inline bool ChangeOfficerRequest::has_targetid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeOfficerRequest::set_has_targetid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeOfficerRequest::clear_has_targetid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeOfficerRequest::clear_targetid() {
  targetid_ = 0;
  clear_has_targetid();
}
inline ::google::protobuf::int32 ChangeOfficerRequest::targetid() const {
  // @@protoc_insertion_point(field_get:main.ChangeOfficerRequest.targetId)
  return targetid_;
}
inline void ChangeOfficerRequest::set_targetid(::google::protobuf::int32 value) {
  set_has_targetid();
  targetid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeOfficerRequest.targetId)
}

// optional int32 teamId = 3;
inline bool ChangeOfficerRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChangeOfficerRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChangeOfficerRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChangeOfficerRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 ChangeOfficerRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.ChangeOfficerRequest.teamId)
  return teamid_;
}
inline void ChangeOfficerRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeOfficerRequest.teamId)
}

// -------------------------------------------------------------------

// ChangeOfficerResponse

// required int32 state = 1;
inline bool ChangeOfficerResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeOfficerResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeOfficerResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeOfficerResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 ChangeOfficerResponse::state() const {
  // @@protoc_insertion_point(field_get:main.ChangeOfficerResponse.state)
  return state_;
}
inline void ChangeOfficerResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeOfficerResponse.state)
}

// required int32 teamId = 2;
inline bool ChangeOfficerResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeOfficerResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeOfficerResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeOfficerResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 ChangeOfficerResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.ChangeOfficerResponse.teamId)
  return teamid_;
}
inline void ChangeOfficerResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeOfficerResponse.teamId)
}

// -------------------------------------------------------------------

// ChangeCurrentTeamRequest

// optional int32 teamId = 1;
inline bool ChangeCurrentTeamRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeCurrentTeamRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeCurrentTeamRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeCurrentTeamRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 ChangeCurrentTeamRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.ChangeCurrentTeamRequest.teamId)
  return teamid_;
}
inline void ChangeCurrentTeamRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeCurrentTeamRequest.teamId)
}

// -------------------------------------------------------------------

// ChangeCurrentTeamResponse

// required int32 state = 1;
inline bool ChangeCurrentTeamResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeCurrentTeamResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeCurrentTeamResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeCurrentTeamResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 ChangeCurrentTeamResponse::state() const {
  // @@protoc_insertion_point(field_get:main.ChangeCurrentTeamResponse.state)
  return state_;
}
inline void ChangeCurrentTeamResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeCurrentTeamResponse.state)
}

// required int32 teamId = 2;
inline bool ChangeCurrentTeamResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeCurrentTeamResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeCurrentTeamResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeCurrentTeamResponse::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 ChangeCurrentTeamResponse::teamid() const {
  // @@protoc_insertion_point(field_get:main.ChangeCurrentTeamResponse.teamId)
  return teamid_;
}
inline void ChangeCurrentTeamResponse::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.ChangeCurrentTeamResponse.teamId)
}

// -------------------------------------------------------------------

// BatchChangeOfficerRequest

// required int32 teamId = 1;
inline bool BatchChangeOfficerRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BatchChangeOfficerRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BatchChangeOfficerRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BatchChangeOfficerRequest::clear_teamid() {
  teamid_ = 0;
  clear_has_teamid();
}
inline ::google::protobuf::int32 BatchChangeOfficerRequest::teamid() const {
  // @@protoc_insertion_point(field_get:main.BatchChangeOfficerRequest.teamId)
  return teamid_;
}
inline void BatchChangeOfficerRequest::set_teamid(::google::protobuf::int32 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:main.BatchChangeOfficerRequest.teamId)
}

// repeated int32 officerIds = 2;
inline int BatchChangeOfficerRequest::officerids_size() const {
  return officerids_.size();
}
inline void BatchChangeOfficerRequest::clear_officerids() {
  officerids_.Clear();
}
inline ::google::protobuf::int32 BatchChangeOfficerRequest::officerids(int index) const {
  // @@protoc_insertion_point(field_get:main.BatchChangeOfficerRequest.officerIds)
  return officerids_.Get(index);
}
inline void BatchChangeOfficerRequest::set_officerids(int index, ::google::protobuf::int32 value) {
  officerids_.Set(index, value);
  // @@protoc_insertion_point(field_set:main.BatchChangeOfficerRequest.officerIds)
}
inline void BatchChangeOfficerRequest::add_officerids(::google::protobuf::int32 value) {
  officerids_.Add(value);
  // @@protoc_insertion_point(field_add:main.BatchChangeOfficerRequest.officerIds)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BatchChangeOfficerRequest::officerids() const {
  // @@protoc_insertion_point(field_list:main.BatchChangeOfficerRequest.officerIds)
  return officerids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BatchChangeOfficerRequest::mutable_officerids() {
  // @@protoc_insertion_point(field_mutable_list:main.BatchChangeOfficerRequest.officerIds)
  return &officerids_;
}

// -------------------------------------------------------------------

// BatchChangeOfficerResponse

// optional int32 state = 1;
inline bool BatchChangeOfficerResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BatchChangeOfficerResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BatchChangeOfficerResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BatchChangeOfficerResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 BatchChangeOfficerResponse::state() const {
  // @@protoc_insertion_point(field_get:main.BatchChangeOfficerResponse.state)
  return state_;
}
inline void BatchChangeOfficerResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.BatchChangeOfficerResponse.state)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace main

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ArmyModule_2eproto__INCLUDED
