// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CooperationModule.proto

#ifndef PROTOBUF_CooperationModule_2eproto__INCLUDED
#define PROTOBUF_CooperationModule_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace main {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CooperationModule_2eproto();
void protobuf_AssignDesc_CooperationModule_2eproto();
void protobuf_ShutdownFile_CooperationModule_2eproto();

class CooperationRequest;
class CooperationResponse;
class CooperationModel;
class CooperationFillRequest;
class CooperationFillResponse;

// ===================================================================

class CooperationRequest : public ::google::protobuf::MessageLite {
 public:
  CooperationRequest();
  virtual ~CooperationRequest();

  CooperationRequest(const CooperationRequest& from);

  inline CooperationRequest& operator=(const CooperationRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CooperationRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CooperationRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CooperationRequest* other);

  // implements Message ----------------------------------------------

  CooperationRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CooperationRequest& from);
  void MergeFrom(const CooperationRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:main.CooperationRequest)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_CooperationModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_CooperationModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_CooperationModule_2eproto();
  friend void protobuf_ShutdownFile_CooperationModule_2eproto();

  void InitAsDefaultInstance();
  static CooperationRequest* default_instance_;
};
// -------------------------------------------------------------------

class CooperationResponse : public ::google::protobuf::MessageLite {
 public:
  CooperationResponse();
  virtual ~CooperationResponse();

  CooperationResponse(const CooperationResponse& from);

  inline CooperationResponse& operator=(const CooperationResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CooperationResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CooperationResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CooperationResponse* other);

  // implements Message ----------------------------------------------

  CooperationResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CooperationResponse& from);
  void MergeFrom(const CooperationResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .main.CooperationModel cooperationModel = 1;
  inline int cooperationmodel_size() const;
  inline void clear_cooperationmodel();
  static const int kCooperationModelFieldNumber = 1;
  inline const ::main::CooperationModel& cooperationmodel(int index) const;
  inline ::main::CooperationModel* mutable_cooperationmodel(int index);
  inline ::main::CooperationModel* add_cooperationmodel();
  inline const ::google::protobuf::RepeatedPtrField< ::main::CooperationModel >&
      cooperationmodel() const;
  inline ::google::protobuf::RepeatedPtrField< ::main::CooperationModel >*
      mutable_cooperationmodel();

  // @@protoc_insertion_point(class_scope:main.CooperationResponse)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::main::CooperationModel > cooperationmodel_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_CooperationModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_CooperationModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_CooperationModule_2eproto();
  friend void protobuf_ShutdownFile_CooperationModule_2eproto();

  void InitAsDefaultInstance();
  static CooperationResponse* default_instance_;
};
// -------------------------------------------------------------------

class CooperationModel : public ::google::protobuf::MessageLite {
 public:
  CooperationModel();
  virtual ~CooperationModel();

  CooperationModel(const CooperationModel& from);

  inline CooperationModel& operator=(const CooperationModel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CooperationModel& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CooperationModel* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CooperationModel* other);

  // implements Message ----------------------------------------------

  CooperationModel* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CooperationModel& from);
  void MergeFrom(const CooperationModel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional int32 itemId = 4;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIdFieldNumber = 4;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // optional int32 itemLevel = 5;
  inline bool has_itemlevel() const;
  inline void clear_itemlevel();
  static const int kItemLevelFieldNumber = 5;
  inline ::google::protobuf::int32 itemlevel() const;
  inline void set_itemlevel(::google::protobuf::int32 value);

  // optional int32 roleLv = 6;
  inline bool has_rolelv() const;
  inline void clear_rolelv();
  static const int kRoleLvFieldNumber = 6;
  inline ::google::protobuf::int32 rolelv() const;
  inline void set_rolelv(::google::protobuf::int32 value);

  // optional sint32 inList = 7;
  inline bool has_inlist() const;
  inline void clear_inlist();
  static const int kInListFieldNumber = 7;
  inline ::google::protobuf::int32 inlist() const;
  inline void set_inlist(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.CooperationModel)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_itemlevel();
  inline void clear_has_itemlevel();
  inline void set_has_rolelv();
  inline void clear_has_rolelv();
  inline void set_has_inlist();
  inline void clear_has_inlist();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 itemlevel_;
  ::google::protobuf::int32 rolelv_;
  ::google::protobuf::int32 inlist_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_CooperationModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_CooperationModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_CooperationModule_2eproto();
  friend void protobuf_ShutdownFile_CooperationModule_2eproto();

  void InitAsDefaultInstance();
  static CooperationModel* default_instance_;
};
// -------------------------------------------------------------------

class CooperationFillRequest : public ::google::protobuf::MessageLite {
 public:
  CooperationFillRequest();
  virtual ~CooperationFillRequest();

  CooperationFillRequest(const CooperationFillRequest& from);

  inline CooperationFillRequest& operator=(const CooperationFillRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CooperationFillRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CooperationFillRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CooperationFillRequest* other);

  // implements Message ----------------------------------------------

  CooperationFillRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CooperationFillRequest& from);
  void MergeFrom(const CooperationFillRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:main.CooperationFillRequest)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_CooperationModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_CooperationModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_CooperationModule_2eproto();
  friend void protobuf_ShutdownFile_CooperationModule_2eproto();

  void InitAsDefaultInstance();
  static CooperationFillRequest* default_instance_;
};
// -------------------------------------------------------------------

class CooperationFillResponse : public ::google::protobuf::MessageLite {
 public:
  CooperationFillResponse();
  virtual ~CooperationFillResponse();

  CooperationFillResponse(const CooperationFillResponse& from);

  inline CooperationFillResponse& operator=(const CooperationFillResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CooperationFillResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CooperationFillResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CooperationFillResponse* other);

  // implements Message ----------------------------------------------

  CooperationFillResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CooperationFillResponse& from);
  void MergeFrom(const CooperationFillResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.CooperationFillResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_CooperationModule_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_CooperationModule_2eproto();
  #endif
  friend void protobuf_AssignDesc_CooperationModule_2eproto();
  friend void protobuf_ShutdownFile_CooperationModule_2eproto();

  void InitAsDefaultInstance();
  static CooperationFillResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// CooperationRequest

// -------------------------------------------------------------------

// CooperationResponse

// repeated .main.CooperationModel cooperationModel = 1;
inline int CooperationResponse::cooperationmodel_size() const {
  return cooperationmodel_.size();
}
inline void CooperationResponse::clear_cooperationmodel() {
  cooperationmodel_.Clear();
}
inline const ::main::CooperationModel& CooperationResponse::cooperationmodel(int index) const {
  // @@protoc_insertion_point(field_get:main.CooperationResponse.cooperationModel)
  return cooperationmodel_.Get(index);
}
inline ::main::CooperationModel* CooperationResponse::mutable_cooperationmodel(int index) {
  // @@protoc_insertion_point(field_mutable:main.CooperationResponse.cooperationModel)
  return cooperationmodel_.Mutable(index);
}
inline ::main::CooperationModel* CooperationResponse::add_cooperationmodel() {
  // @@protoc_insertion_point(field_add:main.CooperationResponse.cooperationModel)
  return cooperationmodel_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::main::CooperationModel >&
CooperationResponse::cooperationmodel() const {
  // @@protoc_insertion_point(field_list:main.CooperationResponse.cooperationModel)
  return cooperationmodel_;
}
inline ::google::protobuf::RepeatedPtrField< ::main::CooperationModel >*
CooperationResponse::mutable_cooperationmodel() {
  // @@protoc_insertion_point(field_mutable_list:main.CooperationResponse.cooperationModel)
  return &cooperationmodel_;
}

// -------------------------------------------------------------------

// CooperationModel

// optional int32 roleId = 1;
inline bool CooperationModel::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CooperationModel::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CooperationModel::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CooperationModel::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 CooperationModel::roleid() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.roleId)
  return roleid_;
}
inline void CooperationModel::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationModel.roleId)
}

// optional string name = 2;
inline bool CooperationModel::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CooperationModel::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CooperationModel::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CooperationModel::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& CooperationModel::name() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.name)
  return *name_;
}
inline void CooperationModel::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:main.CooperationModel.name)
}
inline void CooperationModel::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:main.CooperationModel.name)
}
inline void CooperationModel::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:main.CooperationModel.name)
}
inline ::std::string* CooperationModel::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:main.CooperationModel.name)
  return name_;
}
inline ::std::string* CooperationModel::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CooperationModel::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:main.CooperationModel.name)
}

// optional int32 type = 3;
inline bool CooperationModel::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CooperationModel::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CooperationModel::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CooperationModel::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 CooperationModel::type() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.type)
  return type_;
}
inline void CooperationModel::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationModel.type)
}

// optional int32 itemId = 4;
inline bool CooperationModel::has_itemid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CooperationModel::set_has_itemid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CooperationModel::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CooperationModel::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 CooperationModel::itemid() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.itemId)
  return itemid_;
}
inline void CooperationModel::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationModel.itemId)
}

// optional int32 itemLevel = 5;
inline bool CooperationModel::has_itemlevel() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CooperationModel::set_has_itemlevel() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CooperationModel::clear_has_itemlevel() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CooperationModel::clear_itemlevel() {
  itemlevel_ = 0;
  clear_has_itemlevel();
}
inline ::google::protobuf::int32 CooperationModel::itemlevel() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.itemLevel)
  return itemlevel_;
}
inline void CooperationModel::set_itemlevel(::google::protobuf::int32 value) {
  set_has_itemlevel();
  itemlevel_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationModel.itemLevel)
}

// optional int32 roleLv = 6;
inline bool CooperationModel::has_rolelv() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CooperationModel::set_has_rolelv() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CooperationModel::clear_has_rolelv() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CooperationModel::clear_rolelv() {
  rolelv_ = 0;
  clear_has_rolelv();
}
inline ::google::protobuf::int32 CooperationModel::rolelv() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.roleLv)
  return rolelv_;
}
inline void CooperationModel::set_rolelv(::google::protobuf::int32 value) {
  set_has_rolelv();
  rolelv_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationModel.roleLv)
}

// optional sint32 inList = 7;
inline bool CooperationModel::has_inlist() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CooperationModel::set_has_inlist() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CooperationModel::clear_has_inlist() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CooperationModel::clear_inlist() {
  inlist_ = 0;
  clear_has_inlist();
}
inline ::google::protobuf::int32 CooperationModel::inlist() const {
  // @@protoc_insertion_point(field_get:main.CooperationModel.inList)
  return inlist_;
}
inline void CooperationModel::set_inlist(::google::protobuf::int32 value) {
  set_has_inlist();
  inlist_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationModel.inList)
}

// -------------------------------------------------------------------

// CooperationFillRequest

// -------------------------------------------------------------------

// CooperationFillResponse

// optional int32 state = 1;
inline bool CooperationFillResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CooperationFillResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CooperationFillResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CooperationFillResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 CooperationFillResponse::state() const {
  // @@protoc_insertion_point(field_get:main.CooperationFillResponse.state)
  return state_;
}
inline void CooperationFillResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.CooperationFillResponse.state)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace main

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CooperationModule_2eproto__INCLUDED
