// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Developing.proto

#ifndef PROTOBUF_Developing_2eproto__INCLUDED
#define PROTOBUF_Developing_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace main {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Developing_2eproto();
void protobuf_AssignDesc_Developing_2eproto();
void protobuf_ShutdownFile_Developing_2eproto();

class DevelopOfficerDetailRequest;
class DevelopOfficerDetailResponse;
class DevPointDetail;
class DevOfficerDetail;
class NoSavedDetail;
class DevelopOfficerRequest;
class DevelopOfficerResponse;
class SaveOfficerRequest;
class SaveOfficerResponse;
class GiveUpOfficerRequest;
class UseDevelopItemRequest;
class UseDevelopItemResponse;

enum DevelopingType {
  DEV_OFF_NOR = 0,
  DEV_OFF_SPE = 1
};
bool DevelopingType_IsValid(int value);
const DevelopingType DevelopingType_MIN = DEV_OFF_NOR;
const DevelopingType DevelopingType_MAX = DEV_OFF_SPE;
const int DevelopingType_ARRAYSIZE = DevelopingType_MAX + 1;

enum DevelopingCount {
  DEV_ONE = 0,
  DEV_TEN = 1
};
bool DevelopingCount_IsValid(int value);
const DevelopingCount DevelopingCount_MIN = DEV_ONE;
const DevelopingCount DevelopingCount_MAX = DEV_TEN;
const int DevelopingCount_ARRAYSIZE = DevelopingCount_MAX + 1;

// ===================================================================

class DevelopOfficerDetailRequest : public ::google::protobuf::MessageLite {
 public:
  DevelopOfficerDetailRequest();
  virtual ~DevelopOfficerDetailRequest();

  DevelopOfficerDetailRequest(const DevelopOfficerDetailRequest& from);

  inline DevelopOfficerDetailRequest& operator=(const DevelopOfficerDetailRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DevelopOfficerDetailRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DevelopOfficerDetailRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DevelopOfficerDetailRequest* other);

  // implements Message ----------------------------------------------

  DevelopOfficerDetailRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DevelopOfficerDetailRequest& from);
  void MergeFrom(const DevelopOfficerDetailRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ssId = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DevelopOfficerDetailRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static DevelopOfficerDetailRequest* default_instance_;
};
// -------------------------------------------------------------------

class DevelopOfficerDetailResponse : public ::google::protobuf::MessageLite {
 public:
  DevelopOfficerDetailResponse();
  virtual ~DevelopOfficerDetailResponse();

  DevelopOfficerDetailResponse(const DevelopOfficerDetailResponse& from);

  inline DevelopOfficerDetailResponse& operator=(const DevelopOfficerDetailResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DevelopOfficerDetailResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DevelopOfficerDetailResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DevelopOfficerDetailResponse* other);

  // implements Message ----------------------------------------------

  DevelopOfficerDetailResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DevelopOfficerDetailResponse& from);
  void MergeFrom(const DevelopOfficerDetailResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ssId = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // required bool saved = 2;
  inline bool has_saved() const;
  inline void clear_saved();
  static const int kSavedFieldNumber = 2;
  inline bool saved() const;
  inline void set_saved(bool value);

  // required .main.DevPointDetail pointDetail = 3;
  inline bool has_pointdetail() const;
  inline void clear_pointdetail();
  static const int kPointDetailFieldNumber = 3;
  inline const ::main::DevPointDetail& pointdetail() const;
  inline ::main::DevPointDetail* mutable_pointdetail();
  inline ::main::DevPointDetail* release_pointdetail();
  inline void set_allocated_pointdetail(::main::DevPointDetail* pointdetail);

  // optional .main.DevOfficerDetail officerDetail = 4;
  inline bool has_officerdetail() const;
  inline void clear_officerdetail();
  static const int kOfficerDetailFieldNumber = 4;
  inline const ::main::DevOfficerDetail& officerdetail() const;
  inline ::main::DevOfficerDetail* mutable_officerdetail();
  inline ::main::DevOfficerDetail* release_officerdetail();
  inline void set_allocated_officerdetail(::main::DevOfficerDetail* officerdetail);

  // optional .main.NoSavedDetail noSavedDetail = 5;
  inline bool has_nosaveddetail() const;
  inline void clear_nosaveddetail();
  static const int kNoSavedDetailFieldNumber = 5;
  inline const ::main::NoSavedDetail& nosaveddetail() const;
  inline ::main::NoSavedDetail* mutable_nosaveddetail();
  inline ::main::NoSavedDetail* release_nosaveddetail();
  inline void set_allocated_nosaveddetail(::main::NoSavedDetail* nosaveddetail);

  // required int32 norCoins = 6;
  inline bool has_norcoins() const;
  inline void clear_norcoins();
  static const int kNorCoinsFieldNumber = 6;
  inline ::google::protobuf::int32 norcoins() const;
  inline void set_norcoins(::google::protobuf::int32 value);

  // required int32 norItemNum = 7;
  inline bool has_noritemnum() const;
  inline void clear_noritemnum();
  static const int kNorItemNumFieldNumber = 7;
  inline ::google::protobuf::int32 noritemnum() const;
  inline void set_noritemnum(::google::protobuf::int32 value);

  // required int32 speGold = 8;
  inline bool has_spegold() const;
  inline void clear_spegold();
  static const int kSpeGoldFieldNumber = 8;
  inline ::google::protobuf::int32 spegold() const;
  inline void set_spegold(::google::protobuf::int32 value);

  // required int32 speItemNum = 9;
  inline bool has_speitemnum() const;
  inline void clear_speitemnum();
  static const int kSpeItemNumFieldNumber = 9;
  inline ::google::protobuf::int32 speitemnum() const;
  inline void set_speitemnum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DevelopOfficerDetailResponse)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_saved();
  inline void clear_has_saved();
  inline void set_has_pointdetail();
  inline void clear_has_pointdetail();
  inline void set_has_officerdetail();
  inline void clear_has_officerdetail();
  inline void set_has_nosaveddetail();
  inline void clear_has_nosaveddetail();
  inline void set_has_norcoins();
  inline void clear_has_norcoins();
  inline void set_has_noritemnum();
  inline void clear_has_noritemnum();
  inline void set_has_spegold();
  inline void clear_has_spegold();
  inline void set_has_speitemnum();
  inline void clear_has_speitemnum();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  bool saved_;
  ::main::DevPointDetail* pointdetail_;
  ::main::DevOfficerDetail* officerdetail_;
  ::main::NoSavedDetail* nosaveddetail_;
  ::google::protobuf::int32 norcoins_;
  ::google::protobuf::int32 noritemnum_;
  ::google::protobuf::int32 spegold_;
  ::google::protobuf::int32 speitemnum_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static DevelopOfficerDetailResponse* default_instance_;
};
// -------------------------------------------------------------------

class DevPointDetail : public ::google::protobuf::MessageLite {
 public:
  DevPointDetail();
  virtual ~DevPointDetail();

  DevPointDetail(const DevPointDetail& from);

  inline DevPointDetail& operator=(const DevPointDetail& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DevPointDetail& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DevPointDetail* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DevPointDetail* other);

  // implements Message ----------------------------------------------

  DevPointDetail* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DevPointDetail& from);
  void MergeFrom(const DevPointDetail& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 devPoint = 1;
  inline bool has_devpoint() const;
  inline void clear_devpoint();
  static const int kDevPointFieldNumber = 1;
  inline ::google::protobuf::int32 devpoint() const;
  inline void set_devpoint(::google::protobuf::int32 value);

  // required int32 addDevPoint = 2;
  inline bool has_adddevpoint() const;
  inline void clear_adddevpoint();
  static const int kAddDevPointFieldNumber = 2;
  inline ::google::protobuf::int32 adddevpoint() const;
  inline void set_adddevpoint(::google::protobuf::int32 value);

  // required int32 maxDevPoint = 3;
  inline bool has_maxdevpoint() const;
  inline void clear_maxdevpoint();
  static const int kMaxDevPointFieldNumber = 3;
  inline ::google::protobuf::int32 maxdevpoint() const;
  inline void set_maxdevpoint(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DevPointDetail)
 private:
  inline void set_has_devpoint();
  inline void clear_has_devpoint();
  inline void set_has_adddevpoint();
  inline void clear_has_adddevpoint();
  inline void set_has_maxdevpoint();
  inline void clear_has_maxdevpoint();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 devpoint_;
  ::google::protobuf::int32 adddevpoint_;
  ::google::protobuf::int32 maxdevpoint_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static DevPointDetail* default_instance_;
};
// -------------------------------------------------------------------

class DevOfficerDetail : public ::google::protobuf::MessageLite {
 public:
  DevOfficerDetail();
  virtual ~DevOfficerDetail();

  DevOfficerDetail(const DevOfficerDetail& from);

  inline DevOfficerDetail& operator=(const DevOfficerDetail& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DevOfficerDetail& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DevOfficerDetail* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DevOfficerDetail* other);

  // implements Message ----------------------------------------------

  DevOfficerDetail* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DevOfficerDetail& from);
  void MergeFrom(const DevOfficerDetail& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 extAtk = 1;
  inline bool has_extatk() const;
  inline void clear_extatk();
  static const int kExtAtkFieldNumber = 1;
  inline ::google::protobuf::int32 extatk() const;
  inline void set_extatk(::google::protobuf::int32 value);

  // optional int32 maxAtk = 2;
  inline bool has_maxatk() const;
  inline void clear_maxatk();
  static const int kMaxAtkFieldNumber = 2;
  inline ::google::protobuf::int32 maxatk() const;
  inline void set_maxatk(::google::protobuf::int32 value);

  // optional int32 extDef = 3;
  inline bool has_extdef() const;
  inline void clear_extdef();
  static const int kExtDefFieldNumber = 3;
  inline ::google::protobuf::int32 extdef() const;
  inline void set_extdef(::google::protobuf::int32 value);

  // optional int32 maxDef = 4;
  inline bool has_maxdef() const;
  inline void clear_maxdef();
  static const int kMaxDefFieldNumber = 4;
  inline ::google::protobuf::int32 maxdef() const;
  inline void set_maxdef(::google::protobuf::int32 value);

  // optional int32 extHp = 5;
  inline bool has_exthp() const;
  inline void clear_exthp();
  static const int kExtHpFieldNumber = 5;
  inline ::google::protobuf::int32 exthp() const;
  inline void set_exthp(::google::protobuf::int32 value);

  // optional int32 maxHp = 6;
  inline bool has_maxhp() const;
  inline void clear_maxhp();
  static const int kMaxHpFieldNumber = 6;
  inline ::google::protobuf::int32 maxhp() const;
  inline void set_maxhp(::google::protobuf::int32 value);

  // optional int32 extSp = 7;
  inline bool has_extsp() const;
  inline void clear_extsp();
  static const int kExtSpFieldNumber = 7;
  inline ::google::protobuf::int32 extsp() const;
  inline void set_extsp(::google::protobuf::int32 value);

  // optional int32 maxSp = 8;
  inline bool has_maxsp() const;
  inline void clear_maxsp();
  static const int kMaxSpFieldNumber = 8;
  inline ::google::protobuf::int32 maxsp() const;
  inline void set_maxsp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.DevOfficerDetail)
 private:
  inline void set_has_extatk();
  inline void clear_has_extatk();
  inline void set_has_maxatk();
  inline void clear_has_maxatk();
  inline void set_has_extdef();
  inline void clear_has_extdef();
  inline void set_has_maxdef();
  inline void clear_has_maxdef();
  inline void set_has_exthp();
  inline void clear_has_exthp();
  inline void set_has_maxhp();
  inline void clear_has_maxhp();
  inline void set_has_extsp();
  inline void clear_has_extsp();
  inline void set_has_maxsp();
  inline void clear_has_maxsp();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 extatk_;
  ::google::protobuf::int32 maxatk_;
  ::google::protobuf::int32 extdef_;
  ::google::protobuf::int32 maxdef_;
  ::google::protobuf::int32 exthp_;
  ::google::protobuf::int32 maxhp_;
  ::google::protobuf::int32 extsp_;
  ::google::protobuf::int32 maxsp_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static DevOfficerDetail* default_instance_;
};
// -------------------------------------------------------------------

class NoSavedDetail : public ::google::protobuf::MessageLite {
 public:
  NoSavedDetail();
  virtual ~NoSavedDetail();

  NoSavedDetail(const NoSavedDetail& from);

  inline NoSavedDetail& operator=(const NoSavedDetail& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const NoSavedDetail& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const NoSavedDetail* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(NoSavedDetail* other);

  // implements Message ----------------------------------------------

  NoSavedDetail* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const NoSavedDetail& from);
  void MergeFrom(const NoSavedDetail& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 atk = 1;
  inline bool has_atk() const;
  inline void clear_atk();
  static const int kAtkFieldNumber = 1;
  inline ::google::protobuf::int32 atk() const;
  inline void set_atk(::google::protobuf::int32 value);

  // required int32 def = 2;
  inline bool has_def() const;
  inline void clear_def();
  static const int kDefFieldNumber = 2;
  inline ::google::protobuf::int32 def() const;
  inline void set_def(::google::protobuf::int32 value);

  // required int32 hp = 3;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 3;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // required int32 sp = 4;
  inline bool has_sp() const;
  inline void clear_sp();
  static const int kSpFieldNumber = 4;
  inline ::google::protobuf::int32 sp() const;
  inline void set_sp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.NoSavedDetail)
 private:
  inline void set_has_atk();
  inline void clear_has_atk();
  inline void set_has_def();
  inline void clear_has_def();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_sp();
  inline void clear_has_sp();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 atk_;
  ::google::protobuf::int32 def_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 sp_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static NoSavedDetail* default_instance_;
};
// -------------------------------------------------------------------

class DevelopOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  DevelopOfficerRequest();
  virtual ~DevelopOfficerRequest();

  DevelopOfficerRequest(const DevelopOfficerRequest& from);

  inline DevelopOfficerRequest& operator=(const DevelopOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DevelopOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DevelopOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DevelopOfficerRequest* other);

  // implements Message ----------------------------------------------

  DevelopOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DevelopOfficerRequest& from);
  void MergeFrom(const DevelopOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ssId = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // required .main.DevelopingType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::main::DevelopingType type() const;
  inline void set_type(::main::DevelopingType value);

  // required .main.DevelopingCount count = 3;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 3;
  inline ::main::DevelopingCount count() const;
  inline void set_count(::main::DevelopingCount value);

  // @@protoc_insertion_point(class_scope:main.DevelopOfficerRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_count();
  inline void clear_has_count();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  int type_;
  int count_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static DevelopOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class DevelopOfficerResponse : public ::google::protobuf::MessageLite {
 public:
  DevelopOfficerResponse();
  virtual ~DevelopOfficerResponse();

  DevelopOfficerResponse(const DevelopOfficerResponse& from);

  inline DevelopOfficerResponse& operator=(const DevelopOfficerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DevelopOfficerResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DevelopOfficerResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DevelopOfficerResponse* other);

  // implements Message ----------------------------------------------

  DevelopOfficerResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DevelopOfficerResponse& from);
  void MergeFrom(const DevelopOfficerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 ssId = 2;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 2;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // optional .main.NoSavedDetail noSavedDetail = 3;
  inline bool has_nosaveddetail() const;
  inline void clear_nosaveddetail();
  static const int kNoSavedDetailFieldNumber = 3;
  inline const ::main::NoSavedDetail& nosaveddetail() const;
  inline ::main::NoSavedDetail* mutable_nosaveddetail();
  inline ::main::NoSavedDetail* release_nosaveddetail();
  inline void set_allocated_nosaveddetail(::main::NoSavedDetail* nosaveddetail);

  // @@protoc_insertion_point(class_scope:main.DevelopOfficerResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_nosaveddetail();
  inline void clear_has_nosaveddetail();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 ssid_;
  ::main::NoSavedDetail* nosaveddetail_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static DevelopOfficerResponse* default_instance_;
};
// -------------------------------------------------------------------

class SaveOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  SaveOfficerRequest();
  virtual ~SaveOfficerRequest();

  SaveOfficerRequest(const SaveOfficerRequest& from);

  inline SaveOfficerRequest& operator=(const SaveOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const SaveOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SaveOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SaveOfficerRequest* other);

  // implements Message ----------------------------------------------

  SaveOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SaveOfficerRequest& from);
  void MergeFrom(const SaveOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ssId = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.SaveOfficerRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static SaveOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class SaveOfficerResponse : public ::google::protobuf::MessageLite {
 public:
  SaveOfficerResponse();
  virtual ~SaveOfficerResponse();

  SaveOfficerResponse(const SaveOfficerResponse& from);

  inline SaveOfficerResponse& operator=(const SaveOfficerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const SaveOfficerResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SaveOfficerResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SaveOfficerResponse* other);

  // implements Message ----------------------------------------------

  SaveOfficerResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SaveOfficerResponse& from);
  void MergeFrom(const SaveOfficerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 ssId = 2;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 2;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // optional .main.DevOfficerDetail officerDetail = 3;
  inline bool has_officerdetail() const;
  inline void clear_officerdetail();
  static const int kOfficerDetailFieldNumber = 3;
  inline const ::main::DevOfficerDetail& officerdetail() const;
  inline ::main::DevOfficerDetail* mutable_officerdetail();
  inline ::main::DevOfficerDetail* release_officerdetail();
  inline void set_allocated_officerdetail(::main::DevOfficerDetail* officerdetail);

  // optional .main.DevPointDetail pointDetail = 4;
  inline bool has_pointdetail() const;
  inline void clear_pointdetail();
  static const int kPointDetailFieldNumber = 4;
  inline const ::main::DevPointDetail& pointdetail() const;
  inline ::main::DevPointDetail* mutable_pointdetail();
  inline ::main::DevPointDetail* release_pointdetail();
  inline void set_allocated_pointdetail(::main::DevPointDetail* pointdetail);

  // @@protoc_insertion_point(class_scope:main.SaveOfficerResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_officerdetail();
  inline void clear_has_officerdetail();
  inline void set_has_pointdetail();
  inline void clear_has_pointdetail();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 ssid_;
  ::main::DevOfficerDetail* officerdetail_;
  ::main::DevPointDetail* pointdetail_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static SaveOfficerResponse* default_instance_;
};
// -------------------------------------------------------------------

class GiveUpOfficerRequest : public ::google::protobuf::MessageLite {
 public:
  GiveUpOfficerRequest();
  virtual ~GiveUpOfficerRequest();

  GiveUpOfficerRequest(const GiveUpOfficerRequest& from);

  inline GiveUpOfficerRequest& operator=(const GiveUpOfficerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GiveUpOfficerRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GiveUpOfficerRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GiveUpOfficerRequest* other);

  // implements Message ----------------------------------------------

  GiveUpOfficerRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GiveUpOfficerRequest& from);
  void MergeFrom(const GiveUpOfficerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ssId = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.GiveUpOfficerRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static GiveUpOfficerRequest* default_instance_;
};
// -------------------------------------------------------------------

class UseDevelopItemRequest : public ::google::protobuf::MessageLite {
 public:
  UseDevelopItemRequest();
  virtual ~UseDevelopItemRequest();

  UseDevelopItemRequest(const UseDevelopItemRequest& from);

  inline UseDevelopItemRequest& operator=(const UseDevelopItemRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const UseDevelopItemRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const UseDevelopItemRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(UseDevelopItemRequest* other);

  // implements Message ----------------------------------------------

  UseDevelopItemRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const UseDevelopItemRequest& from);
  void MergeFrom(const UseDevelopItemRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ssId = 1;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 1;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // required int32 itemNum = 2;
  inline bool has_itemnum() const;
  inline void clear_itemnum();
  static const int kItemNumFieldNumber = 2;
  inline ::google::protobuf::int32 itemnum() const;
  inline void set_itemnum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:main.UseDevelopItemRequest)
 private:
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_itemnum();
  inline void clear_has_itemnum();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ssid_;
  ::google::protobuf::int32 itemnum_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static UseDevelopItemRequest* default_instance_;
};
// -------------------------------------------------------------------

class UseDevelopItemResponse : public ::google::protobuf::MessageLite {
 public:
  UseDevelopItemResponse();
  virtual ~UseDevelopItemResponse();

  UseDevelopItemResponse(const UseDevelopItemResponse& from);

  inline UseDevelopItemResponse& operator=(const UseDevelopItemResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const UseDevelopItemResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const UseDevelopItemResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(UseDevelopItemResponse* other);

  // implements Message ----------------------------------------------

  UseDevelopItemResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const UseDevelopItemResponse& from);
  void MergeFrom(const UseDevelopItemResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 state = 1;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 1;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // required int32 ssId = 2;
  inline bool has_ssid() const;
  inline void clear_ssid();
  static const int kSsIdFieldNumber = 2;
  inline ::google::protobuf::int32 ssid() const;
  inline void set_ssid(::google::protobuf::int32 value);

  // optional .main.DevPointDetail pointDetail = 3;
  inline bool has_pointdetail() const;
  inline void clear_pointdetail();
  static const int kPointDetailFieldNumber = 3;
  inline const ::main::DevPointDetail& pointdetail() const;
  inline ::main::DevPointDetail* mutable_pointdetail();
  inline ::main::DevPointDetail* release_pointdetail();
  inline void set_allocated_pointdetail(::main::DevPointDetail* pointdetail);

  // optional .main.DevOfficerDetail officerDetail = 4;
  inline bool has_officerdetail() const;
  inline void clear_officerdetail();
  static const int kOfficerDetailFieldNumber = 4;
  inline const ::main::DevOfficerDetail& officerdetail() const;
  inline ::main::DevOfficerDetail* mutable_officerdetail();
  inline ::main::DevOfficerDetail* release_officerdetail();
  inline void set_allocated_officerdetail(::main::DevOfficerDetail* officerdetail);

  // @@protoc_insertion_point(class_scope:main.UseDevelopItemResponse)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_ssid();
  inline void clear_has_ssid();
  inline void set_has_pointdetail();
  inline void clear_has_pointdetail();
  inline void set_has_officerdetail();
  inline void clear_has_officerdetail();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 ssid_;
  ::main::DevPointDetail* pointdetail_;
  ::main::DevOfficerDetail* officerdetail_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Developing_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Developing_2eproto();
  #endif
  friend void protobuf_AssignDesc_Developing_2eproto();
  friend void protobuf_ShutdownFile_Developing_2eproto();

  void InitAsDefaultInstance();
  static UseDevelopItemResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// DevelopOfficerDetailRequest

// required int32 ssId = 1;
inline bool DevelopOfficerDetailRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevelopOfficerDetailRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevelopOfficerDetailRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevelopOfficerDetailRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 DevelopOfficerDetailRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailRequest.ssId)
  return ssid_;
}
inline void DevelopOfficerDetailRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailRequest.ssId)
}

// -------------------------------------------------------------------

// DevelopOfficerDetailResponse

// required int32 ssId = 1;
inline bool DevelopOfficerDetailResponse::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevelopOfficerDetailResponse::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevelopOfficerDetailResponse::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 DevelopOfficerDetailResponse::ssid() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.ssId)
  return ssid_;
}
inline void DevelopOfficerDetailResponse::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailResponse.ssId)
}

// required bool saved = 2;
inline bool DevelopOfficerDetailResponse::has_saved() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_saved() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DevelopOfficerDetailResponse::clear_has_saved() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DevelopOfficerDetailResponse::clear_saved() {
  saved_ = false;
  clear_has_saved();
}
inline bool DevelopOfficerDetailResponse::saved() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.saved)
  return saved_;
}
inline void DevelopOfficerDetailResponse::set_saved(bool value) {
  set_has_saved();
  saved_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailResponse.saved)
}

// required .main.DevPointDetail pointDetail = 3;
inline bool DevelopOfficerDetailResponse::has_pointdetail() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_pointdetail() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DevelopOfficerDetailResponse::clear_has_pointdetail() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DevelopOfficerDetailResponse::clear_pointdetail() {
  if (pointdetail_ != NULL) pointdetail_->::main::DevPointDetail::Clear();
  clear_has_pointdetail();
}
inline const ::main::DevPointDetail& DevelopOfficerDetailResponse::pointdetail() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.pointDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return pointdetail_ != NULL ? *pointdetail_ : *default_instance().pointdetail_;
#else
  return pointdetail_ != NULL ? *pointdetail_ : *default_instance_->pointdetail_;
#endif
}
inline ::main::DevPointDetail* DevelopOfficerDetailResponse::mutable_pointdetail() {
  set_has_pointdetail();
  if (pointdetail_ == NULL) pointdetail_ = new ::main::DevPointDetail;
  // @@protoc_insertion_point(field_mutable:main.DevelopOfficerDetailResponse.pointDetail)
  return pointdetail_;
}
inline ::main::DevPointDetail* DevelopOfficerDetailResponse::release_pointdetail() {
  clear_has_pointdetail();
  ::main::DevPointDetail* temp = pointdetail_;
  pointdetail_ = NULL;
  return temp;
}
inline void DevelopOfficerDetailResponse::set_allocated_pointdetail(::main::DevPointDetail* pointdetail) {
  delete pointdetail_;
  pointdetail_ = pointdetail;
  if (pointdetail) {
    set_has_pointdetail();
  } else {
    clear_has_pointdetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.DevelopOfficerDetailResponse.pointDetail)
}

// optional .main.DevOfficerDetail officerDetail = 4;
inline bool DevelopOfficerDetailResponse::has_officerdetail() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_officerdetail() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DevelopOfficerDetailResponse::clear_has_officerdetail() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DevelopOfficerDetailResponse::clear_officerdetail() {
  if (officerdetail_ != NULL) officerdetail_->::main::DevOfficerDetail::Clear();
  clear_has_officerdetail();
}
inline const ::main::DevOfficerDetail& DevelopOfficerDetailResponse::officerdetail() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.officerDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return officerdetail_ != NULL ? *officerdetail_ : *default_instance().officerdetail_;
#else
  return officerdetail_ != NULL ? *officerdetail_ : *default_instance_->officerdetail_;
#endif
}
inline ::main::DevOfficerDetail* DevelopOfficerDetailResponse::mutable_officerdetail() {
  set_has_officerdetail();
  if (officerdetail_ == NULL) officerdetail_ = new ::main::DevOfficerDetail;
  // @@protoc_insertion_point(field_mutable:main.DevelopOfficerDetailResponse.officerDetail)
  return officerdetail_;
}
inline ::main::DevOfficerDetail* DevelopOfficerDetailResponse::release_officerdetail() {
  clear_has_officerdetail();
  ::main::DevOfficerDetail* temp = officerdetail_;
  officerdetail_ = NULL;
  return temp;
}
inline void DevelopOfficerDetailResponse::set_allocated_officerdetail(::main::DevOfficerDetail* officerdetail) {
  delete officerdetail_;
  officerdetail_ = officerdetail;
  if (officerdetail) {
    set_has_officerdetail();
  } else {
    clear_has_officerdetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.DevelopOfficerDetailResponse.officerDetail)
}

// optional .main.NoSavedDetail noSavedDetail = 5;
inline bool DevelopOfficerDetailResponse::has_nosaveddetail() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_nosaveddetail() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DevelopOfficerDetailResponse::clear_has_nosaveddetail() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DevelopOfficerDetailResponse::clear_nosaveddetail() {
  if (nosaveddetail_ != NULL) nosaveddetail_->::main::NoSavedDetail::Clear();
  clear_has_nosaveddetail();
}
inline const ::main::NoSavedDetail& DevelopOfficerDetailResponse::nosaveddetail() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.noSavedDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return nosaveddetail_ != NULL ? *nosaveddetail_ : *default_instance().nosaveddetail_;
#else
  return nosaveddetail_ != NULL ? *nosaveddetail_ : *default_instance_->nosaveddetail_;
#endif
}
inline ::main::NoSavedDetail* DevelopOfficerDetailResponse::mutable_nosaveddetail() {
  set_has_nosaveddetail();
  if (nosaveddetail_ == NULL) nosaveddetail_ = new ::main::NoSavedDetail;
  // @@protoc_insertion_point(field_mutable:main.DevelopOfficerDetailResponse.noSavedDetail)
  return nosaveddetail_;
}
inline ::main::NoSavedDetail* DevelopOfficerDetailResponse::release_nosaveddetail() {
  clear_has_nosaveddetail();
  ::main::NoSavedDetail* temp = nosaveddetail_;
  nosaveddetail_ = NULL;
  return temp;
}
inline void DevelopOfficerDetailResponse::set_allocated_nosaveddetail(::main::NoSavedDetail* nosaveddetail) {
  delete nosaveddetail_;
  nosaveddetail_ = nosaveddetail;
  if (nosaveddetail) {
    set_has_nosaveddetail();
  } else {
    clear_has_nosaveddetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.DevelopOfficerDetailResponse.noSavedDetail)
}

// required int32 norCoins = 6;
inline bool DevelopOfficerDetailResponse::has_norcoins() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_norcoins() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DevelopOfficerDetailResponse::clear_has_norcoins() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DevelopOfficerDetailResponse::clear_norcoins() {
  norcoins_ = 0;
  clear_has_norcoins();
}
inline ::google::protobuf::int32 DevelopOfficerDetailResponse::norcoins() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.norCoins)
  return norcoins_;
}
inline void DevelopOfficerDetailResponse::set_norcoins(::google::protobuf::int32 value) {
  set_has_norcoins();
  norcoins_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailResponse.norCoins)
}

// required int32 norItemNum = 7;
inline bool DevelopOfficerDetailResponse::has_noritemnum() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_noritemnum() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DevelopOfficerDetailResponse::clear_has_noritemnum() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DevelopOfficerDetailResponse::clear_noritemnum() {
  noritemnum_ = 0;
  clear_has_noritemnum();
}
inline ::google::protobuf::int32 DevelopOfficerDetailResponse::noritemnum() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.norItemNum)
  return noritemnum_;
}
inline void DevelopOfficerDetailResponse::set_noritemnum(::google::protobuf::int32 value) {
  set_has_noritemnum();
  noritemnum_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailResponse.norItemNum)
}

// required int32 speGold = 8;
inline bool DevelopOfficerDetailResponse::has_spegold() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_spegold() {
  _has_bits_[0] |= 0x00000080u;
}
inline void DevelopOfficerDetailResponse::clear_has_spegold() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void DevelopOfficerDetailResponse::clear_spegold() {
  spegold_ = 0;
  clear_has_spegold();
}
inline ::google::protobuf::int32 DevelopOfficerDetailResponse::spegold() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.speGold)
  return spegold_;
}
inline void DevelopOfficerDetailResponse::set_spegold(::google::protobuf::int32 value) {
  set_has_spegold();
  spegold_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailResponse.speGold)
}

// required int32 speItemNum = 9;
inline bool DevelopOfficerDetailResponse::has_speitemnum() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void DevelopOfficerDetailResponse::set_has_speitemnum() {
  _has_bits_[0] |= 0x00000100u;
}
inline void DevelopOfficerDetailResponse::clear_has_speitemnum() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void DevelopOfficerDetailResponse::clear_speitemnum() {
  speitemnum_ = 0;
  clear_has_speitemnum();
}
inline ::google::protobuf::int32 DevelopOfficerDetailResponse::speitemnum() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerDetailResponse.speItemNum)
  return speitemnum_;
}
inline void DevelopOfficerDetailResponse::set_speitemnum(::google::protobuf::int32 value) {
  set_has_speitemnum();
  speitemnum_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerDetailResponse.speItemNum)
}

// -------------------------------------------------------------------

// DevPointDetail

// required int32 devPoint = 1;
inline bool DevPointDetail::has_devpoint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevPointDetail::set_has_devpoint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevPointDetail::clear_has_devpoint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevPointDetail::clear_devpoint() {
  devpoint_ = 0;
  clear_has_devpoint();
}
inline ::google::protobuf::int32 DevPointDetail::devpoint() const {
  // @@protoc_insertion_point(field_get:main.DevPointDetail.devPoint)
  return devpoint_;
}
inline void DevPointDetail::set_devpoint(::google::protobuf::int32 value) {
  set_has_devpoint();
  devpoint_ = value;
  // @@protoc_insertion_point(field_set:main.DevPointDetail.devPoint)
}

// required int32 addDevPoint = 2;
inline bool DevPointDetail::has_adddevpoint() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DevPointDetail::set_has_adddevpoint() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DevPointDetail::clear_has_adddevpoint() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DevPointDetail::clear_adddevpoint() {
  adddevpoint_ = 0;
  clear_has_adddevpoint();
}
inline ::google::protobuf::int32 DevPointDetail::adddevpoint() const {
  // @@protoc_insertion_point(field_get:main.DevPointDetail.addDevPoint)
  return adddevpoint_;
}
inline void DevPointDetail::set_adddevpoint(::google::protobuf::int32 value) {
  set_has_adddevpoint();
  adddevpoint_ = value;
  // @@protoc_insertion_point(field_set:main.DevPointDetail.addDevPoint)
}

// required int32 maxDevPoint = 3;
inline bool DevPointDetail::has_maxdevpoint() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DevPointDetail::set_has_maxdevpoint() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DevPointDetail::clear_has_maxdevpoint() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DevPointDetail::clear_maxdevpoint() {
  maxdevpoint_ = 0;
  clear_has_maxdevpoint();
}
inline ::google::protobuf::int32 DevPointDetail::maxdevpoint() const {
  // @@protoc_insertion_point(field_get:main.DevPointDetail.maxDevPoint)
  return maxdevpoint_;
}
inline void DevPointDetail::set_maxdevpoint(::google::protobuf::int32 value) {
  set_has_maxdevpoint();
  maxdevpoint_ = value;
  // @@protoc_insertion_point(field_set:main.DevPointDetail.maxDevPoint)
}

// -------------------------------------------------------------------

// DevOfficerDetail

// optional int32 extAtk = 1;
inline bool DevOfficerDetail::has_extatk() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevOfficerDetail::set_has_extatk() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevOfficerDetail::clear_has_extatk() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevOfficerDetail::clear_extatk() {
  extatk_ = 0;
  clear_has_extatk();
}
inline ::google::protobuf::int32 DevOfficerDetail::extatk() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.extAtk)
  return extatk_;
}
inline void DevOfficerDetail::set_extatk(::google::protobuf::int32 value) {
  set_has_extatk();
  extatk_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.extAtk)
}

// optional int32 maxAtk = 2;
inline bool DevOfficerDetail::has_maxatk() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DevOfficerDetail::set_has_maxatk() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DevOfficerDetail::clear_has_maxatk() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DevOfficerDetail::clear_maxatk() {
  maxatk_ = 0;
  clear_has_maxatk();
}
inline ::google::protobuf::int32 DevOfficerDetail::maxatk() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.maxAtk)
  return maxatk_;
}
inline void DevOfficerDetail::set_maxatk(::google::protobuf::int32 value) {
  set_has_maxatk();
  maxatk_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.maxAtk)
}

// optional int32 extDef = 3;
inline bool DevOfficerDetail::has_extdef() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DevOfficerDetail::set_has_extdef() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DevOfficerDetail::clear_has_extdef() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DevOfficerDetail::clear_extdef() {
  extdef_ = 0;
  clear_has_extdef();
}
inline ::google::protobuf::int32 DevOfficerDetail::extdef() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.extDef)
  return extdef_;
}
inline void DevOfficerDetail::set_extdef(::google::protobuf::int32 value) {
  set_has_extdef();
  extdef_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.extDef)
}

// optional int32 maxDef = 4;
inline bool DevOfficerDetail::has_maxdef() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DevOfficerDetail::set_has_maxdef() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DevOfficerDetail::clear_has_maxdef() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DevOfficerDetail::clear_maxdef() {
  maxdef_ = 0;
  clear_has_maxdef();
}
inline ::google::protobuf::int32 DevOfficerDetail::maxdef() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.maxDef)
  return maxdef_;
}
inline void DevOfficerDetail::set_maxdef(::google::protobuf::int32 value) {
  set_has_maxdef();
  maxdef_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.maxDef)
}

// optional int32 extHp = 5;
inline bool DevOfficerDetail::has_exthp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DevOfficerDetail::set_has_exthp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DevOfficerDetail::clear_has_exthp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DevOfficerDetail::clear_exthp() {
  exthp_ = 0;
  clear_has_exthp();
}
inline ::google::protobuf::int32 DevOfficerDetail::exthp() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.extHp)
  return exthp_;
}
inline void DevOfficerDetail::set_exthp(::google::protobuf::int32 value) {
  set_has_exthp();
  exthp_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.extHp)
}

// optional int32 maxHp = 6;
inline bool DevOfficerDetail::has_maxhp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DevOfficerDetail::set_has_maxhp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DevOfficerDetail::clear_has_maxhp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DevOfficerDetail::clear_maxhp() {
  maxhp_ = 0;
  clear_has_maxhp();
}
inline ::google::protobuf::int32 DevOfficerDetail::maxhp() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.maxHp)
  return maxhp_;
}
inline void DevOfficerDetail::set_maxhp(::google::protobuf::int32 value) {
  set_has_maxhp();
  maxhp_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.maxHp)
}

// optional int32 extSp = 7;
inline bool DevOfficerDetail::has_extsp() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DevOfficerDetail::set_has_extsp() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DevOfficerDetail::clear_has_extsp() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DevOfficerDetail::clear_extsp() {
  extsp_ = 0;
  clear_has_extsp();
}
inline ::google::protobuf::int32 DevOfficerDetail::extsp() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.extSp)
  return extsp_;
}
inline void DevOfficerDetail::set_extsp(::google::protobuf::int32 value) {
  set_has_extsp();
  extsp_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.extSp)
}

// optional int32 maxSp = 8;
inline bool DevOfficerDetail::has_maxsp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void DevOfficerDetail::set_has_maxsp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void DevOfficerDetail::clear_has_maxsp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void DevOfficerDetail::clear_maxsp() {
  maxsp_ = 0;
  clear_has_maxsp();
}
inline ::google::protobuf::int32 DevOfficerDetail::maxsp() const {
  // @@protoc_insertion_point(field_get:main.DevOfficerDetail.maxSp)
  return maxsp_;
}
inline void DevOfficerDetail::set_maxsp(::google::protobuf::int32 value) {
  set_has_maxsp();
  maxsp_ = value;
  // @@protoc_insertion_point(field_set:main.DevOfficerDetail.maxSp)
}

// -------------------------------------------------------------------

// NoSavedDetail

// required int32 atk = 1;
inline bool NoSavedDetail::has_atk() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NoSavedDetail::set_has_atk() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NoSavedDetail::clear_has_atk() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NoSavedDetail::clear_atk() {
  atk_ = 0;
  clear_has_atk();
}
inline ::google::protobuf::int32 NoSavedDetail::atk() const {
  // @@protoc_insertion_point(field_get:main.NoSavedDetail.atk)
  return atk_;
}
inline void NoSavedDetail::set_atk(::google::protobuf::int32 value) {
  set_has_atk();
  atk_ = value;
  // @@protoc_insertion_point(field_set:main.NoSavedDetail.atk)
}

// required int32 def = 2;
inline bool NoSavedDetail::has_def() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NoSavedDetail::set_has_def() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NoSavedDetail::clear_has_def() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NoSavedDetail::clear_def() {
  def_ = 0;
  clear_has_def();
}
inline ::google::protobuf::int32 NoSavedDetail::def() const {
  // @@protoc_insertion_point(field_get:main.NoSavedDetail.def)
  return def_;
}
inline void NoSavedDetail::set_def(::google::protobuf::int32 value) {
  set_has_def();
  def_ = value;
  // @@protoc_insertion_point(field_set:main.NoSavedDetail.def)
}

// required int32 hp = 3;
inline bool NoSavedDetail::has_hp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NoSavedDetail::set_has_hp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NoSavedDetail::clear_has_hp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NoSavedDetail::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 NoSavedDetail::hp() const {
  // @@protoc_insertion_point(field_get:main.NoSavedDetail.hp)
  return hp_;
}
inline void NoSavedDetail::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
  // @@protoc_insertion_point(field_set:main.NoSavedDetail.hp)
}

// required int32 sp = 4;
inline bool NoSavedDetail::has_sp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NoSavedDetail::set_has_sp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NoSavedDetail::clear_has_sp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NoSavedDetail::clear_sp() {
  sp_ = 0;
  clear_has_sp();
}
inline ::google::protobuf::int32 NoSavedDetail::sp() const {
  // @@protoc_insertion_point(field_get:main.NoSavedDetail.sp)
  return sp_;
}
inline void NoSavedDetail::set_sp(::google::protobuf::int32 value) {
  set_has_sp();
  sp_ = value;
  // @@protoc_insertion_point(field_set:main.NoSavedDetail.sp)
}

// -------------------------------------------------------------------

// DevelopOfficerRequest

// required int32 ssId = 1;
inline bool DevelopOfficerRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevelopOfficerRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevelopOfficerRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevelopOfficerRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 DevelopOfficerRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerRequest.ssId)
  return ssid_;
}
inline void DevelopOfficerRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerRequest.ssId)
}

// required .main.DevelopingType type = 2;
inline bool DevelopOfficerRequest::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DevelopOfficerRequest::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DevelopOfficerRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DevelopOfficerRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::main::DevelopingType DevelopOfficerRequest::type() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerRequest.type)
  return static_cast< ::main::DevelopingType >(type_);
}
inline void DevelopOfficerRequest::set_type(::main::DevelopingType value) {
  assert(::main::DevelopingType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerRequest.type)
}

// required .main.DevelopingCount count = 3;
inline bool DevelopOfficerRequest::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DevelopOfficerRequest::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DevelopOfficerRequest::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DevelopOfficerRequest::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::main::DevelopingCount DevelopOfficerRequest::count() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerRequest.count)
  return static_cast< ::main::DevelopingCount >(count_);
}
inline void DevelopOfficerRequest::set_count(::main::DevelopingCount value) {
  assert(::main::DevelopingCount_IsValid(value));
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerRequest.count)
}

// -------------------------------------------------------------------

// DevelopOfficerResponse

// required int32 state = 1;
inline bool DevelopOfficerResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevelopOfficerResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevelopOfficerResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevelopOfficerResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 DevelopOfficerResponse::state() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerResponse.state)
  return state_;
}
inline void DevelopOfficerResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerResponse.state)
}

// required int32 ssId = 2;
inline bool DevelopOfficerResponse::has_ssid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DevelopOfficerResponse::set_has_ssid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DevelopOfficerResponse::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DevelopOfficerResponse::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 DevelopOfficerResponse::ssid() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerResponse.ssId)
  return ssid_;
}
inline void DevelopOfficerResponse::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.DevelopOfficerResponse.ssId)
}

// optional .main.NoSavedDetail noSavedDetail = 3;
inline bool DevelopOfficerResponse::has_nosaveddetail() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DevelopOfficerResponse::set_has_nosaveddetail() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DevelopOfficerResponse::clear_has_nosaveddetail() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DevelopOfficerResponse::clear_nosaveddetail() {
  if (nosaveddetail_ != NULL) nosaveddetail_->::main::NoSavedDetail::Clear();
  clear_has_nosaveddetail();
}
inline const ::main::NoSavedDetail& DevelopOfficerResponse::nosaveddetail() const {
  // @@protoc_insertion_point(field_get:main.DevelopOfficerResponse.noSavedDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return nosaveddetail_ != NULL ? *nosaveddetail_ : *default_instance().nosaveddetail_;
#else
  return nosaveddetail_ != NULL ? *nosaveddetail_ : *default_instance_->nosaveddetail_;
#endif
}
inline ::main::NoSavedDetail* DevelopOfficerResponse::mutable_nosaveddetail() {
  set_has_nosaveddetail();
  if (nosaveddetail_ == NULL) nosaveddetail_ = new ::main::NoSavedDetail;
  // @@protoc_insertion_point(field_mutable:main.DevelopOfficerResponse.noSavedDetail)
  return nosaveddetail_;
}
inline ::main::NoSavedDetail* DevelopOfficerResponse::release_nosaveddetail() {
  clear_has_nosaveddetail();
  ::main::NoSavedDetail* temp = nosaveddetail_;
  nosaveddetail_ = NULL;
  return temp;
}
inline void DevelopOfficerResponse::set_allocated_nosaveddetail(::main::NoSavedDetail* nosaveddetail) {
  delete nosaveddetail_;
  nosaveddetail_ = nosaveddetail;
  if (nosaveddetail) {
    set_has_nosaveddetail();
  } else {
    clear_has_nosaveddetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.DevelopOfficerResponse.noSavedDetail)
}

// -------------------------------------------------------------------

// SaveOfficerRequest

// required int32 ssId = 1;
inline bool SaveOfficerRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SaveOfficerRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SaveOfficerRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SaveOfficerRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 SaveOfficerRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.SaveOfficerRequest.ssId)
  return ssid_;
}
inline void SaveOfficerRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.SaveOfficerRequest.ssId)
}

// -------------------------------------------------------------------

// SaveOfficerResponse

// required int32 state = 1;
inline bool SaveOfficerResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SaveOfficerResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SaveOfficerResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SaveOfficerResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 SaveOfficerResponse::state() const {
  // @@protoc_insertion_point(field_get:main.SaveOfficerResponse.state)
  return state_;
}
inline void SaveOfficerResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.SaveOfficerResponse.state)
}

// required int32 ssId = 2;
inline bool SaveOfficerResponse::has_ssid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SaveOfficerResponse::set_has_ssid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SaveOfficerResponse::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SaveOfficerResponse::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 SaveOfficerResponse::ssid() const {
  // @@protoc_insertion_point(field_get:main.SaveOfficerResponse.ssId)
  return ssid_;
}
inline void SaveOfficerResponse::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.SaveOfficerResponse.ssId)
}

// optional .main.DevOfficerDetail officerDetail = 3;
inline bool SaveOfficerResponse::has_officerdetail() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SaveOfficerResponse::set_has_officerdetail() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SaveOfficerResponse::clear_has_officerdetail() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SaveOfficerResponse::clear_officerdetail() {
  if (officerdetail_ != NULL) officerdetail_->::main::DevOfficerDetail::Clear();
  clear_has_officerdetail();
}
inline const ::main::DevOfficerDetail& SaveOfficerResponse::officerdetail() const {
  // @@protoc_insertion_point(field_get:main.SaveOfficerResponse.officerDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return officerdetail_ != NULL ? *officerdetail_ : *default_instance().officerdetail_;
#else
  return officerdetail_ != NULL ? *officerdetail_ : *default_instance_->officerdetail_;
#endif
}
inline ::main::DevOfficerDetail* SaveOfficerResponse::mutable_officerdetail() {
  set_has_officerdetail();
  if (officerdetail_ == NULL) officerdetail_ = new ::main::DevOfficerDetail;
  // @@protoc_insertion_point(field_mutable:main.SaveOfficerResponse.officerDetail)
  return officerdetail_;
}
inline ::main::DevOfficerDetail* SaveOfficerResponse::release_officerdetail() {
  clear_has_officerdetail();
  ::main::DevOfficerDetail* temp = officerdetail_;
  officerdetail_ = NULL;
  return temp;
}
inline void SaveOfficerResponse::set_allocated_officerdetail(::main::DevOfficerDetail* officerdetail) {
  delete officerdetail_;
  officerdetail_ = officerdetail;
  if (officerdetail) {
    set_has_officerdetail();
  } else {
    clear_has_officerdetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.SaveOfficerResponse.officerDetail)
}

// optional .main.DevPointDetail pointDetail = 4;
inline bool SaveOfficerResponse::has_pointdetail() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SaveOfficerResponse::set_has_pointdetail() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SaveOfficerResponse::clear_has_pointdetail() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SaveOfficerResponse::clear_pointdetail() {
  if (pointdetail_ != NULL) pointdetail_->::main::DevPointDetail::Clear();
  clear_has_pointdetail();
}
inline const ::main::DevPointDetail& SaveOfficerResponse::pointdetail() const {
  // @@protoc_insertion_point(field_get:main.SaveOfficerResponse.pointDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return pointdetail_ != NULL ? *pointdetail_ : *default_instance().pointdetail_;
#else
  return pointdetail_ != NULL ? *pointdetail_ : *default_instance_->pointdetail_;
#endif
}
inline ::main::DevPointDetail* SaveOfficerResponse::mutable_pointdetail() {
  set_has_pointdetail();
  if (pointdetail_ == NULL) pointdetail_ = new ::main::DevPointDetail;
  // @@protoc_insertion_point(field_mutable:main.SaveOfficerResponse.pointDetail)
  return pointdetail_;
}
inline ::main::DevPointDetail* SaveOfficerResponse::release_pointdetail() {
  clear_has_pointdetail();
  ::main::DevPointDetail* temp = pointdetail_;
  pointdetail_ = NULL;
  return temp;
}
inline void SaveOfficerResponse::set_allocated_pointdetail(::main::DevPointDetail* pointdetail) {
  delete pointdetail_;
  pointdetail_ = pointdetail;
  if (pointdetail) {
    set_has_pointdetail();
  } else {
    clear_has_pointdetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.SaveOfficerResponse.pointDetail)
}

// -------------------------------------------------------------------

// GiveUpOfficerRequest

// required int32 ssId = 1;
inline bool GiveUpOfficerRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GiveUpOfficerRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GiveUpOfficerRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GiveUpOfficerRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 GiveUpOfficerRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.GiveUpOfficerRequest.ssId)
  return ssid_;
}
inline void GiveUpOfficerRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.GiveUpOfficerRequest.ssId)
}

// -------------------------------------------------------------------

// UseDevelopItemRequest

// required int32 ssId = 1;
inline bool UseDevelopItemRequest::has_ssid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UseDevelopItemRequest::set_has_ssid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UseDevelopItemRequest::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UseDevelopItemRequest::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 UseDevelopItemRequest::ssid() const {
  // @@protoc_insertion_point(field_get:main.UseDevelopItemRequest.ssId)
  return ssid_;
}
inline void UseDevelopItemRequest::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.UseDevelopItemRequest.ssId)
}

// required int32 itemNum = 2;
inline bool UseDevelopItemRequest::has_itemnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UseDevelopItemRequest::set_has_itemnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UseDevelopItemRequest::clear_has_itemnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UseDevelopItemRequest::clear_itemnum() {
  itemnum_ = 0;
  clear_has_itemnum();
}
inline ::google::protobuf::int32 UseDevelopItemRequest::itemnum() const {
  // @@protoc_insertion_point(field_get:main.UseDevelopItemRequest.itemNum)
  return itemnum_;
}
inline void UseDevelopItemRequest::set_itemnum(::google::protobuf::int32 value) {
  set_has_itemnum();
  itemnum_ = value;
  // @@protoc_insertion_point(field_set:main.UseDevelopItemRequest.itemNum)
}

// -------------------------------------------------------------------

// UseDevelopItemResponse

// required int32 state = 1;
inline bool UseDevelopItemResponse::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UseDevelopItemResponse::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UseDevelopItemResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UseDevelopItemResponse::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 UseDevelopItemResponse::state() const {
  // @@protoc_insertion_point(field_get:main.UseDevelopItemResponse.state)
  return state_;
}
inline void UseDevelopItemResponse::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:main.UseDevelopItemResponse.state)
}

// required int32 ssId = 2;
inline bool UseDevelopItemResponse::has_ssid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UseDevelopItemResponse::set_has_ssid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UseDevelopItemResponse::clear_has_ssid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UseDevelopItemResponse::clear_ssid() {
  ssid_ = 0;
  clear_has_ssid();
}
inline ::google::protobuf::int32 UseDevelopItemResponse::ssid() const {
  // @@protoc_insertion_point(field_get:main.UseDevelopItemResponse.ssId)
  return ssid_;
}
inline void UseDevelopItemResponse::set_ssid(::google::protobuf::int32 value) {
  set_has_ssid();
  ssid_ = value;
  // @@protoc_insertion_point(field_set:main.UseDevelopItemResponse.ssId)
}

// optional .main.DevPointDetail pointDetail = 3;
inline bool UseDevelopItemResponse::has_pointdetail() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UseDevelopItemResponse::set_has_pointdetail() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UseDevelopItemResponse::clear_has_pointdetail() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UseDevelopItemResponse::clear_pointdetail() {
  if (pointdetail_ != NULL) pointdetail_->::main::DevPointDetail::Clear();
  clear_has_pointdetail();
}
inline const ::main::DevPointDetail& UseDevelopItemResponse::pointdetail() const {
  // @@protoc_insertion_point(field_get:main.UseDevelopItemResponse.pointDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return pointdetail_ != NULL ? *pointdetail_ : *default_instance().pointdetail_;
#else
  return pointdetail_ != NULL ? *pointdetail_ : *default_instance_->pointdetail_;
#endif
}
inline ::main::DevPointDetail* UseDevelopItemResponse::mutable_pointdetail() {
  set_has_pointdetail();
  if (pointdetail_ == NULL) pointdetail_ = new ::main::DevPointDetail;
  // @@protoc_insertion_point(field_mutable:main.UseDevelopItemResponse.pointDetail)
  return pointdetail_;
}
inline ::main::DevPointDetail* UseDevelopItemResponse::release_pointdetail() {
  clear_has_pointdetail();
  ::main::DevPointDetail* temp = pointdetail_;
  pointdetail_ = NULL;
  return temp;
}
inline void UseDevelopItemResponse::set_allocated_pointdetail(::main::DevPointDetail* pointdetail) {
  delete pointdetail_;
  pointdetail_ = pointdetail;
  if (pointdetail) {
    set_has_pointdetail();
  } else {
    clear_has_pointdetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.UseDevelopItemResponse.pointDetail)
}

// optional .main.DevOfficerDetail officerDetail = 4;
inline bool UseDevelopItemResponse::has_officerdetail() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UseDevelopItemResponse::set_has_officerdetail() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UseDevelopItemResponse::clear_has_officerdetail() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UseDevelopItemResponse::clear_officerdetail() {
  if (officerdetail_ != NULL) officerdetail_->::main::DevOfficerDetail::Clear();
  clear_has_officerdetail();
}
inline const ::main::DevOfficerDetail& UseDevelopItemResponse::officerdetail() const {
  // @@protoc_insertion_point(field_get:main.UseDevelopItemResponse.officerDetail)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return officerdetail_ != NULL ? *officerdetail_ : *default_instance().officerdetail_;
#else
  return officerdetail_ != NULL ? *officerdetail_ : *default_instance_->officerdetail_;
#endif
}
inline ::main::DevOfficerDetail* UseDevelopItemResponse::mutable_officerdetail() {
  set_has_officerdetail();
  if (officerdetail_ == NULL) officerdetail_ = new ::main::DevOfficerDetail;
  // @@protoc_insertion_point(field_mutable:main.UseDevelopItemResponse.officerDetail)
  return officerdetail_;
}
inline ::main::DevOfficerDetail* UseDevelopItemResponse::release_officerdetail() {
  clear_has_officerdetail();
  ::main::DevOfficerDetail* temp = officerdetail_;
  officerdetail_ = NULL;
  return temp;
}
inline void UseDevelopItemResponse::set_allocated_officerdetail(::main::DevOfficerDetail* officerdetail) {
  delete officerdetail_;
  officerdetail_ = officerdetail;
  if (officerdetail) {
    set_has_officerdetail();
  } else {
    clear_has_officerdetail();
  }
  // @@protoc_insertion_point(field_set_allocated:main.UseDevelopItemResponse.officerDetail)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace main

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Developing_2eproto__INCLUDED
