//
//  SGShowString.h
//  GameSanGuo
//
//  Created by dbq on 14-5-14.
//
//
#if 1

#ifndef GameSanGuo_SGShowString_h
#define GameSanGuo_SGShowString_h

#define XDGAME 1
#define G2GAME 2

#define GAMENAME G2GAME

#define str_Apple_official  "苹果官方"
#define str_User_name_already_exists  "用户名已存在"
#define str_Password_tips  "密码為6-16位英文和数字"
#define str_UserNmae_tips  "用户名為6-16位英文和数字"
#define str_Password_erro  "登入密码输入错误!"
#define str_NeedInput "请先登入游戏"
//GameSanGuo/Classes/conn/SGConnectTipBox.mm
#define str_Ok             "确定"
#define str_SkipUpdate      "继续游戏"

//网络出现问题的提示众。10.20
#define str_sgnet_common_problem "主公，网路发生问题，请稍后再试！" //通用错误
#define str_sgnet_network_not_available "主公，网路发生问题，请检查一下！" //手机没有网络
#define str_sgnet_kicked_by_other_device "主公，您的帐号已在其他设备登入！" //其他设备登入
#define str_sgnet_heart_beat_failure "主公，与伺服器连接已中断！请稍候再试！" //心跳检测失败
#define str_sgnet_cannot_reach_server "主公，联线中断，网路发生问题！" //连接不上服务器
#define str_sgnet_no_reply_on_request "主公，伺服器过於火爆，请重试！" //发消息没返回
#define str_sgnet_send_error "主公，伺服器繁忙，请稍后继续！" //发送失败
#define str_sgnet_receive_error "主公，伺服器繁忙，请稍后再试！" //接收失败
#define str_sgnet_send_break "主公，伺服器中断，请稍后继续！" //发送断链
#define str_sgnet_receive_break "主公，伺服器中断，请稍后再试！" //接收断链

#define str_Wuzhuangji_name "武装技名"

#define str_Format_Residual_damage  " 剩餘攻击力:%d "
#define str_Format_before_chain "连锁加攻击力前:%d"

#define str_Chain_attack  "连锁攻击"

#define str_Fusion_attack  "融合攻击"

#define str_Formation_attack "攻击阵形成"

//自动战斗中提示
#define str_AutoBattleTips  "当前处於自动战斗状态..."
#define str_AutoBattleTips1 "%d级以上开启自动战斗3倍速度"

///GameSanGuo/Classes/game/battle/battle_ui/SGBattleCallFriendBox.cpp"
#define str_Call_friend_battale "呼叫友军上场"
#define str_Select_friend_main_role "您可召唤的友军"
#define str_Format_get_wujiang_data_failure_id "获得武将资料失败id：%d"
#define str_Call_friend_tips  "呼叫友军上场需要消耗1个行动力，要让他立即上场作战吗？"
#define str_Can_call_friend  "友军槽已满，可以呼叫！"
#define str_No_Can_call_friend  "友军槽未满，暂不能呼叫。"

#define str_Is_fill_soldier  "是否要给对方补兵！"
//GameSanGuo/Classes/game/battle/battle_ui/SGBattleLeaderSkillBox.cpp
#define str_Mine_zhujiangji  "我方主将计"
#define str_Enemy_zhujiangji  "敌方主将计"
#define str_Zhujiangji   "主将计："
#define str_Format_ji   "Lv %d"
#define str_Format_lvl   "%d/%d"

#define str_Format_ji_New   "   %d"
#define str_No  "无"
#define str_LiangFeng "凉风有性秋月无边，费我思娇的情绪好比度日如年，可惜我不是玉树临风，风流瀟洒，但是我有凉风有性秋月无边，"
#define str_Now_can_start_zhujiangji  "现在可以发动主将计"
#define str_Format_some_round_can_start_zhujiangji  "%d回合后可以发动主将计"

#define str_Format_The_speed  "队伍速度 %d"

#define str_MergeItemoffTips   "是否无损合成更高级的武将经验丹？"
#define str_MergeItemsolTips   "是否无损合成更高级的兵魂卡？"
#define str_MergeItemTitle   "合成提示"

#define str_MergeItemMsg_offSuccess     "武将经验丹合成完毕"
#define str_MergeItemMsg_solSuccess     "兵魂卡合成完毕"

#define str_MergeItemMsg_Failed         "合成失败"
#define str_MergeItemMsg_offNone           "无需要合成的武将经验丹"
#define str_MergeItemMsg_solNone           "无需要合成的兵魂卡"

#define str_back_battale_tips1  "您在闯关模式中有未完成的战斗噢，是否继续作战？"
#define str_back_battale_tips2  "您当前有正在继续的守荆州战斗噢，是否继续？"
#define str_back_battale_tips3  "您在天梯晋级战中有未完成的战斗噢，是否继续作战？"
#define str_back_battale_tips4  "世界和平万岁！"

#define str_give_up_this_round_tips  "可以点击回合按钮，结束本回合"
#define str_Delete_sb_tips  "小提示：您可以按住指定人物，来删除它。"
#define str_Move_role_tips "小提示：您可以移动指定人物，到闪烁区域。（可以试试拖拽的方法哦~）"
#define str_Start_zhujiangji_tips "可以点击主将计按钮，发动主将计。"
#define str_Fill_soldier_tips "可以点击援军按钮，补充士兵。"
#define str_Formation_defense_wall "防御墙形成"

#define str_Match "匹配"
#define str_Test  "测试"
#define str_Action_plus "动作+"
#define str_Action_sub "动作-"

#define str_Skill_name  "技能名称"

#define str_NoSpace_for_thecall "场上没有空位，请确定有空位后再呼出"
#define str_lianji_str1 "累计伤害"

#define str_Try_three_samecolor_soldier "试著把三个同顏色的士兵组成一竖列或一横排。"
#define str_Only_move_last_soldier  "只能移动每列的最后一名士兵哦!"
#define str_this_is_first_get_four_ "这是您首次获得/#四格武将/#。"
#define str_Four_guide_tips "他在战场中/#组成阵列/#的方式与以往略有差别。"
#define str_Four_guide_tips_now_explain "现在為您讲解吗？"

#if GAMENAME  == XDGAME
#define str_Waiting "请稍等"
#define str_buy_requesting "正在為您请求购买。。。"
#define str_buy_fail_retry "你购买失败，请重新尝试购买～"
#define str_buy_close "Close（关闭）"
#define str_buy_succeed  "恭喜你购买成功啦"
#define str_buy_fail  "你购买失败啦"
#define str_buy_permit  "You can‘t purchase in app store（你没允许应用程序内购买）"
#define str_buy_back  "NSURLConnection  返回 error"
#elif GAMENAME  == G2GAME
#define str_Waiting "请稍等"
#define str_buy_requesting "正在為您请求购买。。。"
#define str_buy_fail_retry "您购买失败，请重新尝试购买～"
#define str_buy_close "Close（关闭）"
#define str_buy_succeed  "恭喜您购买成功啦"
#define str_buy_fail  "您购买失败啦"
#define str_buy_permit  "You can‘t purchase in app store（你没允许应用程序内购买）"
#define str_buy_back  "NSURLConnection  返回 error"
#else
#define str_Waiting "请稍等"
#define str_buy_requesting "正在為您请求购买。。。"
#define str_buy_fail_retry "你购买失败，请重新尝试购买～"
#define str_buy_close "Close（关闭）"
#define str_buy_succeed  "恭喜你购买成功啦"
#define str_buy_fail  "你购买失败啦"
#define str_buy_permit  "You can‘t purchase in app store（你没允许应用程序内购买）"
#define str_buy_back  "NSURLConnection  返回 error"
#endif

#define str_Get_ "领  取"
#define str_Ok_ "确 定"
#define str_Back_ "返  回"
#define str_TouDong_  "拖动"

#define str_Get_succeed "领取奖励成功"
#define str_Get_fail "领取失败"
#define str_Format_yuanbao_bei "元宝x%d倍"
#define str_Format_yuanbao "元宝x%d"
#define str_Format_yuanbao__ "元宝"
#define str_Format_tongMoney  "铜钱x%d"
#define str_Format_tongMoney__  "铜钱"
#define str_Format_pvpScore  "Pvp积分x%d"
#define str_Format_pvpScore__  "Pvp积分"
#define str_Format_jungong "军功x%d"
#define str_Format_junhun__ "军魂"
#define str_Format_junhun__1 "军魂 x%d"
#define str_Format_tili__ "体力"
#define str_Format_junliang__ "军粮"

#define str_Format_xunzhang__ "勋章"
#define str_Format_jungong__ "军功"
#define str_Format_smalll_laba  "小喇叭x%d"
#define str_Format_smalll_laba__  "小喇叭"
#define str_Format_liandian  "炼丹秘方x%d"
#define str_Format_liandian__  "炼丹秘方"
#define str_Tong_money "铜钱"
#define str_yuanbao "元宝"
#define str_jungong "军功"
#define str_Small_laba "小喇叭"
#define str_liandianmifang "炼丹秘方"
#define str_chinese_jade "勾玉"
#define str_arena_score "征服点"

#define str_Hit_goto "点击前往"

#define str_one_star_card3 "1星卡片 x 3张"
#define str_two_star_card3 "2星卡片 x 3张"
#define str_three_star_card3 "3星卡片 x 3张"
#define str_4_star_card3 "4星卡片 x 3张"
#define str_5_star_card3 "5星卡片 x 3张"
#define str_6_star_card3 "6星卡片 x 3张"
#define str_Format__star_card3 "%d星卡片 x %d张"

#define str_you_have_tong_money "您有铜钱 :"
#define str_cost_tong_money  "花费铜钱 : "
#define str_Class  "等级:"
#define str_Class_not_enough  "等级不足"
#define str_Format_Class "等级:%d/%d"
#define str_zhuansheng  "转生"
#define str_zhuansheng_  "转 生"
#define str_EquipAdvanced_start  "开始转生"
#define str_officer_zhuan "武将转生"
#define str_officer_zhuan_max "转生已达到上限"
#define str_adcance_tips "转生所需该武将碎片数量不足"
#define str_EquipAdvanced_failed  "转生失败"

//通用文本
#define str_back  "返回"

#define str_refresh "刷新"

#define str_Format_need_3_role "需要消耗三个/#%d/#星同名武将"

#define str_vipgiftinfo  "礼包详情"

#define str_Format_need_3_zhuangbei "需要消耗三个/#%d/#星级装备"
#define str_Format_need_3 "需要消耗三个/#%d星%s/#"
#define str_material_not_enough "材料不足"
#define str_attack "攻击:"
#define str_defense "防御:"
#define str_hp "血量:"
#define str_xuli "蓄力:"
#define str_speed "速度:"
#define str_tongyuli "统御力:"
#define str_Format_the_max "(最大%d)"
#define str_Format_class_d_d "等级:%d/%d"
#define str_Format_card_zhuansheng_tips "本次转生卡牌至少达到%d级"
#define str_zhuansheng_material_not_enough "转生材料不足，需要三张%d星级武将卡牌"
#define str_zhuansheng_material_not_enough1 "转生材料不足，需要三张%d星级装备卡牌"
#define str_zhuansheng_fail "转生失败"
#define str_advance_tips    "同名武将是武将进阶的必需材料，请主公记得保留！"

#define str_sort "排序"
#define str_max_3_role "最多可选择3位武将"
#define str_use_after_zhuangbei_auto_ "使用后,武将身上装备会自动卸下"
#define str_max_3_zhuangbei "最多可选择3个装备"
#define str_nohave_this_star_role "暂无可用武将"
#define str_tips_youmaybeto_vist "小提醒：或许去探访可以获得武将哦！"
#define str_nohave_this_star_zhuangbei "暂无可用装备"
#define str_tips_youmaybeto_vist1 "小提醒：或许去探访可以获得装备哦！"
#define str_no_as_material_role_ "不能将上阵武将作為材料"
#define str_no_as_material_zhuangbei  "不能将穿戴中的装备作為材料"
#define str_qianghua_tips1 "经验已满,不能继续强化"
#define str_one_card_need "至少选择一个素材"
#define str_is_zhengying1 "已在阵营1中"
#define str_is_zhengying2 "已在阵营2中"
#define str_is_zhengying3 "已在阵营3中"
#define str_have_zhuangbei "有装备在身"
#define str_zhuansheng_no_need "装备已是最强，无需转生。"
#define str_equipAdvance_top    "装备已达转生上限"

#define str_zhujiangji "主将计:"
#define str_beidongji  "被动技:"
#define str_Format_round_class "%s(%d回合) %d级"
#define str_Format_s_s_class   "%s %s级"
#define str_shangzheng_need_tongyuli "上阵需统御力:"
#define str_No_zhuangbei_shuxing   "装备属性: 无"

#define str_No_if_jingjie  "已达上限"
#define str_the_role_up_border  "此武将已达到转生上限,不能"
#define str_the_role_zhuansheng_no_class "转生此武将等级不足,不能"
#define str_no_material_zhuansheng "转生此武将材料不足,不能"
#define str_no_zhuangbei_class  "转生此装备等级不足,不能"
#define str_no_material_zhuansheng_zhuangbei "转生此装备材料不足,不能"
#define str_no_this_zhuangbei_star_up_border "此装备已达到星级上限,不能"
#define str_up_star "继续转生。"
#define str_lian_sheng_shuoming "连胜奖励说明"
#define str_Format_lian_sheng "连胜%d-%d场，"
#define str_CantAdvance_tips1  "无额外声望奖励"
#define str_CantAdvance_tips2 "额外声望奖励+%d/场"
#define str_CantAdvance_tips3 "提示：如果比赛失败，连胜奖励将"
#define str_CantAdvance_tips4 "降低至上一个级别的初始。"
#define str_CantAdvance_tips4_nomoney "您的铜钱不够了"
#define str_CantAdvance_tips5 "本次强化需要花费%d铜钱，"
#define str_CantAdvance_tips7 "您有%d铜钱，不足以支付，"
#define str_CantAdvance_tips8 "您的铜钱不够了"
#define str_CantAdvance_tips9 "可以用元宝兑换铜钱。"
#define str_CantAdvance_tips10 "本次转生需要花费%d铜钱，"
#define str_CantAdvance_tips11 "该武将是上场武将，"
#define str_CantAdvance_tips12 "不能卖出。"
#define str_CantAdvance_tips13 "您获得了 20000铜钱"
#define str_CantAdvance_tips14 "是否要将邀请人加為好友?"
#define str_CantAdvance_tips15 "再次体验新手引导流程(全程约"
#define str_CantAdvance_tips16 "5秒)，但不能重复获取相关环"
#define str_CantAdvance_tips17 "节中的奖励。"
#define str_CantAdvance_tips18 "元宝换铜钱"
#define str_CantAdvance_tips19  "本次操作需支付 %d元宝。您的"
#define str_CantAdvance_tips199 "帐户中有 %d元宝，不足以支付"
#define str_CantAdvance_tips20 "您不能购买这个礼包"
#define str_CantAdvance_tips21 "你要购买的礼包价格%d元宝"
#define str_CantAdvance_tips22 "购买此礼包需vip%d"
#define str_CantAdvance_tips23 "储值一定金额可以提升vip等级"
#define str_CantAdvance_tips24 "背包已满"
#define str_CantAdvance_tips25  "您的背包已满,无法容纳更多的卡牌"
#define str_CantAdvance_tips26 "当前空间 %d/%d"
#define str_CantAdvance_tips27 "请先强化一些卡片或扩展背包"
#define str_CantAdvance_tips28 "请留意"
#define str_CantAdvance_tips29 "您只有%d元宝了,不足以支付"
#define str_CantAdvance_tips30_1 "将此武将卡作為素材，其穿戴"
#define str_CantAdvance_tips30_2 "的装备会自动為您存入背包"
#define str_CantAdvance_tips31 "选择的卡牌中包含三星以上的"
#define str_CantAdvance_tips32 "卡牌,是否确定使用"
#define str_CantAdvance_tips31_1 "材料中有与目标卡同名的武将，"
#define str_CantAdvance_tips31_2 "确认要继续吗？"
#define str_CantAdvance_tips31_3 "(同名武将是武将进阶的必须材料）"
#define str_CantAdvance_tips33  "因為之前有武将进阶，佔用了更多的统御力"
#define str_CantAdvance_tips34 "目前统御力已超上限"
#define str_CantAdvance_tips35 "体力不足"
#define str_CantAdvance_tips35_1 "补充体力"
#define str_CantAdvance_tips35_2 "立即补充"
#define str_CantAdvance_tips35_3 "取消"
#define str_CantAdvance_tips35_4 "补充军粮"
#define str_CantAdvance_tips35_31 "储值"
#define str_CantAdvance_tips36 "这是今天第%d/%d次购买"
#define str_CantAdvance_tips37  "支付%d金可立即回满"
#define str_CantAdvance_tips38 "你现有%d金子"
#define str_CantAdvance_tips39 "金子不够，无法通过这种方式回復体力"
#define str_CantAdvance_tips40 "炼丹配方不足"
#define str_CantAdvance_tips41  "你拥有的炼丹秘方数量不足"
#define str_CantAdvance_tips42 "是否前往商城购买?"
#define str_CantAdvance_tips43 "给财神献上一定数量的金子,财神"
#define str_CantAdvance_tips44  "必定"
#define str_CantAdvance_tips45 "会返回给你更多数量的元宝哦!"
#define str_CantAdvance_tips46 "元宝不足"
#define str_CantAdvance_tips47 "本次拜财神需要%d元宝"
#define str_CantAdvance_tips48 "确认註册"
#define str_CantAdvance_tips49 "立即绑定"
#define str_CantAdvance_tips50 "请注意"
#define str_CantAdvance_tips51 "当前有未绑定的游客帐号，绑定"
#define str_CantAdvance_tips52 "该帐号前不能註册新帐号。"

#define str_CantAdvance_tips53 "您没有输入帐号,将以新的游客身份"
#define str_CantAdvance_tips54 "开始游戏!"
#define str_CantAdvance_tips55 "重要提示"
#define str_CantAdvance_tips56 "您当前使用的是“游客帐号,”只有"
#define str_CantAdvance_tips57 "升级為正式帐号后才能修改密码。"
#define str_CantAdvance_tips58 "体力不足"
#define str_CantAdvance_tips59 "您的体力不足以参加本场战斗，等级提升后可以提升体力上限。"
#define str_CantAdvance_tips60 "炼丹炉"
#define str_CantAdvance_tips61 "稟告主公!探马发现此地不远有"
#define str_CantAdvance_tips62 "一炼丹炉，是否要过去看看？"
#define str_CantAdvance_tips63 "军粮不足"
#define str_CantAdvance_tips64 "体力"
#define str_CantAdvance_tips65 "军粮"
#define str_CantAdvance_tips66 "这是今天第%s次恢復"
#define str_CantAdvance_tips67 "恢復全部%s需支付"
#define str_CantAdvance_tips67_2 "恢復%d点%s需支付"
#define str_CantAdvance_tips67_1    "恢復%d点体力需支付"
#define str_CantAdvance_tips68 "%d元宝"
#define str_CantAdvance_tips69 "您的帐户现有"
#define str_CantAdvance_tips70 "今日元宝回%s次数已用尽。"
#define str_CantAdvance_tips71 "提升VIP等级可获得更多购买次数。"
#define str_CantAdvance_tips72 "提升"
#define str_CantAdvance_tips73 "VIP等级"
#define str_CantAdvance_tips74 "可获得更多购买次数。"
#define str_CantAdvance_tips75 "获得奖励失败！！"
#define str_CantAdvance_tips76 "取胜秘笈"
#define str_CantAdvance_tips761 "如何变强"
#define str_CantAdvance_tips77 "    主公，强化武将、装备和士兵可以大幅提高部队战力。灵活搭配主将计和被动技，也会让战斗变得更為轻鬆。"
#define str_CantAdvance_tips78 "您之前未完成新手教学，点击确定后继续為您讲解。"
#define str_CantAdvance_tips79 "匹配失败"
#define str_CantAdvance_tips80 "匹配失败！对手已掉线，请重新配对。"
#define str_CantAdvance_tips81 "因对方断线，速配失败，请重新报名参加！"
#define str_CantAdvance_tips82 "统御力超出，请重新佈阵或替换装备！"
#define str_CantAdvance_tips84 "恭喜您获得%d铜钱,%d元宝!"
#define str_CantAdvance_tips85 "跳过关卡"
#define str_Cancel_ "取  消"
#define str_CantAdvance_tips86 "手动闯关"
#define str_CantAdvance_tips87 "守荆州战斗确认"
#define str_CantAdvance_tips88 "您之前以%d%%血量的最高纪录闯过本关，是否以此血量跳过本关？（如果您想突破自己的纪录，可以选择手动闯关噢。）"
#define str_CantAdvance_tips89 "守荆州战绩报告"
#define str_CantAdvance_tips90 "您本次守荆州总共消耗敌军血量%d，获得军魂%d。"
#define str_CantAdvance_tips91 "确定放弃"
#define str_CantAdvance_tips92 "继续战斗"
#define str_CantAdvance_tips93 "守荆州战斗确认"
#define str_CantAdvance_tips94 "结束的话，守荆州进度会消失哦！真的要结束吗？"
#define str_Cancel  "取消"
#define str_CantAdvance_tips95 "取回军魂消费确认"
#define str_CantAdvance_tips96 "您要花费%d元宝取回现在已经注入的军魂吗？"
#define str_CantAdvance_tips97 "去储值"
#define str_CantAdvance_tips98 "取回军魂元宝不足"
#define str_CantAdvance_tips99 "哎呀，您的元宝不足呢，无法取回哦~"
#define str_CantAdvance_tips100 "军魂换礼兑换奖励"
#define str_CantAdvance_tips101 "守荆州结算奖励"
#define str_CantAdvance_tips102 "您昨天守荆州的排名為第%d名，获得奖励%d元宝，请您再接再厉哦！"
#define str_CantAdvance_tips103 "BOSS 战结算奖励"
#define str_CantAdvance_tips104 "注入军魂数量确认"
#define str_CantAdvance_tips105 "您还没有注入军魂哦~"
#define str_Tips "提示"
#define str_CantAdvance_tips106 "今日挑战次数已达上限!!!!!!!"
#define str_CantAdvance_tips107 "VIP进入次数耗尽"
#define str_CantAdvance_tips108  "哎呀,VIP进入次数已经用完了哦～"
#define str_CantAdvance_tips109 "守荆州消费确认"
#define str_CantAdvance_tips110 "您确定花费30元宝换取进入守荆州的一次机会麼"
#define str_CantAdvance_tips111 "您是VIP用户，还有%d次机会哦"
#define str_CantAdvance_tips112 "删除问题确认"
#define str_CantAdvance_tips113 "确认该问题已经得到了满意的解答吗？删除后，该问题将不在显示！！"
#define str_CantAdvance_tips114 "由於本次战斗我方伤血较多，未达到三星胜利。强化武将和装备能快速提高部队战斗力，有助於主公完成三星胜利!"
#define str_CantAdvance_tips115 "前往强化"
#define str_CantAdvance_tips116 "知道了"
#define str_CantAdvance_tips117 "体力恢復成功"
#define str_CantAdvance_tips118 "体力恢復异常"
#define str_CantAdvance_tips119 "军粮补充成功"
#define str_CantAdvance_tips120 "军粮补充异常"
#define str_CantAdvance_tips121 "战斗提示"
#define str_CantAdvance_tips122 "天梯%d倍声望活动限时开啟，大量声望等你来拿，是否立即前往参加？"
#define str_CantAdvance_tips123 "讨伐魔王开始了,是否前往参战?"
#define str_CantAdvance_tips124 "铜钱不足"
#define str_CantAdvance_tips125 "主公，元宝不足，是否要立即前往储值？"
#define str_CantAdvance_tips126 "主公，铜钱不足，是否立即前往兑换？"
#define str_CantAdvance_tips127 "兑换"

#define str_CantAdvance_tips128 "兑换次数不足"
#define str_CantAdvance_tips129 "主公，今日元宝换铜钱次数已达上限，提高VIP等级每日可获得更多兑换次数哦!"
#define str_CantAdvance_tips1297 "主公，今日元宝换铜钱次数已达上限。"
#define str_CantAdvance_tips130 "vip等级不够"
#define str_CantAdvance_tips131 "元宝不足"
#define str_CantAdvance_tips132 "购买成功"
#define str_CantAdvance_tips133 "需要达到vip3才能购买"
#define str_CantAdvance_tips134 "元宝不足，无法购买"
#define str_CantAdvance_tips135 "恭喜主公成功购买了成长计划，等级越高，可领取的奖励越多哦~！"
#define str_CantAdvance_tips136 "您已经购买成长计划，不可重复购买~！"

#define str_CantAdvance_tips137 "购买挑战次数"
#define str_CantAdvance_tips138 "挑战次数不足,是否消耗%d元宝购买一次挑战次数?"
#define str_CantAdvance_tips139 "购买"

#define str_Consumable_tips1  "使用失败，%s!"
#define str_Consumable_tips2  "使用成功，%s!"
#define str_Consumable_tips3 "卖出失败"
#define str_Consumable_tips4 "卖出成功，获得金币%d!"
#define str_Consumable_tips5 "拥有的消耗品"
#define str_Consumable_str1 "页数:%d/%d"
#define str_Consumable_str2 "道具:%d"
#define str_Sale_  "卖 出"
#define str_Show_  "展 示"
#define str_Consumable_str3 "消耗品出售"
#define str_Consumable_str4 "请选择您出售的数量"
#define str_Consumable_str5  "预计获得"
#define str_Consumable_str6 "请选择卡牌数量!"
#define str_Consumable_str7 "确认卖出？"
#define str_Consumable_str8 "您确定要出售%d个%s, 获得游戏币%d吗？"

#define str_Material_str1   "拥有的材料"

#define str_use "使用"
#define str_shuliang "数量: %d"
#define str_need "需要 "
#define str_prop_not_enough "道具不足！"

#define str_treasure_box "宝箱"
#define str_The_key "钥匙"
#define str_gift_bag "礼包"
#define str_tiliyaoshui "体力药水"
#define str_junliangyaoshui "军粮药水"

#define str_ArrangeLayer_str1  "您没有可供上场的武将,可以到\n闯关模式或探访中获得."
#define str_ArrangeLayer_str2  "总统御力: "
#define str_ArrangeLayer_str3  "页数:%d/%d"
#define str_ArrangeLayer_str4  "已有同名武将上场!"
#define str_ArrangeLayer_str5  "已上阵同名武将!"
#define str_ArrangeLayer_str6  "统御力已超上限，无法上场这个武将!"
#define str_fail "失败"

#define str_huanren "换人"
#define str_xiachang "下场"
#define str_Set_to_main_role "设為主将"
#define str_qianghua  "强化"
#define str_qianghua_  "强 化"
#define str_autoqianghua  "自动强化"
#define str_huanzhuang "换装"
#define str_EmbattlBox_str1  "星级已达上限！"
#define str_EmbattlBox_str2 "武将 %s 下场抽根烟"
#define str_EmbattlBox_str3 "%s 被设置為主将,主将计生效"
#define str_EmbattlBox_str4  "这是上阵的唯一武将,不能下场"

#define str_EmbattleLayer_str1 "阵容总览"
#define str_EmbattleLayer_str2 "总速度:"
#define str_EmbattleLayer_str3 "总血量:"
#define str_EmbattleLayer_str4 "战斗力:"
#define str_EmbattleLayer_str5 "拖动武将头像至主将框,可将其设置為新的主将"
#define str_EmbattleLayer_str6 "阵容1"
#define str_EmbattleLayer_str7 "阵容2"
#define str_EmbattleLayer_str8 "阵容3"
#define str_EmbattleLayer_str9 "最强装备"
#define str_EmbattleLayer_str10 "查看士兵"
#define str_EmbattleLayer_str11 "当前阵容已啟用"
#define str_EmbattleLayer_str12 "要要主将计 Lv2"
#define str_EmbattleLayer_str13 "换阵容失败"
#define str_EmbattleLayer_str14 "%s 被设置為主将,主将计生效"
#define str_EmbattleLayer_str15 "无主将计"
#define str_EmbattleLayer_str16 "%s(回合数:%d) %d级"
#define str_EmbattleLayer_str17 "没有主将计"
#define str_EmbattleLayer_str18  "总血量+ %d\n"
#define str_EmbattleLayer_str19 "总速度+ %d\n"
#define str_EmbattleLayer_str20 "战斗力+ %d\n"
#define str_EmbattleLayer_str21 "统御力+ %d\n"

#define str_EmbattleLayer_str181  "总血量- %d\n"
#define str_EmbattleLayer_str191 "总速度- %d\n"
#define str_EmbattleLayer_str201 "战斗力- %d\n"
#define str_EmbattleLayer_str211 "统御力- %d\n"

#define str_EmbattleLayer_str22 "%s %d级(回合数:%d)"
#define str_EmbattleLayer_str23 "%d级可以解锁该卡槽"

#define str_select "选择"
#define str_SoiderListBox_str1 "请选择                  的兵种"
#define str_SoiderListBox_str2 "提示：点击头像可查看属性"
#define str_SoiderListBox_str3 "绿色部队"
#define str_SoiderListBox_str4 "蓝色部队"
#define str_SoiderListBox_str5 "红色部队"
#define str_SoiderListBox_str6 "设置失败"

#define str_EquipBox_str1 "装备%d件时"
#define str_EquipBox_str2 "上阵武将每人血量＋%d"

#define str_Equipslayer_str1 "套装属性: %s (1/%d)"
#define str_Equipslayer_str2 "套装属性: 无"
#define str_Equipslayer_str3 "经验已满,不能继续强化"
#define str_Equipslayer_str4 "取消保护失败"
#define str_Equipslayer_str5 "已解除保护状态"
#define str_Equipslayer_str6 "已将这张卡片设為保护状态"

#define str_Equipslayer_str7  "您没有此类装备，可以在闯关模式或探访中获得。"
#define str_sale "卖出"
#define str_Equipslayer_str8  "您总共有       件装备符合转生要求,点击查看"
#define str_Equipslayer_str9 "此分类下没有任何卡片"
#define str_Equipslayer_str10 "管理装备"
#define str_Equipslayer_str11 "缘分武将: "
#define str_Equipslayer_str12 "转生成功"
#define str_Equipslayer_str13 "铜钱购买"
#define str_Equipslayer_str14 "前往祭天"

#define str_ExpandLayer_str1 "元宝扩展背包的次数已用尽."
#define str_ExpandLayer_str2 "扩展背包"
#define str_ExpandLayer_str3 "卡牌:%d/%d"
#define str_ExpandLayer_str4 "增加"
#define str_ExpandLayer_str5 "个空间"
#define str_ExpandLayer_str6 "背包空间提升了! %d -》 %d"
#define str_ExpandLayer_str7 "背包扩展"

#define str_AutoEquipBox_str1 "要将/#所有上阵武将/#的装备自动调整為最强配置吗？（所有上阵武将的装备都可能变动）"
#define str_AutoEquipBox_str2 "要将/#当前武将/#的装备自动调整為最强配置吗?（不会变动其他武将身上的装备）"
#define str_AutoEquipBox_str3 "最强装备穿戴成功"

#define str_ChangeEquipEffectLayer_str1 "攻击力+"
#define str_ChangeEquipEffectLayer_str2 "攻击力+ %d\n"
#define str_ChangeEquipEffectLayer_str3 " 防御力+ %d\n"
#define str_ChangeEquipEffectLayer_str4 "血量+ %d\n"
#define str_ChangeEquipEffectLayer_str5 "速度+ %d"
#define str_ChangeEquipEffectLayer_str6 "攻击力- %d\n"
#define str_ChangeEquipEffectLayer_str7 "防御力- %d\n"
#define str_ChangeEquipEffectLayer_str8 "血量- %d\n"
#define str_ChangeEquipEffectLayer_str9 "速度- %d"
#define str_ChangeEquipEffectLayer_str10  "统御力减少了%d"
#define str_ChangeEquipEffectLayer_str11 "统御力+ %d"
#define str_ChangeEquipEffectLayer_str12 "血量减少了%d"
#define str_ChangeEquipEffectLayer_str13 "血量+ %d"
#define str_ChangeEquipEffectLayer_str14 "蓄力减少了%d"
#define str_ChangeEquipEffectLayer_str15 "蓄力+ %d"
#define str_ChangeEquipEffectLayer_str16 "速度减少了%d"
#define str_ChangeEquipEffectLayer_str17  "速度+ %d"
#define str_ChangeEquipEffectLayer_str18 "防御力减少了%d"
#define str_ChangeEquipEffectLayer_str19 "防御力+ %d"

#define str_SGExchangeEquipBox_str1 "品，要让他脱下来让给刚才选"
#define str_SGExchangeEquipBox_str2 "您的武将"
#define str_SGExchangeEquipBox_str3 "择的武将吗？"
#define str_SGExchangeEquipBox_str4 "正装备这个物"
#define str_SGExchangeEquipBox_str5 "%s 成功装备了 %s"

#define str_FateInfoItem_str1 "与"
#define str_FateInfoItem_str2 "同时上阵，可使本武将"
#define str_FateInfoItem_str3 "装备"
#define str_FateInfoItem_str4 "，可使本武将"
#define str_FateInfoItem_str5 "同时上阵"
#define str_FateInfoItem_str6  "名"
#define str_FateInfoItem_str7 "蜀国"
#define str_FateInfoItem_str8 "魏国"
#define str_FateInfoItem_str9 "吴国"
#define str_FateInfoItem_str10 "群雄"
#define str_FateInfoItem_str11 "天朝"
#define str_FateInfoItem_str12 "武将，可使本武将"
#define str_FateInfoItem_str13 "男性"
#define str_FateInfoItem_str14 "女性"
#define str_FateInfoItem_str15 "人妖"
#define str_FateInfoItem_str16 "传奇"
#define str_FateInfoItem_str17 "盖世无双"
#define str_FateInfoItem_str18 "勇冠三军"
#define str_FateInfoItem_str19 "神鬼莫测"
#define str_FateInfoItem_str20 "能攻善守"
#define str_FateInfoItem_str21 "运筹帷幄"
#define str_FateInfoItem_str22 "纳尼"
#define str_FateInfoItem_star1 "一星"
#define str_FateInfoItem_star2 "二星"
#define str_FateInfoItem_star3 "三星"
#define str_FateInfoItem_star4 "四星"
#define str_FateInfoItem_star5 "五星"
#define str_FateInfoItem_star6 "六星"
#define str_FateInfoItem_str23 "奇怪"
#define str_FateInfoItem_str24 "将缘描述出了点儿小问题哟~"

#define str_GeneralEquipBox_str1 "装备物品"
#define str_GeneralEquipBox_str2 "管理已装备的物品"
#define str_GeneralEquipBox_str3 "套装属性:"
#define str_GeneralEquipBox_str4 "%s将 %s 放入背包"

#define str_GeneralInfoLayer_str1 "%s  Lv%d"
#define str_huanren_ "换 人"
#define str_jiangyuan "将缘:"
#define str_deji "等级:"
#define str_jingyan "经验:"

#define str_mainjingyan "经验"
#define str_maintili  "体力"
#define str_mainjunliang "军粮"

#define str_GeneralInfoLayer_str2 "统御:"
#define str_GeneralInfoLayer_str3 "占格:"
#define str_GeneralInfoLayer_str4 "该武将等级已经到达上限"
#define str_GeneralInfoLayer_str5 "当前无装备"
#define str_GeneralInfoLayer_str6 "开始战斗"
#define str_GeneralInfoLayer_str7 "未知武将"
#define str_GeneralInfoLayer_str4_1 "等级已达上限,升级主公可继续提升武将等级!"
#define str_GeneralInfoLayer_str4_2 "等级已达上限,升级主公可继续提升士兵等级!"
#define str_GeneralInfoLayer_str10 "战力:"
#define str_GeneralInfoLayer_str11 "已达上限"

#define str_GeneralInfoLayer_str501 "绿色后解锁"
#define str_GeneralInfoLayer_str502 "绿色+1后解锁"
#define str_GeneralInfoLayer_str503 "绿色+2后解锁"
#define str_GeneralInfoLayer_str504 "绿色+3后解锁"
#define str_GeneralInfoLayer_str404 "等级经到达20级才开啟"

#define str_GeneralInfoEffect_str1 "武将当前没有主将计"
#define str_GeneralInfoEffect_str2  "无被动技"
#define str_GeneralInfoEffect_str3 "武将当前没有被动技"
#define str_GeneralInfoEffect_str4  "等级已达上限"
#define str_GeneralInfoEffect_str5 "等级已达上限，请提升武将星级"

#define str_GeneralsLayer_str1 "您总共有       位武将符合转生要求,点击查看"
#define str_generalsBagLayer_1 "拥有武将"
#define str_generalsBagLayer_2 "召唤武将"
#define str_generalsBagLayer_3 "当前拥有经验丹/石: %d"

#define str_NoExpStrengBox_str1 "这名武将得经验已满，继续强化\n也不会再获得经验。确认要这样\n做吗？"
#define str_NoExpStrengBox_str2 "备註:用相同技能的武将卡来强化,\n有一定机率提升原卡技能的等级"

#define str_SellBox_str1 "您确定要卖出该卡吗？"
#define str_SellBox_str2 "成功卖出卡片,铜钱%d"
#define str_jiage "价格:"

#define str_SkillInfoBox_str1 "提示: 相同主将计名称的武将相互强化,"
#define str_SkillInfoBox_str2 "可减少主将计发动回合。"
#define str_SkillInfoBox_str3 "提示: 使用与主卡相同技能的素材卡,"
#define str_SkillInfoBox_str4 "可以提高升级机率。"
#define str_SkillInfoBox_str5 "武将等级已满,不能继续强化，"
#define str_SkillInfoBox_str6 "提升主公等级可以提升武将等级"
#define str_SkillInfoBox_str7 "上限。"
#define str_SkillInfoBox_str8 "1.各个国家都有不同的3张士兵卡,士兵卡不能被卖出"
#define str_SkillInfoBox_str9 "2.士兵卡可通过吞噬兵魂卡提升等级,但不能进化升星"
#define str_SkillInfoBox_str10 "3.不同士兵卡拥有不同的技能,技能等级会随士兵卡等级提升而提升"
#define str_SkillInfoBox_str11 "绑定帐号"
#define str_SkillInfoBox_str12 "确认登入"
#define str_SkillInfoBox_str13 "        当前存在[游客帐号]信息,请先绑定帐号后再进行其他操作。"
#define str_SkillInfoBox_str14 "新建帐号"
#define str_SkillInfoBox_str15 "        当前存在[游客帐号]信息,要使用facebook帐号绑定该游客信息吗？"

#define str_StrengConfiirm_str1  "被动技强化"
#define str_StrengConfiirm_str2 "主将计强化"
#define str_StrengConfiirm_str3 "无武将计"

#define str_EquipPiecesLayer_str1 "拥有的装备碎片"
#define str_EquipPiecesLayer_str2 "当前通用碎片：%d"
#define str_EquipPiecesLayer_str3  "卡牌:%d"
#define str_EquipPiecesLayer_str4 "召唤成功！"
#define str_EquipPiecesLayer_str5 "召唤失败！"

#define str_PiecesCell_str1  "进度："
#define str_PiecesCell_str2 "可使用通用碎片：%d"
#define str_PiecesCell_str3 "哎呀，当前碎片数量不能召唤哦~"
#define str_PiecesCell_str4 "拥有数量 : %d"

#define str_Pieceslayer_str1 "拥有的武将碎片"
#define str_Pieceslayer_str2 "碎片:%d"
#define str_PiecesInfolayer_str1 "收集%d个该碎片可以合成武将，可以通过参加活动获得。"

#define str_PropInfolayer_str1 "道具不能升级或进阶"

#define str_Ding "顶"

#define str_SkillCardsInfoLayer_str1 "技能卡不能升级或进阶"
#define str_SkillCardsInfoLayer_str2 "提升武将星级,可以提高武将技能等级上限"

#define str_jieshao "介绍"
#define str_jieshao_colon "介绍："
#define str_Show "展示"
#define str_chengzhangji "成长技:"
#define str_wu_chengzhangji "无成长技"
#define str_tianfuji "天赋技:"
#define str_wu_tianfuji "无天赋技"
#define str_SoldiersInfoLayer "士兵当前等级没有成长技"
#define str_SoldiersInfoLayer_str1 "士兵当前等级没有天赋技"

#define str_Soldierslayer_str1 "士兵:%d"
#define str_Soldierslayer_str2 "以下是兵魂卡，用於给士兵提升经验等级。"

#define str_SoulCardInfoLayer_str1 "提供经验量: %d"
#define str_SoulCardInfoLayer_str2 "兵魂卡不能被强化和进阶，只能与士兵卡合成用"

#define str_StrengCox_str1 "拥有包含相同主将计的武将卡%d张"
#define str_chuji "初级"
#define str_zhongji "中级"
#define str_gaoji "高级"
#define str_StrengCox_str2 "%s %s  %d/%d  成功率%d%%"
#define str_StrengCox_str3 "%d增加经验%d"

#define str_StrengLayer_str1 "满级经验 : "
#define str_StrengLayer_str2 "预计经验 : "
#define str_zidong "自动"
#define str_tianja "添加"
#define str_StrengLayer_str3 "当前等级："
#define str_StrengLayer_str4 "技能升级机率:"
#define str_StrengLayer_str5 "升级概率: "
#define str_StrengLayer_str6 "(已选0/5)"
#define str_StrengLayer_str7 "没有可用的素材卡\n素材卡可以从限时副本中获得"
#define str_StrengLayer_str8 "(已选%d/5)"
#define str_StrengLayer_str9 "没有符合自动添加要求的卡牌"
#define str_StrengLayer_st10 "已选择卡牌"
#define str_StrengLayer_st11 "素材已经选满"
#define str_StrengLayer_st12 "增加经验%d"

#define str_StrengLayer_st101 "当前拥有经验丹/石:"
#define str_StrengLayer_st102 "当前拥有主将计卷轴:"
#define str_StrengLayer_st103 "当前拥有被动计卷轴:"
#define str_StrengLayer_st104 "当前拥有兵魂卡:"
#define str_StrengLayer_st105 "一键合併"

#define str_StrengLvIUpBox_str1 "卡牌升级"
#define str_StrengLvIUpBox_str2 "恭喜, %s升级了"

#define str_bag "背包"
#define str_wujiang "武将"
#define str_zhuangbei "装备"
#define str_soldiers "士兵"
#define str_suipian "碎片"
#define str_porp  "道具"
#define str_material_title    "材料"
#define str_jinengshucai "技能素材卡"
#define str_xiexia "卸下"

#define str_BassStuffLayer_str1 "强化合成"
#define str_BassStuffLayer_str2 "转生道具"
#define str_wuqi "武器"
#define str_kaijia "防具"
#define str_jiezhi "饰品"
#define str_zuoji "坐骑"

#define str_CardBatchSellLayer_str1 "卖出武将卡"
#define str_CardBatchSellLayer_str2 "卖出装备卡"
#define str_CardBatchSellLayer_str3 "卖出技能卡"
#define str_CardBatchSellLayer_str4 "已选中"
#define str_CardBatchSellLayer_str5 "卡牌 "
#define str_CardBatchSellLayer_str6 "背包容纳: "
#define str_CardBatchSellLayer_str7 "自动卖出"
#define str_CardBatchSellLayer_str8 "（自动卖出三星以下未锁定卡牌）"
#define str_CardBatchSellLayer_str9 "所有锁定或者在阵容中（含未啟用阵容）\n的武将均不可卖出!"
#define str_CardBatchSellLayer_str10 "所有锁定的装备均不可卖出!"
#define str_CardBatchSellLayer_str11 "没有技能卡片!"
#define str_CardBatchSellLayer_str12 "没有合适的卡牌!"
#define str_CardBatchSellLayer_str13  "请选择要卖出的卡牌"
#define str_CardBatchSellLayer_str14 "是否卖出以下卡牌？"
#define str_nowhave "现有"
#define str_CardBatchSellLayer_str15 "卖出卡牌失败"
#define str_CardBatchSellLayer_str16 "卖出卡牌成功"
#define str_CardBatchSellLayer_str17 "卖出武将成功，并卸下武将身上装备"
#define str_CardBatchSellLayer_str18 "没有合适的卡牌!"
#define str_CardBatchSellLayer_str19 "没有选择卡牌"
#define str_CardBatchSellLayer_str20 "请先选择自动卖出物品的星级!"
#define str_CardBatchSellLayer_str21 "获得"
#define str_CardBatchSellLayer_str22 "共卖出最大星级两星卡牌x%d张,最大星级三星卡牌x%d张"

#define str_CardItem_str1 "统御力不足"
#define str_CardItem_str101 "当前阵容"
#define str_CardItem_str102 "替补阵容"

#define str_CardItem_str2 "可转生"
#define str_CardItem_str3  "已上阵"
#define str_CardItem_str4  "血量: %d"
#define str_CardItem_str5  "攻击: %d"
#define str_CardItem_str6 "速度: %d"
#define str_CardItem_str7 "防御: %d"
#define str_CardItem_str8 "统御力: %d"
#define str_CardItem_str9  "%s已装备"
#define str_CardItem_str10 "附带经验:%d"
#define str_CardItem_str11 "已有同名上场武将"
#define str_CardItem_str12 "战力: %d"

#define str_SortBox_str1 "卡牌顺序"
#define str_SortBox_str2 "新获得"
#define str_SortBox_str3 "星级高"
#define str_SortBox_str4 "等级高"
#define str_SortBox_str5 "星级低"
#define str_SortBox_str6 "等级低"
#define str_SortBox_str7 "血量高"
#define str_SortBox_str8 "攻击高"
#define str_SortBox_str9 "速度快"
#define str_SortBox_str10 "防御高"
#define str_SortBox_str11 "统御高"
#define str_SortBox_str12 "同国家"
#define str_SortBox_str13 "同类型"

#define str_BMatchAlertBox_str1 "天梯赛速配成功"
#define str_BMatchAlertBox_str2 "您是否已做好战前準备？"
#define str_BMatchAlertBox_str3 "提示：选“稍后”，将停止速配"

#define str_BMatchEndBox_str1 "正在為您速配对手"
#define str_BMatchEndBox_str2 "昵称昵称"
#define str_BMatchEndBox_str3 "跨服排名：_ _"
#define str_BMatchEndBox_str4 "跨服排名：%d"
#define str_BMatchEndBox_str5 "参战：_ _次"
#define str_BMatchEndBox_str6 "参战：%d次"
#define str_BMatchEndBox_str7 "天梯声望：_ _"
#define str_BMatchEndBox_str8 "天梯声望：%d"
#define str_BMatchEndBox_str9 "胜率：_ _%"
#define str_BMatchEndBox_str10 "胜率：%.2f%%"
#define str_BMatchEndBox_str11 "对战窍门和最新活动公告的文字。"
#define str_BMatchEndBox_str12 "一二三四"
#define str_BMatchEndBox_str13 "天梯积分次日发放,天梯声望越高,积分越多。"
#define str_BMatchEndBox_str14 "排名：%d"
#define str_BMatchEndBox_str15 "参战：%d次"
#define str_BMatchEndBox_str16 "天梯声望：%d"
#define str_BMatchEndBox_str17 "胜率：%.2f%%"
#define str_BMatchEndBox_str18 "%d服:%s"
#define str_BMatchEndBox_str19 "天梯赛速配成功"
#define str_BMatchEndBox_str20 "已找到对手，"
#define str_BMatchEndBox_str21 "%d秒后"
#define str_BMatchEndBox_str22 "进入战场"
#define str_BMatchEndBox_str23 "排名：未知"

#define str_BMatchStartBox_str1 "速配中"
#define str_BMatchStartBox_str2 "您可以选择"
#define str_BMatchStartBox_str3 "隐藏菜单"
#define str_BMatchStartBox_str4 "，找到对手后，"
#define str_BMatchStartBox_str5  "系统会自动為您弹出提示。"
#define str_BMatchStartBox_str6 "提示：速配过程中请不要退出游戏"

#define str_BattleMainLayer_str1 "排行榜"
#define str_BattleMainLayer_str2 "上届榜单"
#define str_BattleMainLayer_str3 "赛季奖励"
#define str_BattleMainLayer_str4 "积分换奖"
#define str_BattleMainLayer_str5 "每日奖励"
//#define str_BattleMainLayer_str6 "关於对战模式"
#define str_BattleMainLayer_str6 "天梯对战规则"
#define str_BattleMainLayer_str7 "第%d届 天梯赛"
#define str_BattleMainLayer_str8 "赛季截止："
#define str_BattleMainLayer_str9 "当前胜率："
#define str_BattleMainLayer_str10 "最大连胜："
#define str_BattleMainLayer_str11 "天梯积分："
#define str_BattleMainLayer_str12 "天梯声望："
#define str_BattleMainLayer_str13 "本服排名："
#define str_BattleMainLayer_str14 "当前军衔："
#define str_BattleMainLayer_str15 "连胜奖励："
#define str_BattleMainLayer_str16 "正常在等待中。。。  请稍等！"
#define str_BattleMainLayer_str17 "无排名"
#define str_BattleMainLayer_str18 "暂无上届榜单"
#define str_BattleMainLayer_str19 "当前军粮："

#define str_GeneralBox_str1 "要将援军加為好友吗"
#define str_GeneralBox_str2 "援军/#%s/#不是您的好友，要添加他為好友吗？"
#define str_GeneralBox_str3 "加好友"
#define str_GeneralBox_str4  "稟告主公！探马发现此地不远有"
#define str_GeneralBox_str5 "一炼丹炉，您可以去领奖中看看"
#define str_GeneralBox_str6 "好友上限："
#define str_GeneralBox_str7 "武将空位："
#define str_GeneralBox_str8 "体力上限："
#define str_GeneralBox_str9 "统御力上限："
#define str_GeneralBox_str10 "升级获得体力      点"

#define str_BattleHelpLayer_str1 "您可以选择「隐藏功能表」，先去做其他事情，找到对手后，系统会自动為您弹出提示。您可以选择「隐藏功能表」，先去做其他事情，找到对手后，系统会自动為您弹出提示。您可以选择“隐藏功能表”，先去做其他事情，找到对手后，系统会自动為您弹出提示。"
#define str_BattleHelpLayer_str2 "铜钱25万，军功*1200，/#四星燎原火*1/#，四个国家的武将经验丹（中）各3个，/#二星燎原火*1/#"
#define str_BattleHelpLayer_str3 "铜钱25万，/#四星燎原火*1/#，四个国家的武将经验丹（中）各3个"

#define str_BattleRankCell_str1 "天梯等级：%d"

#define str_BattleRankLayer_str1 "天梯晋级战"
#define str_BattleRankLayer_str2 "此排名暂无数据"
#define str_BattleRankLayer_str3 "天梯等级："
#define str_BattleRankLayer_str4 "拥有积分："
#define str_BattleRankLayer_str5 "您的军衔："

#define str_BattleScorelayer_str1  "天梯商城"
#define str_BattleScorelayer_str2 "您的天梯声望: "
#define str_BattleScorelayer_str3 "拥有积分: "
#define str_hot_sale "热卖"
#define str_kapei "卡牌"
#define str_juanzhou "卷轴"
#define str_cailiao "材料"
#define str_other "其他"
#define str_BattleScorelayer_str4 "天梯声望不够"
#define str_BattleScorelayer_str5 "天梯积分不够"
#define str_BattleScorelayer_str6   "兑换次数不够"
#define str_BattleScorelayer_str7 "您获得了：%sX%d"

#define str_CreditCardBox_str1 "您目前拥有的积分 : %d"
#define str_CreditCardBox_str2 "兑换此道具需花费 : %d 积分"
#define str_CreditCardBox_str3 "确定兑换此道具？"
#define str_haha "哈哈"

#define str_CreditCardCellstr1  "道具名"
#define str_CreditCardCellstr2  "数量"
#define str_CreditCardCellstr3  "天梯等级"
#define str_CreditCardCellstr4  "所需积分"
#define str_CreditCardCellstr5  "可替换次数"
#define str_CreditCardCellstr6 "需%d积分"
#define str_CreditCardCellstr7  "原%d积分"
#define str_CreditCardCellstr8  "现%d积分"
#define str_CreditCardCellstr9  "天梯声望%d以上可换"
#define str_CreditCardCellstr10  "已兑换%d/%d次"
#define str_CreditCardCellstr11 "数量:%d"

#define str_BattleFieldItemstr1 "战场胜利次数不够 未开啟"

#define str_BattleFieldLayer_str1  "天梯晋级战（新手）"
#define str_BattleFieldLayer_str2   "天梯晋级战（老手）"
#define str_BattleFieldLayer_str3  "打够5场就可以去高手房了，总在菜鸟房呆著自己也会变成菜鸟的！"
#define str_BattleFieldLayer_str4  "面临新的挑战吧，这裡不是菜鸟乐园，拿出你真正的实力面对每一个新对手吧!"
#define str_BattleFieldLayer_str5  "需要在新手模式中完成%d场才能进入！"

#define str_BossBattleDetailLayer_str1 "已获得属性:  "
#define str_BossBattleDetailLayer_str2  "攻击: "
#define str_BossBattleDetailLayer_str3  "爆击倍数: "
#define str_BossBattleDetailLayer_str4  "爆击率: "
#define str_BossBattleDetailLayer_str5  "主公已攻击"
#define str_BossBattleDetailLayer_str6  "次，共造成伤害"
#define str_BossBattleDetailLayer_str7  "退  出"
#define str_BossBattleDetailLayer_str8   "起死回生"
#define str_BossBattleDetailLayer_str9  "涅槃重生"
#define str_BossBattleDetailLayer_str10  "浴火重生"
#define str_BossBattleDetailLayer_str11   "王者归来"
#define str_BossBattleDetailLayer_str12  "復活:  "
#define str_BossBattleDetailLayer_str13  "未復活，不能开始战斗"
#define str_BossBattleDetailLayer_str14  "购买成功!"
#define str_BossBattleDetailLayer_str15  "购买失败!"
#define str_BossBattleDetailLayer_str16  "当前无需使用復活功能"
#define str_BossBattleDetailLayer_str1601  "达到vip%d时可使用该功能"
#define str_BossBattleDetailLayer_str17  "元宝不足以支付!"
#define str_BossBattleDetailLayer_str18  "爆击率已达百分之百!"
#define str_BossBattleDetailLayer_str19  "讨魔战介绍"
#define str_BossBattleDetailLayer_str20  "1.起死回生：復活等待时间变為0立即復活"
#define str_BossBattleDetailLayer_str21  "2.涅槃重生：立即復活并使自身攻击力增加5%"
#define str_BossBattleDetailLayer_str22  "3.浴火重生：立即復活并使爆击伤害倍数增加10%"
#define str_BossBattleDetailLayer_str23  "4.王者归来：立即復活并使自身爆击率增加5%"

#define str_BossBattleJoinInLayer_str1 "前三名：伤心陌生人，伤心陌生人，伤心陌生人"
#define str_BossBattleJoinInLayer_str2  "伤心陌生人在9分鐘将boss击杀"
#define str_BossBattleJoinInLayer_str3  "所有上阵武将将会合体\n \t                              共同对Boss发动强力一击"
#define str_BossBattleJoinInLayer_str4  "每天21：00开战"
#define str_BossBattleJoinInLayer_str5  "讨伐魔王活动已开啟, 请主公前去讨伐!"
#define str_BossBattleJoinInLayer_str6 "战斗已经开始%d分鐘了"

#define str_jump_out "跳过"

#define str_BossBattleRankListLayer_str1 "讨魔活动伤害排名"
#define str_BossBattleRankListLayer_str2  "boss在%d分鐘内被%s亲手击杀。伤害量 %d。伤害排名前10的主公们获得了击杀礼包。"
#define str_BossBattleRankListLayer_str3  "伤害排名前10的主公们获得了击杀礼包。"
#define str_BossBattleRankListLayer_str4  "我的阵型"
#define str_BossBattleRankListLayer_str5  "等级: %d"
#define str_BossBattleRankListLayer_str6  "伤害:"
#define str_BossBattleRankListLayer_str7 "暂无"

#define str_BossRankItem_str1 "伤害：%d"
#define str_BossRankItem_str2 "详细阵型"
#define str_BossRankItem_str3 "等级 %d"

#define str_BossRewardLayer_str1  "讨魔奖励"
#define str_BossRewardLayer_str2  "本次攻击对魔王吕布造成了%d点得伤害"
#define str_BossRewardLayer_str3  "获得铜钱："
#define str_BossRewardLayer_str4  "获得勋章："

#define str_JunxianLayer_str1  "军衔说明"
#define str_JunxianLayer_str2  "我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我"
#define str_JunxianLayer_str3   "获得条件:"
#define str_JunxianLayer_str4  "军衔加成:"

#define str_PvpMainCell_str1 "未开放"
#define str_PvpMainCell_str2  "3倍声望活动:%s~%s"
#define str_PvpMainCell_str3  "稍后开放，敬请期待"
#define str_PvpMainCell_str4  "阳平关夺宝战"
#define str_PvpMainCell_str5  "皇城擂臺"

#define str_PvpMainLayer_str1  "对战(PVP)"
#define str_PvpMainLayer_str2  "该功能暂未开放"

#define str_SeasonListLayer_str1  "赛季奖励"
#define str_SeasonListLayer_str2  "不能领取该奖励"
#define str_SeasonListLayer_str3  "该奖励已经领取"
#define str_SeasonListLayer_str4  "领取奖励失败"
#define str_SeasonListLayer_str5  "第%d名奖励礼包"
#define str_SeasonListLayer_str6  "一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十"
#define str_SeasonListLayer_str7  "查看"
#define str_SeasonListLayer_str8  "每日奖励"

#define str_pvpLastListLayer_str1  "第%d届 天梯赛榜单"
#define str_pvpLastListLayer_str2  "一二三四"
#define str_pvpLastListLayer_str3  "本服排名:"
#define str_pvpLastListLayer_str4  "详细阵型"
#define str_pvpLastListLayer_str5  "%d服-%s"
#define str_pvpLastListLayer_str6  "战无不胜"

#define str_JingZhouProcessLayer_str1  "开始守城"
#define str_JingZhouProcessLayer_str2  "从头开始守城，一切皆有可能。"
#define str_JingZhouProcessLayer_str3  "您将无损从第/#%d/#波开始守城, 同时获得前/#%d/#波军魂/#%d/#及所有其他奖励。"
#define str_JingZhouProcessLayer_str4  "从头开始守城。一切皆有可能。"
#define str_JingZhouProcessLayer_str5  "您将无损从第/#%d/#波开始守城, 同时获得前/#%d/#波军魂/#%d/#及所有其他奖励。"

#define str_ShouJingZhou_str1  "守荆州"
#define str_ShouJingZhou_str2  "未开始"
#define str_ShouJingZhou_str3  "第 %d 波"
#define str_ShouJingZhou_str4  "第 %d 名"
#define str_ShouJingZhou_str5 "未上榜"
#define str_ShouJingZhou_str6  "%llu伤害"
#define str_ShouJingZhou_str7  "哎呀，主公等级不够呀！达到%d级才能进入哦~"
#define str_ShouJingZhou_str8  "今日挑战次数已达上限"
#define str_ShouJingZhou_str9 "关於守荆州"
#define str_ShouJingZhou_str10 "哎呀，排行榜暂时木有人儿噢~"
#define str_ShouJingZhou_str11  "哎呦，外星人来了，进入失败"
#define str_ShouJingZhou_str12  "购买成功"
#define str_ShouJingZhou_str13  "您的元宝不足以支付!"
#define str_ShouJingZhou_str14   "本关卡挑战次数、今日重置次数都已用尽，请明天再来。"
#define str_ShouJingZhou_str15 "抱歉，您暂时不能进入守荆州噢~"

#define str_ShouJingZhou_str16 "从第/#%d/#波开始"

#define str_ShouJingZhouRank_str1  "今日守荆州排行"
#define str_ShouJingZhouRank_str2  "守荆州排名前 %d 将获得丰厚奖励"
#define str_ShouJingZhouRank_str3  "我的排名："
#define str_ShouJingZhouRank_str4  "发奖倒计时:  "
#define str_ShouJingZhouRank_str5  "今日参战: "
#define str_ShouJingZhouRank_str6  "今日守荆州排行"

#define str_ShowJingZhouRankCell_str1 "呵呵"
#define str_ShowJingZhouRankCell_str2 "最高波数：第%d波"
#define str_ShowJingZhouRankCell_str3 "造成伤害：%d"

#define str_SoulExchangeLayer_str1 "军魂换礼"
#define str_SoulExchangeLayer_str2 "按住「注入」可以向宝箱中注入军魂。"
#define str_SoulExchangeLayer_str3  "军魂蓄满后，宝箱就会打开，可以获得各种装备哦！"
#define str_SoulExchangeLayer_str4 "箱子越好，获得的装备也会越好噢。"
#define str_SoulExchangeLayer_str5 "哎呀，军魂注入出了点儿小问题，请再试试吧。"
#define str_SoulExchangeLayer_str6  "成功取回已注入的军魂噢~"
#define str_SoulExchangeLayer_str7  "取回军魂出错啦~"
#define str_SoulExchangeLayer_str8 "哎呀，领奖好像出了点儿小问题，请再试试吧。"

#define str_SoulExchangeLayer_str9 "恭喜您获得"
#define str_SoulExchangeLayer_str10 "领取成功"

#define str_BattlePreLayer_str1 "天梯晋级赛"
#define str_BattlePreLayer_str2 "读取中，请稍后"
#define str_BattlePreLayer_str3 "现在為您补满血量，教学完成后的关卡可是没有这个待遇的哦~战斗的要点是，竖排组成攻击阵列，横排组成防御阵列。"
#define str_BattlePreLayer_str4  "你可以花费%d元宝满血復活!是否復活。"

#define str_BattleRoundPromptLayer_str1  "结束回合"
#define str_BattleRoundPromptLayer_str2 "你还可以行动%d次，要立即结束回合吗？"
#define str_BattleRoundPromptLayer_str3 "提示：每放弃2行动力，可降低1个主将计发动回合"

#define str_TTMainLayer_str1 "测试"
#define str_TTMainLayer_str2 "张三在求良将中获得4星极品武将张辽"
#define str_TTMainLayer_str3  "张三：有组队打副本的没有，加我"
#define str_TTMainLayer_str4 "冷却 9:55"
#define str_TTMainLayer_str5  "註册一个新帐号，并将当前存档绑定。"
#define str_TTMainLayer_str6  "可以避免因為更换手机或程式出错而造成的存档丢失。"

#define str_TTMainLayer_str7 "您当前的帐号為正式帐号,"
#define str_TTMainLayer_str8 "安全係数提高！如以后更换手机,"
#define str_TTMainLayer_str9 "也可通过此帐号密码登入。"

/*
 新开始游戏：台词
 
 三国，是一段歷史
 更是一段传奇
 今天
 这段传奇
 将由你来重新谱写……
 
 */

#define str_CGMovieLayer_str1 "三国，是一段歷史"
#define str_CGMovieLayer_str2 "更是一段传奇"
#define str_CGMovieLayer_str3   "今天"
#define str_CGMovieLayer_str4  "这段传奇"
#define str_CGMovieLayer_str5   "将由你来重新谱写……"
#define str_CGMovieLayer_str6  " "
#define str_CGMovieLayer_str7   " "
#define str_CGMovieLayer_str8  "请输入啟动码"
#define str_CGMovieLayer_str9 "CDKKEY无效"

#if GAMENAME == XDGAME
#define str_CGMovieLayer_str10 "这是您首次来到中国好三国，请选择一个国家开始\n游戏。"
#elif GAMENAME == G2GAME
#define str_CGMovieLayer_str10 "这是您首次来到三国英雄联盟，请选择一个国家开始\n游戏。"
#else
#define str_CGMovieLayer_str10 "这是您首次来到中国好三国，请选择一个国家开始\n游戏。"
#endif

#define str_NikeNameBox_str1  "暱称需2-7个字，可以是中文、\n字母、数字或者符号。"
#define str_NikeNameBox_str2  "字数不符合要求"
#define str_NikeNameBox_str3  "不能含有表情符号"
#define str_NikeNameBox_str4  "字数不符合要求"
#define str_NikeNameBox_str5  "随机名字错误\n"

#define str_NikeNameBox_str6   "开始征途"
#define str_NikeNameBox_str7   "重选国家"

#define str_RegisterLayer_login "已有帐号登入"
#define str_RegisterLayer_login_old "使用老帐号登入"
#define str_RegisterLayer_login_old_verify "当前有未绑定的游客账号，使用老账号登陆会丢失游客数据，是否确认使用老账号登陆？"

#define str_RegisterBox_str1 "6-16位英文和数字"
#define str_RegisterBox_str2 "再输入一遍密码"
#define str_RegisterBox_str3 "註册帐号"
#define str_RegisterBox_str4 "绑定帐号"
#define str_RegisterBox_str5 "註册一个新帐号,并将当前存档绑定."
#define str_RegisterBox_str6 "可以避免因更换手机或游戏程式出"
#define str_RegisterBox_str7 "错而造成的存档丢失."
#define str_RegisterBox_str8  "密码必须為4-16位数字或字母"
#define str_RegisterBox_str9  "两次密码不一致"
#define str_RegisterBox_str10  "已经有人使用了这个帐号"
#define str_RegisterBox_str11  "帐号绑定成功"
#define str_RegisterBox_str12  "用户名不存在"
#define str_RegisterBox_str13  "旧密码错误"
#define str_RegisterBox_str1301  "原密码错误"
#define str_RegisterBox_str14 "不能重复绑定帐号"
#define str_RegisterBox_str15  "註册接收资料失败"
#define str_RegisterBox_str16 "用户名"
#define str_RegisterBox_str17 "密码"
#define str_RegisterBox_str18 "确认密码"
#define str_RegisterBox_str19 "创建新帐号"
#define str_RegisterBox_str20 "绑定帐号"
#define str_RegisterBox_str21 "本操作将绑定当前游客帐号"
#define str_RegisterBox_str22 "请输入正确的用户名做為帐号"
#define str_RegisterBox_str23 "註册成功,您可以开始游戏了"
#define str_RegisterBox_str24 "这个帐号已经绑定过其它角色了，不能重复绑定！"

#define str_RegisterSuccess_str1 "下次游戏时，选择"
#define str_RegisterSuccess_str2 "可免输入帐号密码直接进入游戏哦~"

#define str_ChangePassWordLayer_str1 "密码不能為空"
#define str_ChangePassWordLayer_str2 "新密码必须為4-16位数字或字母"
#define str_ChangePassWordLayer_str3 "密码格式不对"
#define str_ChangePassWordLayer_str4 "新密码不一致"
#define str_ChangePassWordLayer_str5 "新密码与旧密码相同"
#define str_ChangePassWordLayer_str6 "修改密码"
#define str_ChangePassWordLayer_str7 "旧密码"
#define str_ChangePassWordLayer_str8  "新密码"
#define str_ChangePassWordLayer_str9 "确认新密码"
#define str_ChangePassWordLayer_str10 "帐号错误"
#define str_ChangePassWordLayer_str11 "新密码格式错误"
#define str_ChangePassWordLayer_str12 "新旧密码相同"
#define str_ChangePassWordLayer_str13 "密码修改成功"

#define str_ModificationPassword_str1 "帐号"
#define str_ModificationPassword_str2 "旧密码"
#define str_ModificationPassword_str3 "再输入一次新密码"
#define str_ModificationPassword_str4 "旧密码不正确"
#define str_ModificationPassword_str5 "密码必须為4-16位数字或字母"

#define str_ServerItem_str1 "你在哪裡呢"
#define str_ServerItem_str2 "未创建角色"
#define str_ServerItem_str3 "你在哪裡呢"
#define str_ServerItem_str4 "(维护)"
#define str_ServerItem_str5 "(通畅)"
#define str_ServerItem_str6 "(火爆)"
#define str_ServerItem_str7 "(新区)"
#define str_ServerItem_str8 "蜀国  %s  %s级"
#define str_ServerItem_str9 "魏国  %s  %s级"
#define str_ServerItem_str10  "吴国  %s  %s级"

#define str_ServerItem_str11 "可选的伺服器"
#define str_ServerItem_str12 "登入游戏"
#define str_ServerItem_str13 "6-16位英文和数字"
#define str_ServerItem_str14 "请输入帐号和密码"
#define str_ServerItem_str15 "帐号不存在"
#define str_ServerItem_str16 "密码错误"
#define str_ServerItem_str17 "点击登入"
#define str_ServerItem_str18 "登入"

#define str_ServerListNewServerBox_str1 "您之前没有玩过这个服，"
#define str_ServerListNewServerBox_str2 "要在   "
#define str_ServerListNewServerBox_str3 " 新建一个角色吗？"
#define str_ServerListNewServerBox_str4 "新建角色"

#define str_WdelcomeLayer_str1 "提示 : 点击帐号和伺服器可以进行更换"
#define str_WdelcomeLayer_str2 "提示 : 点击伺服器可以进行更换"
#define str_WdelcomeLayer_str3 "切换帐号"
#define str_WdelcomeLayer_str4 "游客"
#define str_WdelcomeLayer_str5 "註册登入"

#define str_ChatMessageCenter1 "聊天字数已达上限!"
#define str_ChatMessageCenter2 "两次发言之间需要休息15秒!"

#define str_ForbidChat_str1  "您已没有小喇叭用於发言，是"
#define str_ForbidChat_str2  "否花100元宝买10个？"
#define str_ForbidChat_str3  "您的帐户有%d元宝"
#define str_ForbidChat_str4  "不足以支付"

#define str_ChatInputBox_str1 "发言内容"
#define str_ChatInputBox_str2 "输入聊天文字"
#define str_ChatInputBox_str3 "输入字数过多"
#define str_ChatInputBox_str4 "发言内容不能為空"
#define str_ChatInputBox_str5 "还可以输入%d个字!"
#define str_ChatInputBox_str6 "输入字数太多了哦"
#define str_ChatInputBox_str7 "已经达到字数上限"

#define str_Chat_str1 "禁言"
#define str_Chat_str2 "内容"
#define str_Chat_str3 "%s (左将军)"
#define str_Chat_str4 "你"
#define str_Chat_str5 "等级达到5级才能发言"

#define str_DynamicCirculateLayer_str1 "公告：运气不错！"
#define str_DynamicCirculateLayer_str2 "探访到了"
#define str_DynamicCirculateLayer_str3 "品质武将"
#define str_DynamicCirculateLayer_str4 "品质装备"
#define str_DynamicCirculateLayer_str5 "公告："
#define str_DynamicCirculateLayer_str6 "的武将"
#define str_DynamicCirculateLayer_str7 "的装备"
#define str_DynamicCirculateLayer_str8 "成功进阶到"
#define str_DynamicCirculateLayer_str9 "品质"
#define str_DynamicCirculateLayer_str10 "成功击败"
#define str_DynamicCirculateLayer_str11 "，获得了珍贵的武将卡"
#define str_DynamicCirculateLayer_str12 "解锁成就"
#define str_DynamicCirculateLayer_str13 "，获得"
#define str_DynamicCirculateLayer_str14 "成就点"
#define str_DynamicCirculateLayer_str15 "绿色"
#define str_DynamicCirculateLayer_str16 "蓝色"
#define str_DynamicCirculateLayer_str17 "紫色"
#define str_DynamicCirculateLayer_str18 "橙色"
#define str_DynamicCirculateLayer_str19 "红色"
#define str_DynamicCirculateLayer_str20 "普通色"

#define str_LandingReward_str1 "已连续登入 %d 天, 可抽奖 %d/%d 次"
#define str_LandingReward_str2 "天时"
//#define str_LandingReward_str3 "可额外获得"
#define str_LandingReward_str3 "点击卡牌选择你的奖励吧！"
#define str_LandingReward_str4 "连续登入"
#define str_LandingReward_str5 "%d 铜钱"
#define str_LandingReward_str6 "小喇叭x%d"
#define str_LandingReward_str7 "炼丹秘方x%d"
#define str_LandingReward_str8 "连续登入中断后，翻牌数量会减少哦。"

#define str_AllCardsLayer_str1  "卡牌图鉴"
#define str_AllCardsLayer_str2 "武将卡"
#define str_AllCardsLayer_str3 "武将卡"
#define str_AllCardsLayer_str4 "武将卡"
#define str_AllCardsLayer_str5 "武将卡"
#define str_AllCardsLayer_str6 "装备卡"

#define str_CardsLayer_str1  "武将卡图鉴"
#define str_CardsLayer_str2  "武将卡图鉴"
#define str_CardsLayer_str3 "武将卡图鉴"
#define str_CardsLayer_str4 "武将卡图鉴"
#define str_CardsLayer_str5  "装备卡图鉴"
#define str_CardsLayer_str6 "投诉意见"
#define str_CardsLayer_str7 "您可以对此问题做更多的描述哦！"
#define str_CardsLayer_str8 "GM%d号"

#define str_ChatWithGMInputBox_str1 "输入留言文字"
#define str_ChatWithGMInputBox_str2 "发言频率过快，请稍后再试"
#define str_ChatWithGMInputBox_str3 "留言字数不符合要求"
#define str_ChatWithGMInputBox_str4 "发送成功"
#define str_ChatWithGMInputBox_str5 "发送失败"

#define str_Delete "删除"

#define str_ComplainLayer_str1  "现在还没有任何问题哦"
#define str_ComplainLayer_str2  "投诉建议"
#define str_ComplainLayer_str3 "新建问题"
#define str_ComplainLayer_str4 "删除成功"
#define str_ComplainLayer_str5 "删除失败"
#define str_ComplainLayer_str6  "帮助手册"

#define str_HelpLayer_str1 "各种设置"
#define str_HelpLayer_str2 "帮助手册"
#define str_HelpLayer_str3 "投诉建议(%d)"
#define str_HelpLayer_str4 "用户中心"
#define str_HelpLayer_str5 "同步社区"
#define str_HelpLayer_str6 "社区中心"
#define str_HelpLayer_str7 "切换伺服器"
#define str_HelpLayer_str8 "分享游戏"
#define str_HelpLayer_str9 "卡牌图鉴"
#define str_HelpLayer_str10 "FB官方粉丝团"
#define str_system "系统"

#define str_InviteNum_str1 "邀请码"
#define str_InviteNum_str2 "如果您是受好友邀请来玩这个游戏的,"
#define str_InviteNum_str3 "请将他提供的"
#define str_InviteNum_str4 "填写在上面,"
#define str_InviteNum_str5 "成功填写后您将获得"
#define str_InviteNum_str6 "2万铜钱,"
#define str_InviteNum_str7 "当您升到"
#define str_InviteNum_str8 "15级"
#define str_InviteNum_str9 "时,对方将可以获得"
#define str_InviteNum_str10 "3元宝"

#define str_LiuyanLayer_str1 "客服留言"
#define str_LiuyanLayer_str2 "提交"
#define str_LiuyanLayer_str3 "缺陷"
#define str_LiuyanLayer_str4 "建议"
#define str_LiuyanLayer_str5 "举报"
#define str_LiuyanLayer_str6 "储值"
#define str_LiuyanLayer_str7 "标     题:"
#define str_LiuyanLayer_str8 "详细描述"
#define str_LiuyanLayer_str9 "新建问题需间隔30秒"
#define str_LiuyanLayer_str10 "字数限制:100"
#define str_LiuyanLayer_str11 "请输入标题"
#define str_LiuyanLayer_str12 "您提交新问题的频率过快，请稍后再试"
#define str_LiuyanLayer_str13 "為了更準确的為您服务，请选择本次问题的类型。"
#define str_LiuyanLayer_str14 "為了更準确的為您服务，请您填写下标题内容。"
#define str_LiuyanLayer_str15 "為了更準确的為您服务，请详细描述下您的问题。"
#define str_LiuyanLayer_str16 "提交成功"
#define str_LiuyanLayer_str17 "哎呀，提交失败了哦~"

#define str_ChangeNickName_str1 "请输入主公的新名字:"
#define str_ChangeNickName_str2 "命名需2-7个字，可以是中文、字母、数字或符号。"
#define str_ChangeNickName_str3 "字数不符合要求"
#define str_ChangeNickName_str4 "15级以下的主公可以免费改名1次"
#define str_ChangeNickName_str5 "您符合免费条件"
#define str_ChangeNickName_str6 "改名需支付 100元宝"
#define str_ChangeNickName_str7 "您现有 %d元宝"
#define str_ChangeNickName_str8 "改名不能赊帐"

#define str_CountrysInfo_str1  "国家特性"
#define str_CountrysInfo_str2  "魏国国家特性"
#define str_CountrysInfo_str3  "蜀国国家特性"
#define str_CountrysInfo_str4  "吴国国家特性"
#define str_CountrysInfo_str5  "尚未开放,敬请期待"

#define str_PlayerInfoLayer_str1 "个人资料"
#define str_PlayerInfoLayer_str2 "补充"
#define str_PlayerInfoLayer_str3 "回满"
#define str_PlayerInfoLayer_str4 "换礼"
#define str_PlayerInfoLayer_str5 "兑换"
#define str_PlayerInfoLayer_str6 "储值"
#define str_PlayerInfoLayer_str7 "经验: %d / %d"
#define str_PlayerInfoLayer_str8 "特权"
#define str_PlayerInfoLayer_str9 "特性"
#define str_PlayerInfoLayer_str10 "邀请码:%s"
#define str_PlayerInfoLayer_str11 "当前体力已满,无需恢復"
#define str_PlayerInfoLayer_str12 "当前军粮已满,无需恢復"

#define str_CoinRewardBox_str1  "获得了今日登入奖励"
#define str_CoinRewardBox_str2  "记得明天要来哦"

#define str_DrinkWineLayer_str1 "煮酒论英雄"
#define str_DrinkWineLayer_str2 "每次喝酒,可以回復%d体力,记得準时来哦!"
#define str_DrinkWineLayer_str3 "正午 12点~13点"
#define str_DrinkWineLayer_str4 "黄昏 18点~19点"
#define str_DrinkWineLayer_str5 "体力已恢復"
#define str_DrinkWineLayer_str6 "还没有到喝酒的时间"
#define str_DrinkWineLayer_str7  "您已经喝过这个时段的酒了"

#define str_monthly_sign_str1 "签到奖励"
#define str_monthly_sign_str2 "%d月签到奖励"
#define str_monthly_sign_str3 "本月已累计签到 %d 天"
#define str_monthly_sign_str4 "当日签到奖励已领取，%s，是否前往储值？"
#define str_monthly_sign_str5 "主公可以去商店看看"

#define str_ExchangeCodeLayer_str1 "兑换码"
#define str_ExchangeCodeLayer_str2 "输入兑换码"
#define str_ExchangeCodeLayer_str3 "兑换码的使用和获得:"
#define str_ExchangeCodeLayer_str4  "兑换码不能有表情符号!"
#define str_ExchangeCodeLayer_str5 "兑换码不能為空"
#define str_ExchangeCodeLayer_str6  "兑换码输入有误！请重新输入"
#define str_ExchangeCodeLayer_str7  "兑换码输入有误！"
#define str_ExchangeCodeLayer_str8  "兑换码已使用"
#define str_ExchangeCodeLayer_str9  "已经兑换该类兑换码"
#define str_ExchangeCodeLayer_str10 "此兑换码在本区不能兑换！"
#define str_ExchangeCodeLayer_str11 "兑换失败，请联繫客服!"

#define str_GetSalaryLayer_str1  "%02d:%02d:%02d后可以收取"
#define str_GetSalaryLayer_str2  "%d天%02d:%02d:%02d后可以收取"
#define str_GetSalaryLayer_str3  "领俸禄"
#define str_GetSalaryLayer_str4  "您的帐号等级是: %d级"
#define str_GetSalaryLayer_str5  "每天可取 %d铜钱"
#define str_GetSalaryLayer_str501  "等级达到%d级每天可领取大量铜钱"
#define str_GetSalaryLayer_str6  "您在天梯晋级战中的天梯声望是: %d"
#define str_GetSalaryLayer_str7  "每三天可领%d铜钱"
#define str_GetSalaryLayer_str8  "当前可领取"
#define str_GetSalaryLayer_str9  "您未进入排行榜"
#define str_GetSalaryLayer_str10  "所有参加过天梯晋级赛（%d级开啟）"
#define str_GetSalaryLayer_str11  "的主公，都可定时领取大量铜币奖励。"
#define str_GetSalaryLayer_str12  "天梯声望越高，奖励越多哦！"
#define str_GetSalaryLayer_str14  "本赛季您还未参加任何天梯晋级赛，"
#define str_GetSalaryLayer_str15  "请在参加后进行相关奖励俸禄领取"

#define str_InviteeLayer_str1 "请填入邀请码"
#define str_InviteeLayer_str2 "小提醒: "
#define str_InviteeLayer_str3  "1.填写邀请码后，立即获得奖励"
#define str_InviteeLayer_str4 "2.填写邀请码可获得「铜钱1W」,「元宝100」奖励"
#define str_InviteeLayer_str401 "\"       1W”"
#define str_InviteeLayer_str402 "\"       100”奖励"
#define str_InviteeLayer_str403   "2.填写邀请码可获得"
#define str_InviteeLayer_str5  "3.奖励只能获得一次。"
#define str_InviteeLayer_str6  "提示：玩家任何等级都可以填写邀请码。"
#define str_InviteeLayer_str7 "请输入相关邀请码"
#define str_InviteeLayer_str8 "您已输入邀请码:%s"
#define str_InviteeLayer_str9 "被邀请人超过15级 "
#define str_InviteeLayer_str10  "不能填写自己的邀请码哦"
#define str_InviteeLayer_str11 "无效邀请人"
#define str_InviteeLayer_str12 "邀请码只能填写一次"
#define str_InviteeLayer_str13 "我去!!!"
#define str_InviteeLayer_str14 "请填入邀请码"

#define str_InviterLayer_str1 "我的邀请码"
#define str_InviterLayer_str2 "2.每个玩家的邀请码可被多个好友使用，不设上限。                                                                                        3. 邀请成功好友数量越多，可领取的奖励越多,邀请码30级可见。"

#define str_InviterLayer_str201 "邀请好友进入游戏，可获得丰厚奖励"
#define str_InviterLayer_str202 "1.好友进入游戏后，填写您的邀请码并"
#define str_InviterLayer_str203 "达到35级"
#define str_InviterLayer_str204 "才算邀请成功。(邀请码30级可见)"
#define str_InviterLayer_str205 "2.玩家的邀请码可被多个好友使用，不设上限。"
#define str_InviterLayer_str206 "3.邀请成功好友数量越多，可领取的奖励越多。"
#define str_InviterLayer_str207 "4.邀请码30级可见。"
#define str_InviterLayer_str3 "您的邀请码是: "
#define str_InviterLayer_str4 "已邀请: %d/%d 位"
#define str_InviterLayer_str5  "抱歉领奖失败，请联繫GM!"
#define str_InviterLayer_str6 "成功邀请"
#define str_InviterLayer_str7 "     位好友,可获得"
#define str_InviterLayer_str8  "%d 元宝"
#define str_InviterLayer_str9  "此奖励您已经领过了"
#define str_InviterLayer_str10 "您还未达到要求的数量"

#define str_JitianLayer_str1  "祭祀"
#define str_JitianLayer_str2 "已连续祭天"
#define str_JitianLayer_str3  " 次"
#define str_JitianLayer_str4 "每日祭祀可获得 "
#define str_JitianLayer_str5 "元宝 "
#define str_JitianLayer_str6 "奖励"
#define str_JitianLayer_str7  "连续祭祀"
#define str_JitianLayer_str8 "%d天"
#define str_JitianLayer_str9 "有机会获得神器!"
#define str_JitianLayer_str10 "祭祀完成,记得明天也要来哦!"
#define str_JitianLayer_str11 "感动上天,您获得了%s一个"
#define str_JitianLayer_str12 "今天已经祭祀过了，请明天再来"

#define str_LevelUpGetGold_str1 "升级得元宝"
#define str_LevelUpGetGold_str2 "升到"
#define str_LevelUpGetGold_str3 "级"
#define str_LevelUpGetGold_str4 "此奖励您已经领过了"
#define str_LevelUpGetGold_str5 "您还未达到要求的级别"
#define str_LevelUpGetGold_str6 "突破"
#define str_LevelUpGetGold_str7 "角色等级达到要求后可领取"
#define str_LevelUpGetGold_str8 "天梯等级（对战模式）达到要求后可领取"

#define str_LiandanLayer_str1 "领取高级经验丹需消耗炼丹秘方。"
#define str_LiandanLayer_str2 "当前拥有: %d个"
#define str_LiandanLayer_str3 "可收取"
#define str_LiandanLayer_str4  "还没有到领取丹药的时间"
#define str_LiandanLayer_str5  "恭喜您获得了奖励"

#define str_RewardBindLayer_str1 "  主公，绑定帐号可以确保更换设备后，帐号依然正常使用哦。成功绑定帐号后更有丰富奖励可以领取！"
#define str_RewardBindLayer_str2 "  主公，您的帐号已经成功绑定，可以领取如下奖励："
#define str_RewardBindLayer_str3 "您已经领取过该奖励。"
#define str_RewardBindLayer_str4 "註册成功,您可以开始游戏了"
#define str_RewardBindLayer_str5 "已经有人使用了这个帐号了"
#define str_RewardBindLayer_str101 "已领取"
#define str_RewardBindLayer_str102 "绑定"
#define str_RewardBindLayer_str103 "请输入要绑定的邮箱"
#define str_RewardBindLayer_str104 "再输入要绑定的邮箱"
#define str_RewardBindLayer_str105  "主公,绑定邮箱能够穫得额外丰厚奖励,点击下面输入框输入您的邮箱进行绑定吧!"
#define str_RewardBindLayer_str106 "主公,你的帐号已成功绑定邮箱%s可领取到如下奖励:"
#define str_RewardBindLayer_str107  "请输入正确的邮箱地址!"
#define str_RewardBindLayer_str108  "两次输入的邮箱不一緻!"
#define str_RewardBindLayer_str109 "该帐号已被绑定!"
#define str_RewardBindLayer_str110 "邮箱格式错误!"
#define str_RewardBindLayer_str111 "主公,你的帐号已成功绑定邮箱%s可领取到如下奖励:"
#define str_RewardBindLayer_str112 "确认提示"
#define str_RewardBindLayer_str113 "主公,您是否确认将帐号%s与邮箱%s进行绑定?绑定后无法解绑,请慎重操作!"
#define str_RewardBindLayer_str114 "绑定成功"
#define str_RewardBindLayer_str115 "主公，邮箱绑定成功，马上领取您的奖励吧！"

#define str_RewardBindLayer_str6  "月卡奖励领取"
#define str_RewardBindLayer_str7  "升级得元宝"
#define str_RewardBindLayer_str8  "迎财神"
#define str_RewardBindLayer_str9  "每天领俸禄"
#define str_RewardBindLayer_str10  "煮酒论英雄"
#define str_RewardBindLayer_str11 "祭天许愿"
#define str_RewardBindLayer_str12 "信息绑定领奖"
#define str_RewardBindLayer_str13 "炼丹秘境(%d)"
#define str_RewardBindLayer_str14 "炼丹秘境"
#define str_RewardBindLayer_str15 "领奖"
#define str_RewardBindLayer_str16 "您获得了%s一个！"
#define str_RewardBindLayer_str17  "开服奖励"

#define str_RewardRegLayer_str1 "财神离开:"
#define str_RewardRegLayer_str2 "天     小时     分      秒"
#define str_RewardRegLayer_str3 "拜神次数: "
#define str_RewardRegLayer_str4 "%s  拜财神获得            元宝"
#define str_RewardRegLayer_str5 "献上元宝可获得更多的元宝！"
#define str_RewardRegLayer_str6 "财神到~您获得了%d元宝"
#define str_RewardRegLayer_str7 "还差"
#define str_RewardRegLayer_str8 "天"
#define str_RewardRegLayer_str9 "登入就能领取"
#define str_RewardRegLayer_str10 "财神离开后不再返回，且拜且珍惜哦!"

#define str_RewardYueKaLayer_str1 "月卡奖励"
#define str_RewardYueKaLayer_str2 "抱歉领奖失败，请联繫GM!"
#define str_RewardYueKaLayer_str3 "每日登入，领取月卡奖励"
#define str_RewardYueKaLayer_str4 "奖励限当日领取,月卡奖励剩餘 %d 天"
#define str_RewardYueKaLayer_str5 "还未拥有该月卡"
#define str_RewardYueKaLayer_str6 "此奖励您已经领过了"
#define str_RewardYueKaLayer_str7 "您还未拥有该月卡"
#define str_RewardYueKaLayer_str8 "您已经累计登入"
#define str_RewardYueKaLayer_str9 "记得明天再来哦"
#define str_RewardYueKaLayer_str10 "还有未领取的奖励!"
#define str_RewardYueKaLayer_str101 "永久"

#define str_SetItem_str1 "音乐"
#define str_SetItem_str2 "音效"
#define str_SetItem_str3 "消息推送"
#define str_SetItem_str4  "游戏功能设定"

#define str_AllTaskLayer_str1 "还未达到条件哦"
#define str_AllTaskLayer_str2 "已领取过了"

#define str_AllTaskLayer_1 "暂时没有任务"
#define str_AllTaskLayer_2 "每日"
#define str_AllTaskLayer_str3 "主线"
#define str_AllTaskLayer_str4 "强化"
#define str_AllTaskLayer_str5 "活动"
#define str_AllTaskLayer_str6 "赵云积分老干劳森就该空间概况，说地烦啊老姐夫老阿姐佛车位人戳我俄军方"
#define str_AllTaskLayer_str7 "进度:1/2"
#define str_AllTaskLayer_str8 "进行中..."
#define str_AllTaskLayer_str9 "奖励 元宝x%d"
#define str_AllTaskLayer_str10 "已完成111111"
#define str_AllTaskLayer_str11 "进度：%d/%d"
#define str_AllTaskLayer_str12  "奖励  铜钱x%d"
#define str_AllTaskLayer_str13 "奖励  Pvp积分x%d"
#define str_AllTaskLayer_str14 "奖励  军功x%d"
#define str_AllTaskLayer_str15 "奖励  小喇叭x%d"
#define str_AllTaskLayer_str16 "奖励 炼丹秘方x%d"
#define str_AllTaskLayer_str17 "奖励  %sx%d"
#define str_AllTaskLayer_str18 "奖励 %sx%d"
#define str_AllTaskLayer_str19 "前往"
#define str_AllTaskLayer_str20 "领取成功！"
#define str_AllTaskLayer_str21 "领取失败！"
#define str_AllTaskLayer_str22 "提示:卡片转生后，等级上限得到提升"
#define str_AllTaskLayer_str23 "可以拥有更强大的能力"
#define str_AllTaskLayer_str24 "武将卡"
#define str_AllTaskLayer_str25 "装备卡"

#define str_FirstLayer_str1  "阵容 %d"
#define str_FirstLayer_str2  "战斗力: %d"

//#define str_FirstLayer_str3  "任 务"
//#define str_FirstLayer_str4  "活 动"
//#define str_FirstLayer_str5 "领 奖"
//#define str_FirstLayer_str6_1 "商 城"
//#define str_FirstLayer_str7 "强 化"
//#define str_FirstLayer_str6 "排 行"

#define str_FirstLayer_str3  ""
#define str_FirstLayer_str4  ""
#define str_FirstLayer_str5 ""
#define str_FirstLayer_str6_1 ""
#define str_FirstLayer_str7 ""
#define str_FirstLayer_str6 ""

#define str_FirstLayer_str8 "武 将"
#define str_FirstLayer_str9 "/#%d/#级开啟"
#define str_FirstLayer_str10 "你在参加PVP,不能参加守荆州"
#define str_FirstLayer_str11 "%d级开啟守荆州"
#define str_FirstLayer_str12 "%d级开啟讨魔"
#define str_FirstLayer_str13 "你在参加PVP,不能参加讨伐魔王"
#define str_FirstLayer_str14 "抱歉，您暂时不能进入守荆州噢~"
#define str_FirstLayer_str15 "你在参加PVP,不能参加闯关"
#define str_FirstLayer_str16 "总血量 %d\n"
#define str_FirstLayer_str17 "总速度 %d\n"
#define str_FirstLayer_str18 "战斗力  %d\n"

#define str_FirstLayer_str19 "选择强化卡牌类型"
#define str_FirstLayer_str20 "士兵卡"
#define str_FirstLayer_str21 "被动技"
#define str_FirstLayer_str22 "主将技"
#define str_FirstLayer_str23 "%d级开啟幻境"

#define str_soldier_intro1   "1. 不同国家拥有不同的3张士兵卡, 士兵卡不能卖出"
#define str_soldier_intro2   "2. 士兵卡通过吞噬兵魂卡提升等级, 上限為100级"
#define str_soldier_intro3   "3. 不同士兵卡拥有不同技能, 技能等级随士兵卡等级提升而提升"

#define str_soldier_detail   "详情"

#define str_MainTaskLayer_str1 "通关 白马银枪 奖励rrrrrrrrrrr"

#define str_MainTaskLayer_str2 "玩家名称"
#define str_MainTaskLayer_str3 "声望：%d"
#define str_MainTaskLayer_str4 "总战力：%d"
#define str_MainTaskLayer_str5 "等级：%d"
#define str_MainTaskLayer_str6 "伤害总量：%d"
#define str_MainTaskLayer_str7 "铜钱：%d"
#define str_MainTaskLayer_str8 "不能在跨服天梯查看详细阵型！"

#define str_MainTaskLayer_str9 "属性"
#define str_MainTaskLayer_str10 "统御力:   %d/%d"
#define str_MainTaskLayer_str11 "总血量:   %d"
#define str_MainTaskLayer_str12 "总速度:   %d"
#define str_MainTaskLayer_str13 "国    家:   蜀"
#define str_MainTaskLayer_str14 "国    家:   魏"
#define str_MainTaskLayer_str15 "国    家:   吴"
#define str_MainTaskLayer_str16 "天梯声望:   %d"
#define str_MainTaskLayer_str17 "天梯战绩:   胜%d   负%d"
#define str_MainTaskLayer_str18 "天梯排名:  未进榜"
#define str_MainTaskLayer_str19 "天梯排名:  本服第%d名"
#define str_MainTaskLayer_str20 "天梯胜率:  0.0 %"
#define str_MainTaskLayer_str21 "天梯胜率: %5.1f %%"

#define str_RankLayer_str1 "世界天梯"
#define str_RankLayer_str2 "本服天梯"
#define str_RankLayer_str3 "总战力"
#define str_RankLayer_str4 "角色等级"
#define str_RankLayer_str5 "财富排行"
#define str_RankLayer_str6  "未进榜"
#define str_RankLayer_str7 "我的排名:"
#define str_RankLayer_str8 "声望:"
#define str_RankLayer_str9 "总战力:"
#define str_RankLayer_str10 "铜钱:"

#define str_RankLayer_str11 "主线任务"
#define str_RankLayer_str12 "每日任务"
#define str_RankLayer_str13 "今日已做 %d/%d"

#define str_BlackFriend_str1 "您的黑名单裡是空的"
#define str_BlackFriend_str2 "黑名单"
#define str_BlackFriend_str3 "(%d/%d人)"
#define str_BlackFriend_str4 "解除黑名单失败"

#define str_ExpandFriend_str1 "好友位置扩充"
#define str_ExpandFriend_str2 "当前好友上限15个"
#define str_ExpandFriend_str3 "(含10扩充)"
#define str_ExpandFriend_str4 "支付"
#define str_ExpandFriend_str5 "60元宝，可以立即增加5个位置，"
#define str_ExpandFriend_str6 "通过这种方式您最多可增加50个好友位置。"
#define str_ExpandFriend_str7 "已达上限，不能使用这种方式提升好友人数了。"
#define str_ExpandFriend_str8 "(含%d扩充)"
#define str_ExpandFriend_str9 "当前好友上限%d个"
#define str_ExpandFriend_str10 "已扩充至上限"
#define str_ExpandFriend_str101 "当前不可扩充!"
#define str_ExpandFriend_str1012 "提升VIP等级才能继续扩充好友位置!"
#define str_ExpandFriend_str11 "好友位置增多了！ %d -> %d"
#define str_ExpandFriend_str12 "好友扩充"

#define str_FriendBase_str1 "当前没有任何好友"
#define str_FriendBase_str2 "好友请求发送异常"
#define str_FriendBase_str3 "对方的好友已满"
#define str_FriendBase_str4 "已经在你的好友列表中"
#define str_FriendBase_str5 "已经在他的黑名单中"
#define str_FriendBase_str6 "已经申请过了,在他的申请列表中"
#define str_FriendBase_str7 "对方在你的黑名单中,解除黑名单并申请"
#define str_FriendBase_str8 "好友请求发送成功"
#define str_FriendBase_str9 "消息发送失败"
#define str_FriendBase_str10 "不在自己的申请列表裡"
#define str_FriendBase_str11 "添加成功"
#define str_FriendBase_str12 "拒绝好友请求失败"
#define str_FriendBase_str13 "已拒绝该好友的请求"

#define str_FriendBase_str14 "当前线上"
#define str_FriendBase_str15 "22级"
#define str_FriendBase_str16 "暱称"
#define str_FriendBase_str17 "%d分鐘前登入"
#define str_FriendBase_str18 "%d小时前登入"
#define str_FriendBase_str19 "%d天前登入"
#define str_FriendBase_str20 "%d月前登入"
#define str_FriendBase_str21 "该玩家已不在当前列表中"

#define str_FriendCountFull_str1 "因為您的好友位置已满"
#define str_FriendCountFull_str2 "无法增加新的好友"
#define str_FriendCountFull_str3 "当前没有收到加友请求"
#define str_FriendCountFull_str4 "加友请求"
#define str_FriendCountFull_str5 "当前没有收到加友请求"
#define str_FriendCountFull_str6 "当前没有收到加友请求"

#define str_FriendCountFull_str7 "发送到社交平臺"
#define str_FriendCountFull_str8 "通过手机短信邀请"
#define str_FriendCountFull_str9 "该功能未开啟"

#define str_FriendCountFull_str10 "您还没有好友，可以到聊天室去认识一些新朋友"
#define str_FriendCountFull_str11 "我的好友"
#define str_FriendCountFull_str12 "删除好友失败"
#define str_FriendCountFull_str13 "删除好友成功"

#define str_FriendCountFull_str14 "国家:"
#define str_FriendCountFull_str15 "0级"
#define str_FriendCountFull_str16 "家族:"
#define str_FriendCountFull_str17 "无家族"
#define str_FriendCountFull_str18 "主将"
#define str_FriendCountFull_str19 "查看全部"
#define str_FriendCountFull_str20 "%s    等级：%d级"
#define str_FriendCountFull_str21 "%s    等级：%d级"
#define str_FriendCountFull_str22 "群英"
#define str_FriendCountFull_str23 "发邮件功能尚未开啟"
#define str_FriendCountFull_str24 "不能添加自己為好友"

#define str_FriendSendTiLi_str1   "领取体力"
#define str_FriendSendTiLi_str2   "成功赠送体力"
#define str_FriendSendTiLi_str3   "还没有好友赠送体力哦，试试主动赠送体力!"
#define str_FriendSendTiLi_str4   "今日还可领取次数: "
#define str_FriendSendTiLi_str5   "已赠送给好友过体力哦！"

#define str_FriendSendTiLi_str14 "刚刚赠送"
#define str_FriendSendTiLi_str17 "%d分鐘前赠送"
#define str_FriendSendTiLi_str18 "%d小时前赠送"
#define str_FriendSendTiLi_str19 "%d天前赠送"
#define str_FriendSendTiLi_str20 "%d月前赠送"
#define str_FriendSendTiLi_str21 "主公，你的体力已满，无需领取。"
#define str_FriendSendTiLi_str22 "主公，今天领取次数已用完。"
#define str_FriendSendTiLi_str23 "获得了%d点体力，并已回赠好友"
#define str_FriendSendTiLi_str24 "获得%d点体力"
#define str_FriendSendTiLi_str25 "领取体力失败"
#define str_FriendGetTiLiAll_str1 "一键领取并回赠"
#define str_FriendGetTiLiAll_str2 "还没有好友赠送体力哦"

#define str_SearchFriend_str1 "我要找人"
#define str_SearchFriend_str2 "您的角色ID是：%s"
#define str_SearchFriend_str3 "通过用户角色ID查找"
#define str_SearchFriend_str4 "查询"
#define str_SearchFriend_str5 "您还没有填写搜索条件呢～"
#define str_SearchFriend_str6 "搜索条件过短，请重新输入!"
#define str_SearchFriend_str7 "您还没有填写搜索条件呢～"
#define str_SearchFriend_str8 "没有这个玩家"

#define str_SearchFriend_str9 "不能添加自己进黑名单"
#define str_SearchFriend_str10 "好友请求"
#define str_SearchFriend_str11 "好友暱称"
#define str_SearchFriend_str12 "（3分鐘前）"
#define str_SearchFriend_str13 "邮件内容"

#define str_SearchFriend_str14 "好友消息"
#define str_SearchFriend_str15 "与 "
#define str_SearchFriend_str16 " 的消息记录"
#define str_SearchFriend_str17 "西门吹雪"

#define str_FriendMailLayer_str1 "来自好友的消息"
#define str_FriendMailLayer_str2 "您还没有任何好友消息"
#define str_FriendMailLayer_str3 "邮件删除成功"
#define str_FriendMailLayer_str4 "邮件删除失败"

#define str_FriendMailLayer_str5 "输入聊天文字"
#define str_FriendMailLayer_str6 "发言字数不符合要求"

#define str_FriendMailLayer_str7 "删除邮件成功!"
#define str_FriendMailLayer_str8 "军魂"
#define str_FriendMailLayer_str9 "天梯积分"

#define str_FriendMailLayer_str10 "恭喜你成功通关，获得奖励："
#define str_FriendMailLayer_str11 "系统邮件"
#define str_FriendMailLayer_str12 "（3分鐘前）"

#define str_FriendMailLayer_str13 "领取附件"
#define str_FriendMailLayer_str14 "本邮件中附带了物品：%d件"
#define str_FriendMailLayer_str15 "你好好你你你好你好你你好"
#define str_FriendMailLayer_str16 "邮件已收取！"
#define str_FriendMailLayer_str17 "查看邮件失败"
#define str_FriendMailLayer_str18  "本邮件中附带了物品：0件"
#define str_FriendMailLayer_str19 "接收附件失败"

#define str_SystemMailLayer_str1 "系统消息"
#define str_SystemMailLayer_str2 "您还没有任何系统消息"
#define str_SystemMailLayer_str3 "尚未开啟"
#define str_SystemMailLayer_str4 "我的消息"
#define str_SystemMailLayer_str5 "联繫GM（客服）"

#define str_SystemMailLayer_str6 "原价"
#define str_SystemMailLayer_str7 "数量 : %d"

#define str_SystemMailLayer_str8 "元宝换铜钱"
#define str_SystemMailLayer_str9 "vip等级越高,每天可以兑换的次数越多。"
#define str_SystemMailLayer_str10 "您不是vip,每天可以兑换 %d次 (已换 %d次)"
#define str_SystemMailLayer_str11 "每天可以兑换 %d次 (已换 %d次)"
#define str_SystemMailLayer_str12 "您是vip%d,每天可以兑换 %d次 (已换 %d次)"
#define str_SystemMailLayer_str13 "兑换成功! 获得了%d铜钱"
#define str_SystemMailLayer_str14 "今日兑换次数已用尽,不能兑换了"

#define str_GoldShopGoodsItem_str1 "今日还可购买:  "
#define str_GoldShopGoodsItem_str2 "需要:    "
#define str_GoldShopGoodsItem_str3 "购买"
#define str_GoldShopGoodsItem_str4 "原价:   "
#define str_GoldShopGoodsItem_str5 "现价:    "
#define str_GoldShopGoodsItem_str6 "价格:   "
#define str_GoldShopGoodsItem_str7 "剩餘数量:    "
#define str_GoldShopGoodsItem_str8 "截止时间:    "
#define str_GoldShopGoodsItem_str9 "当前等级不足，不能购买本商品！"
#define str_GoldShopGoodsItem_str10 "当前Vip等级不足，不能购买本商品！"
#define str_GoldShopGoodsItem_str12 "Vip等级或等级不足，不能购买本商品"
#define str_GoldShopGoodsItem_str13 "商品已经下架！"
#define str_GoldShopGoodsItem_str14 "可购买次数不足！"
#define str_GoldShopGoodsItem_str15 "共拥有%d个"
#define str_GoldShopGoodsItem_str16 "请选择购买 "
#define str_GoldShopGoodsItem_str17 "的数量"
#define str_GoldShopGoodsItem_str18 "总价:   "
#define str_GoldShopGoodsItem_str19 "请选择商品数量!"
#define str_GoldShopGoodsItem_str20 "元宝不够！"
#define str_GoldShopGoodsItem_str21 "礼包详情"
#define str_GoldShopGoodsItem_str22 "您获得以下物品"

#define str_GoldShopLimitTimeSell_str1 "元宝商城"
#define str_GoldShopLimitTimeSell_str2 "当前拥有		元宝:"
#define str_GoldShopLimitTimeSell_str3 "今日特价"
#define str_GoldShopLimitTimeSell_str4 "限时出售"
#define str_GoldShopLimitTimeSell_str5 "普通商品"

#define str_GoldShopLimitTimeSell_str6 "商城"
#define str_GoldShopLimitTimeSell_str7 "储      值"
#define str_GoldShopLimitTimeSell_str8 "VIP礼包"
#define str_GoldShopLimitTimeSell_str18 "洛阳鬼市"
#define str_GoldShopLimitTimeSell_str19 "荆州军需处"
#define str_GoldShopLimitTimeSell_str20 "云游商人"
#define str_GoldShopLimitTimeSell_str21 "%d级开啟天梯商城"
#define str_GoldShopLimitTimeSell_str22 "%d级开啟荆州军需处"
#define str_GoldShopLimitTimeSell_str23 "其他计费点资讯"

#define str_GoldShopLimitTimeSell_str24 "%d级开啟幻境商城"
#define str_GoldShopLimitTimeSell_str25 "%d级开啟乱世商人"
#define str_GoldShopLimitTimeSell_str26 "幻境商城"
#define str_GoldShopLimitTimeSell_str27 "乱世商人"

#define str_GoldShopLimitTimeSell_str9 "%d元"
#define str_GoldShopLimitTimeSell_str10 "下次购买:%d天"
#define str_GoldShopLimitTimeSell_str11 "%d元宝"
#define str_GoldShopLimitTimeSell_str12 "无优惠"
#define str_GoldShopLimitTimeSell_str13 "每日登入"
#define str_GoldShopLimitTimeSell_str14 "领取"
#define str_GoldShopLimitTimeSell_str15 "900元宝"
#define str_GoldShopLimitTimeSell_str16 "X30天"
#define str_GoldShopLimitTimeSell_str17 "下次购买:30天"
#define str_GoldShopLimitTimeSell_str108 "X永久"
#define str_GoldShopLimitTimeSell_str109 "X%d天"
#define str_GoldShopLimitTimeSell_str200 "可购买"

#define str_StoreLayer_str1 "您当前不是VIP"
#define str_StoreLayer_str2 "再储值%d元,可升為vip1"
#define str_StoreLayer_str3 "您当前為 : "
#define str_StoreLayer_str4 "享受最尊崇的礼遇!"
#define str_StoreLayer_str5 "再储值%d元,可升為vip%d"
#define str_StoreLayer_str6 "您已拥有该月卡!"
#define str_StoreLayer_str7 "储值功能暂不开放！！敬请期待！"
#define str_StoreLayer_str8 "购买物品成功!"
#define str_StoreLayer_str9 "购买物品失败!"

#define str_StoreLayer_str10 "VIP特权"
#define str_StoreLayer_str11 "您当前不是VIP"
#define str_StoreLayer_str12 "购买失败"
#define str_StoreLayer_str13 "特权: "
#define str_StoreLayer_str14 "您已购买该礼包"
#define str_StoreLayer_str15 "您需要先成為VIP%d"

#define str_ActivityMainCell_str1 "活动名称"
#define str_ActivityMainCell_str101 "挑战次数%d/%d"
#define str_ActivityMainCell_str2 "开啟提示"
#define str_ActivityMainCell_str3 "00小时"
#define str_ActivityMainCell_str4 "小时"
#define str_ActivityMainCell_str5 "%d 小时"
#define str_ActivityMainCell_str6 "开啟剩餘: "
#define str_ActivityMainCell_str7 "%d 分鐘"
#define str_ActivityMainCell_str8 "分鐘"
#define str_ActivityMainCell_str9 "结束剩餘: "

#define str_ActivityMainCell_str10 "限时副本"
#define str_ActivityMainCell_str11 "副本还未开啟!"
#define str_ActivityMainCell_str111 "没有挑战次数了!"

#define str_ActivityMainCell_str12 "我方损失：%.0f%%"
#define str_ActivityMainCell_str13 "我方损失：无伤"
#define str_ActivityMainCell_str14 "获得经验："
#define str_ActivityMainCell_str15 "获得元宝："
#define str_ActivityMainCell_str16 "获得军功："
#define str_ActivityMainCell_str17 "剩餘血量："
#define str_ActivityMainCell_str18 "恭喜您已经成功守住了荆州"
#define str_ActivityMainCell_str19 "继续闯关"
#define str_ActivityMainCell_str20 "待会再来"
#define str_ActivityMainCell_str21 "抱歉，您暂时不能进入守荆州噢~"
#define str_ActivityMainCell_str22 "恭喜您已经成功守住了荆州"

#define str_OverBattleBox_str1 "由於我方血量值高於对方，我方胜利！"
#define str_OverBattleBox_str2 "由於我方血量值低於对方，我方失败！"
#define str_OverBattleBox_str3 "对方已退兵"
#define str_OverBattleBox_str4 "你选择投降"
#define str_OverBattleBox_str5 "你获得胜利！"
#define str_OverBattleBox_str6  "我方失败！"

#define str_OverBattleBox_str7 "快速战斗"
#define str_OverBattleBox_str8 "此关卡您的战斗评价还没有达到二星状态，无法跳过战斗。"
#define str_OverBattleBox_str9 "您可以直接跳过战斗，获得奖励呦！O(∩_∩)O"
#define str_OverBattleBox_str10 "(小提醒：VIP4战斗评价达到二星即可跳过战斗咯！)"
#define str_OverBattleBox_str1011 "继续"
#define str_OverBattleBox_str1012 "通关奖励"
#define str_OverBattleBox_str1013 "扫荡完成"
#define str_OverBattleBox_str1014 "第%d次扫荡获得:"

#define str_OverBattleBox_str11  "86%以上"
#define str_OverBattleBox_str12 "我方损失：%.0f%%"
#define str_OverBattleBox_str13 "我方损失：无伤"
#define str_OverBattleBox_str14 "评价："
#define str_OverBattleBox_str15 "获得经验：%d"
#define str_OverBattleBox_str16 "获得经验：%d + %d"
#define str_OverBattleBox_str17 "获得铜钱：%d"
#define str_OverBattleBox_str18 "获得军功：%d"
#define str_OverBattleBox_str19 "获得金子：%d"
#define str_OverBattleBox_str20 "获得卡片"

#define str_OverBattleBox_str21 "等级"
#define str_OverBattleBox_str22 "%d军功"
#define str_OverBattleBox_str23 "玩家等级: %d级"

#define str_OverBattleBox_str24 "找个人来帮忙"
#define str_OverBattleBox_str25 "剩餘%d分鐘"

#define str_OverBattleBox_str26 "闯关模式"

#define str_StorySectionCell_str1 "通关奖励"
#define str_StorySectionCell_str2 "剩餘可挑战次数: %d"
#define str_StorySectionCell_str3 "还需          颗"
#define str_StorySectionCell_str4 "今日可挑战次数和重置次数已用尽!"
#define str_StorySectionCell_str3 "还需          颗"
#define str_StorySectionCell_str401 "副本挑战次数已用尽!"

//#define str_StorySectionCell_str5 "您今日守荆州次数已用完.\n升级到Vip等级%d,拥有购买守荆州次数的机会."
//#define str_StorySectionCell_str6 "您今日守荆州次数已用完.\n您当前Vip等级為%d,今日剩餘可购买次数為0,Vip等级升到%d级,拥有更多购买机会."
//#define str_StorySectionCell_str7 "您今日守荆州次数已用完.\n您当前Vip等级為%d,今日剩餘可购买次数為0"

#define str_shoujingzhou_please_buy_vip "您今日守荆州次数已用尽。\n提升至vip%d级可额外购买%d次。"
#define str_shoujingzhou_no_more_time "您今日守荆州次数和购买次数皆已用尽，请明天再来吧。"

#define str_StorySectionCell_str8 "您今日守荆州次数已用尽.\n当前Vip等级剩餘可购买%d次，是否花费%d元宝购买？"
#define str_StorySectionCell_str9 "本关卡挑战次数已用尽，今日剩餘重置次数%d/%d，是否花费%d元宝重置？"
#define str_StorySectionCell_str10 "本章没有攒够足够的★哦！"
#define str_StorySectionCell_str11 "体力消耗:"
#define str_StorySectionCell_str12 "建议战斗力:"
#define str_StorySectionCell_str13 "胜利获得:"
#define str_StorySectionCell_str14 "剩餘重置次数: %d"
#define str_StorySectionCell_str15 "机率获得: "
#define str_StorySectionCell_str16 "本章达到    x    ，获得以下奖励:"
#define str_StorySectionCell_str17 "新章节开啟"
#define str_StorySectionCell_str18 "满星通关！是否领取奖励并开始挑战下一章？"
#define str_StorySectionCell_str19 "新关卡开啟!是否立即前往？"
#define str_StorySectionCell_str23 "本关奖励已经领取."

#define str_StorySectionCell_str20 "%.2f倍经验奖励"
#define str_StorySectionCell_str21  "%.2f倍金钱奖励"
#define str_StorySectionCell_str22 "剩餘%d分鐘\033"

#define str_CanVisitBox_str1 "帐户中有%d元宝,不足以支付。"
#define str_CanVisitBox_str2 "本次探访要支付300元宝，您的"
#define str_CanVisitBox_str3 "本次探访要支付100元宝，您的"
#define str_CanVisitBox_str4 "本次探访要支付2800元宝，您的"
#define str_CanVisitBox_str5 "本次探访要支付1000元宝，您的"
#define str_CanVisitBox_str6 "的帐户中有%d铜钱,不足以支付。"
#define str_CanVisitBox_str7 "本次探访要支付 10000铜钱 您"
#define str_CanVisitBox_str8 "本次探访要支付 100铜钱 您"
#define str_CanVisitBox_str9 "本次探访要支付 100000铜钱 您"
#define str_CanVisitBox_str10 "本次探访要支付 1000铜钱 您"

#define str_CanVisitBox_str13 "您的帐户中有%d元宝,不足以支"
#define str_CanVisitBox_str14 "付。但您可以花费%d元宝连续"
#define str_CanVisitBox_str15 "连探11次需要支付 3000元宝 "
#define str_CanVisitBox_str16 "探访%d次，可以吗?"
#define str_CanVisitBox_str17 "付。但您可以花费%d元宝连续"
#define str_CanVisitBox_str18 "连探11次需要支付 1000元宝 "
#define str_CanVisitBox_str19 "中有%d铜钱,不足以支付"
#define str_CanVisitBox_str20 "但您可以花费%d铜钱连续探访%d次,"
#define str_CanVisitBox_str21 "连探11次需要支付3000铜钱 您的帐户"
#define str_CanVisitBox_str22 "连探11次需要支付1000铜钱 您的帐户"
#define str_CanVisitBox_str23 "可以吗?"
#define str_CanVisitBox_str24 "您的帐户中只有%d元宝"
#define str_CanVisitBox_str25 "不足以支付本次探访哦！"
#define str_CanVisitBox_str26 "购买失败"
#define str_CanVisitBox_str27 "购买失败"
#define str_CanVisitBox_str28 "购买失败"
#define str_CanVisitBox_str29 "购买失败"

#define str_TongQueLayer_str1 "铜雀台"
#define str_TongQueLayer_str2 "当前拥有"
#define str_TongQueLayer_str3 "下次自动刷新 "
#define str_TongQueLayer_str4 "刷新"
#define str_TongQueLayer_str5 "免费刷新"
#define str_TongQueLayer_str6 "点击刷新可更换宝物.夺宝需消耗讨魔勋章.每次夺宝可获得祝福值"
#define str_TongQueLayer_str7 "祝福值累积满后，可开啟宝箱获得超级奖励.祝福值每天0时刷新."
#define str_TongQueLayer_str8 "(点击查看)"
#define str_TongQueLayer_str9 "(点击领取)"
#define str_TongQueLayer_str10 "可以领取铜雀台秘宝了!"
#define str_TongQueLayer_str11 "所有宝物都已获得，请刷新宝物。"
#define str_TongQueLayer_str12 "勋章不足"
#define str_TongQueLayer_str13 "恭喜您获得了:%s"
#define str_TongQueLayer_str14 "请稍后刷新!"
#define str_TongQueLayer_str15 "您的铜钱不足哦！"
#define str_TongQueLayer_str16 "宝物已刷新"
#define str_TongQueLayer_str17 "可以领取铜雀台秘宝了。"
#define str_TongQueLayer_str18 "勋章x%d"

#define str_TongQueLayer_str19 "槽满后必赠1张"
#define str_TongQueLayer_str20 "紫卡"
#define str_TongQueLayer_str21 "后免费"
#define str_TongQueLayer_str22 "时间显示"
#define str_TongQueLayer_str23 "时开啟"
#define str_TongQueLayer_str24 "秒后开啟"
#define str_TongQueLayer_str25 "活动已开啟"
#define str_TongQueLayer_str26 "活动已结束"

#define str_TongQueLayer_str27 "槽满后赠一次！ (槽能量每日0点清空)"
#define str_TongQueLayer_str28 "群英薈萃"
#define str_TongQueLayer_str29 "限量名将"
#define str_TongQueLayer_str30 "当前拥有   元宝:"
#define str_TongQueLayer_str31 "军功: "
#define str_TongQueLayer_str32 "探访1次"
#define str_TongQueLayer_str33 "探访10次"
#define str_TongQueLayer_str34 "元宝抽武将"
#define str_TongQueLayer_str35 "元宝抽装备"
#define str_TongQueLayer_str36 "敬请期待"
#define str_TongQueLayer_str37 "确  定 "
#define str_TongQueLayer_str3701 "分 享"
#define str_TongQueLayer_str38 "猪头小泽"
#define str_TongQueLayer_str39 "夏侯惇"

#define str_TongQueLayer_str40  "(槽能量每日0点清空)"
#define str_TongQueLayer_str41  "VIP等级达到%d时开放该活动!"
#define str_TongQueLayer_str42  "金钱: "
#define str_TongQueLayer_str43  "获得 %s X %d"

#define str_YangXinBox_str1 "领 取"
#define str_YangXinBox_str2 "恭喜您获得了: "
#define str_YangXinBox_str3 "积攒足量夺宝祝福，可获得: "
#define str_YangXinBox_str4 "铜雀台秘宝"

#define str_MainLayer_str5 "商品裡面没有东西！"
#define str_MainLayer_str6 "本分类商城下无商品！"
#define str_MainLayer_str7 "购买成功！"
#define str_MainLayer_str8 "购买失败，剩餘数量不足！"
#define str_MainLayer_str9 "购买失败，商品已经下架！"
#define str_MainLayer_str10 "购买失败，购买物品数量超过上限制！"
#define str_MainLayer_str11 "购买失败，等级不足！"
#define str_MainLayer_str12 "购买失败，Vip等级不足！"
#define str_MainLayer_str13 "购买失败，元宝个数不足！"
#define str_MainLayer_str14 "%d级开啟天梯"
#define str_MainLayer_str1401 "%d级开啟天梯商城"
#define str_MainLayer_str15 "功能尚未开啟!"
#define str_MainLayer_str152 "普通模式通关第%d章后开啟精英模式"
#define str_MainLayer_str16 "你在参加PVP,不能参加副本"
#define str_MainLayer_str17 "%d级开啟副本"
#define str_MainLayer_str18 "当前时段没有活动, 无法进入副本！"
#define str_MainLayer_str19 "通关普通关卡%s章后，开啟精英副本模式"
#define str_MainLayer_str191 "第八"
#define str_MainLayer_str20 "不能参加精英副本!"
#define str_MainLayer_str21 "哎呀，查看的物品已失效！"
#define str_MainLayer_str22 "您查看的信息已失效。"
#define str_MainLayer_str23  "等级不够"
#define str_MainLayer_str24 "军粮不够"
#define str_MainLayer_str25 "胜利次数不够20场"
#define str_MainLayer_str26 "现在未到竞技场开放时间"
#define str_MainLayer_str27 "赛季未开放"
#define str_MainLayer_str28 "您已报名，请耐心等待！"
#define str_MainLayer_str29 "报名失败！！请重新报名。"
#define str_MainLayer_str30 "元宝回体力"
#define str_MainLayer_str31 "两次展示物品之间需要休息15秒!"
#define str_MainLayer_str32 "成功展示了哦！"
#define str_MainLayer_str33 "该功能尚未开放!"
#define str_MainLayer_str34 "首储奖励"
#define str_MainLayer_str35 "这是奖励物品啊"

#define str_MainLayer_str36 "对战速配中"
#define str_MainLayer_str37 "显示记忆体资讯"

#define str_MainLayer_str38 "%d 行, %d 列"
#define str_MainLayer_str39 "行列有问题"
#define str_MainLayer_str40 "移动"

#define str_MainLayer_str43 "删除"

#define str_MainLayer_str46  "出兵数量為0！！！"
#define str_MainLayer_str47 "数量不可能是0"
#define str_MainLayer_str48 "出兵数据為空！！！"
#define str_MainLayer_str49 "不可 空"
#define str_MainLayer_str50 "无操作"
#define str_MainLayer_str51 "哦耶 验证成功啦！！！"
#define str_MainLayer_str52 "保存截图"
#define str_MainLayer_str53 "战斗復活"
#define str_MainLayer_str54 "有一场战斗正在进行中哦！"
#define str_MainLayer_str55 "没有这个关卡哦！"
#define str_MainLayer_str56 "背包已满，不能进入哦！"
#define str_MainLayer_str57 "体力不足哦！"
#define str_MainLayer_str58 "武将统御力超出哦！"
#define str_MainLayer_str59 "关卡正在準备中哦！"
#define str_MainLayer_str60 "未到关卡开放时间哦！"
#define str_MainLayer_str61 "同名武将不能同时上场哦!"
#define str_MainLayer_str62 "体力不够"
#define str_MainLayer_str63 "军粮不够"

#define str_MainLayer_str64 "需要主公等级达到%d级才能参加天梯晋级战！"
#define str_MainLayer_str6403 "需要主公等级达到%d级才能参加！"
#define str_MainLayer_str604 "需要主公等级达到%d级才能参加守荆州！"
#define str_MainLayer_str65 "限时副本已结束哦!"

#define str_UpdateFail_str1 "更新失败"
#define str_UpdateFail_str2 "更新资源失败"
#define str_UpdateFail_str3 "游戏更新"
#define str_UpdateFail_str4 "游戏版本过低，请下载新版本后继续游戏。"
#define str_UpdateFail_str5 "游戏更新"
#define str_UpdateFail_str6 "资源更新中"
#define str_UpdateFail_str7 "伺服器繁忙，请稍后再尝试登入。"
#define str_UpdateFail_str8 "有新的游戏版本发布，是否立即更新？"
#define str_UpdateFail_str9 "载入失败"
#define str_UpdateFail_str10 "解压缩失败"
#define str_UpdateFail_str11 "解压缩资源中..."
#define str_UpdateFail_str12 "网路异常，请稍后再尝试登入。"
#define str_UpdateFail_str13 "版本检测中"
#define str_NetworkExp_str1  "网路异常"
#define str_ServerExp_str1   "伺服器繁忙"

#define str_Tools_str1 "很久以前"
#define str_Tools_str2 "%lld个月前"
#define str_Tools_str3  "%lld天前"
#define str_Tools_str4 "%lld小时前"
#define str_Tools_str5  "%lld分鐘前"
#define str_Tools_str6 "刚刚"

#define str_wujiangqianghua "武将强化"
#define str_wujiangjiqianghua "主将计强化"
#define str_zhuangbeiqianghua "装备强化"
#define str_zbqianghuacurstatus "当前属性"
#define str_zbqianghuanextstatus "强化属性"
#define str_zbqianghuancost "花费铜钱: "
#define str_zbqianghuantotalMy "现有铜钱: "
#define str_zbqianghuatoplevel "装备等级已达到上限 "
#define str_zbqianghuaneedmoney "所需铜钱不足 "
#define str_beidongjiqianghua "被动技强化"
#define str_shibinqianghua "士兵强化"

#define str_wan_ "%d万"
#define str_SGShareBox_str1 "分 享 奖 励"
#define str_SGShareBox_str2 "点击相应图示进行分享,邀请小伙伴一起来游戏吧"
#define str_SGShareBox_str3 "每日首次分享可获得"
#define str_SGShareBox_str4 "朋友圈"
#define str_SGShareBox_str5 "推 特"
#define str_SGShareBox_str6 "新浪微博"

#define str_SGShareBox_str7 "已领取元宝%d 铜钱%d"

#if (PLATFORM == IOS)

#if GAMENAME == XDGAME
#define str_SGShareBoxInfo_genral @"我正在玩手机游戏中国好三国，一起来试一试吧！"
#define str_SGShareBoxInfo_visit @"我刚才在中国好三国裡进行了一次武将探访，收穫不菲啊！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_boss @"吕布发疯了，不过刚刚已经被我制服，汝何不来一起试一试中国好三国？"
#define str_SGShareBoxInfo_pvefight @"终於战胜了这关boss，中国好三国的关卡太有挑战性了！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_jinzhou @"荆州之战一触即发，热血儿郎，当血染沙场换取军魂，赶紧一起来中国好三国吧！"
#elif GAMENAME == G2GAME
#define str_SGShareBoxInfo_genral @""
#define str_SGShareBoxInfo_visit @""
#define str_SGShareBoxInfo_boss @""
#define str_SGShareBoxInfo_pvefight @""
#define str_SGShareBoxInfo_jinzhou @""
#else
#define str_SGShareBoxInfo_genral @"我正在玩手机游戏中国好三国，一起来试一试吧！"
#define str_SGShareBoxInfo_visit @"我刚才在中国好三国裡进行了一次武将探访，收穫不菲啊！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_boss @"吕布发疯了，不过刚刚已经被我制服，汝何不来一起试一试中国好三国？"
#define str_SGShareBoxInfo_pvefight @"终於战胜了这关boss，中国好三国的关卡太有挑战性了！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_jinzhou @"荆州之战一触即发，热血儿郎，当血染沙场换取军魂，赶紧一起来中国好三国吧！"
#endif

#else

#if GAMENAME == XDGAME
#define str_SGShareBoxInfo_genral "我正在玩手机游戏中国好三国，一起来试一试吧！"
#define str_SGShareBoxInfo_visit "我刚才在中国好三国裡进行了一次武将探访，收穫不菲啊！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_boss "吕布发疯了，不过刚刚已经被我制服，汝何不来一起试一试中国好三国？"
#define str_SGShareBoxInfo_pvefight "终於战胜了这关boss，中国好三国的关卡太有挑战性了！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_jinzhou "荆州之战一触即发，热血儿郎，当血染沙场换取军魂，赶紧一起来中国好三国吧！"
#elif GAMENAME == G2GAME
#define str_SGShareBoxInfo_genral ""
#define str_SGShareBoxInfo_visit ""
#define str_SGShareBoxInfo_boss ""
#define str_SGShareBoxInfo_pvefight ""
#define str_SGShareBoxInfo_jinzhou ""
#else
#define str_SGShareBoxInfo_genral "我正在玩手机游戏中国好三国，一起来试一试吧！"
#define str_SGShareBoxInfo_visit "我刚才在中国好三国裡进行了一次武将探访，收穫不菲啊！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_boss "吕布发疯了，不过刚刚已经被我制服，汝何不来一起试一试中国好三国？"
#define str_SGShareBoxInfo_pvefight "终於战胜了这关boss，中国好三国的关卡太有挑战性了！赶紧一起来玩吧！"
#define str_SGShareBoxInfo_jinzhou "荆州之战一触即发，热血儿郎，当血染沙场换取军魂，赶紧一起来中国好三国吧！"
#endif

#endif

#define str_sgQfightBox_str1 "今日剩餘扫荡次数"
#define str_sgQfightBox_str2 "三星通关后可使用扫荡功能,快速获得关卡奖励!"
#define str_sgQfightBox_str3 "扫荡十次"
#define str_sgQfightBox_str202 "扫荡两次"
#define str_sgQfightBox_str4 "扫荡一次"
#define str_sgQfightBox_str5 "进入战斗"
#define str_sgQfightBox_str6 "扫荡次数不足!"
#define str_sgQfightBox_str7  "体力不足!"
#define str_sgQfightBox_str701  "达到vip%d时或主公达到%d级可使用该功能"
#define str_sgQfightBox_str702  "达到vip1时可使用该功能"
#define str_sgQfightBox_str703 "(提升VIP等级每日可获得更多扫荡次数)"
#define str_sgQfightBox_str704 "正在扫荡中"
#define str_StoryMainLayer_str1 "主公等级达到%d级时可挑战本关卡。"
#define str_sgQfightBox_str201  "通关后可使用扫荡功能,快速获得关卡奖励!"
#define str_sgQfightBox_str203 "挑战次数不足!"

//商店
#define str_MallLayer_str1 "天梯商城"
#define str_MallLayer_str2 "购买"
#define str_MallLayer_str3 "取消"
#define str_MallLayer_str4 "刷新"
#define str_MallLayer_str5 "购买失败，请重新购买"
#define str_MallLayer_str6 "购买成功"
#define str_MallLayer_str7 "对不起，您的 %s 不足，无法购买"
#define str_MallLayer_str8 "对不起，商品不足，请刷新商品后购买"
#define str_MallLayer_str9 "对不起，商品无法购买"
#define str_MallLayer_str10 "对不起，您的 %s 不足，不能刷新"
#define str_MallLayer_str11 "刷新确认"
#define str_MallLayer_str12 "刷新一批新的货物需要消耗"
#define str_MallLayer_str13 "确定要继续吗？"
#define str_MallLayer_str14 "拥有             个"
#define str_MallLayer_str15 "购买        个"
#define str_MallLayer_str16 "每日更新时间"
#define str_MallLayer_str17 "没有剩餘"
#define str_MallLayer_str18 "不能刷新"
#define str_MallLayer_str19 "已售出"
#define str_MallLayer_str20 "限制购买中..."

#define str_Currency_YanBao "元宝"
#define str_Currency_TongQian "铜钱"
#define str_Currency_TianTiJiFen "天梯积分"
#define str_Currency_JunGong "军功"
#define str_Currency_JunHun "军魂"
#define str_Currency_XunZhang "勋章"

//商店  end.

#define str_ShareGame_str1 "分享成功！"
#define str_ShareGame_str2 "分享失败！"
#define str_SGStorySectionLayer_str101  "(剩餘%d/%d)"

//图鉴来源
#define str_lookWiKi_1 "获取途径"
#define str_lookWiKi_2 "关闭"
#define str_lootWiKi_3 "该星级卡牌暂不由日常功能產出"
#define str_lootWiKi_4 "守荆州"
#define str_lootWiKi_5 "副本"
#define str_lootWiKi_6 "闯关"
#define str_lootWiKi_7 "天梯"
#define str_lootWiKi_8 "讨魔"
#define str_lootWiKi_9 "%d开放关卡"
#define str_lootWiKi_10 "不能参加该精英副本"
#define str_lootWiKi_11 "主公您尚未开啟该关卡噢~"
#define str_lootWiKi_12 "未开啟"

#define str_PvpSurrenderLimitMsg  "pvp战局瞬息万变，观察%d回合后再投降吧!"

#define str_SGCantAdvanceBox_1001 "更新完成提示"
#define str_SGCantAdvanceBox_1002 "资源更新完成需您重啟游戏"

#define str_SHOWWINDOW_1001 "此功能尚未开啟"
#define str_SHOWWINDOW_1002 "密码不能為空"
#define str_SHOWWINDOW_1003 "新密码必须為6﹣16為英文或数字"
#define str_SHOWWINDOW_1004 "密码格式不对"
#define str_SHOWWINDOW_1005 "新密码不一致"
#define str_SHOWWINDOW_1006 "旧密码"
#define str_SHOWWINDOW_1007 "新密码与旧密码相同"
#define str_SHOWWINDOW_1008 "帐号错误"
#define str_SHOWWINDOW_1009 "新密码格式错误"
#define str_SHOWWINDOW_1010 "新旧密码相同"
#define str_SHOWWINDOW_1011 "密码修改成功"
#define str_SHOWWINDOW_1012 "请输入帐号和密码"
#define str_SHOWWINDOW_1013 "帐号不存在"
#define str_SHOWWINDOW_1014 "密码错误"

#define str_SGShadeBox2_1  "等待对方玩家进入中"

#define str_SDKCallBack_1  "绑定失败，帐号已绑定过其他游客"
#define str_SDKCallBack_2  "用户名為6﹣16位英文和数字"
#define str_SDKCallBack_3  "密码為6﹣16位英文和数字"
#define str_SDKCallBack_4  "用户名已存在"
#define str_SDKCallBack_5  "登入密码输入错误!"

#define str_SGSoldierItem_1 "士兵名称"
#define str_SGSoldierItem_2  "成长技"
#define str_SGSoldierItem_3  "天赋技"
#define str_SGSoldierItem_4  "无技能"

//攻防士速四大文本
#define SGFII_ATTR_ATK "攻击"
#define SGFII_ATTR_DEF "防御"
#define SGFII_ATTR_MOR "血量"
#define SGFII_ATTR_SPD "速度"
#define str_lvBu_ "吕佈"

//通用信息框文本
#define str_cib_fate_officer "缘分武将："

//召唤、转生 动画
#define str_adv_eff_1 "转生成功"
#define str_adv_eff_2 "召唤成功"
#define str_adv_eff_3 "已拥有此武将，转化為%d个碎片。"
#define str_adv_eff_4 "碎片可用於武将转生"

//新pvp战斗结算
#define SGPvpFightRewardLayer_1 "获得天梯声望： "
#define SGPvpFightRewardLayer_2 "获得天梯积分： "
#define SGPvpFightRewardLayer_3 "预计天梯排名： "

#define str_exit_game_title "主公且慢"
#define str_exit_game_notice "要放弃天下归隐山林了吗？"

//幻境
#define str_GouYu           "勾玉"
#define str_SpecialBattleIntro  "幻境介绍"
#define str_SpecialBattleBuyCount "挑战次数已用尽，今日剩餘购买次数%d/%d，是否花费%d元宝购买一次？"
#define str_SpecialBattleSuggestPower   "建议战斗力: %d"
#define str_SpecilaBattleLimit          "勾玉数量已达上限！"
#define str_SpecialBattleResidue        "剩餘次数: %d/%d 次"
#define str_SpecialBattleBuyTips        "购买次数"
#define str_SpecialBattleNoneCondition  "阵容不符，无法挑战，请调整阵容！"
#define str_SpecialBattleNoneCondition1  "次数不足，无法挑战！"

#define str_SpecialBattleCanUseCount    "还有可剩餘次数！"
#define str_SpecailBattleResidueCoint   "剩餘次数: %d"
#define str_SpecialBattleRuleTips       "规则说明"
#define str_SpecialBattleNotCanBuy      "可购买次数不足！"
#define str_SpecialBattlePreview        "关卡掉落预览"

#define str_source "获取"

#define str_developing_officer_1 "潜力点：%d"
#define str_developing_officer_2 "可增加潜力点：%d/%d"
#define str_developing_officer_3 "最大%d)"
#define str_developing_officer_4 "培养一次"
#define str_developing_officer_5 "培养十次"
#define str_developing_officer_6 "保存"
#define str_developing_officer_7 "放弃"
#define str_developing_officer_8 "（1潜力点）"
#define str_developing_officer_9 "普通"
#define str_developing_officer_10 "精心"
#define str_developing_officer_11 "武将培养"
#define str_developing_officer_12 "激发潜力"
#define str_developing_officer_13 "当前拥有：%d"
#define str_developing_officer_14 "使用十个"
#define str_developing_officer_15 "使用一个"
#define str_developing_officer_16 "关闭"
#define str_developing_officer_17 "培 养"
#define str_developing_officer_18 "培养丹数量不足"
#define str_developing_officer_19 "所需材料数量不足~"
#define str_developing_officer_20 "所有属性已达到培养上限"
#define str_developing_officer_21 "伺服器异常"
#define str_developing_officer_22 "有未保存的属性，不能保存"
#define str_developing_officer_23 "潜力酒数量不足"
#define str_developing_officer_24 "没有可培养的属性"
#define str_developing_officer_25 "主公达到%d级开啟此功能"
#define str_developing_officer_26 "武将达到%d级开啟此功能"
#define str_developing_officer_27 "保存失败！"
#define str_developing_officer_28 "该武将培养已达上限"
#define str_developing_officer_29 "使用成功~"
#define str_developing_officer_30 "使用失败！"
#define str_developing_officer_31 "剩餘可增加潜力点:%d"

//西域商人
#define str_exomech_1 "随著主公vip等级的提升，西域商人会出售更為稀有的商品。"
#define str_exomech_2 "vip1及以上玩家可以在西域商人处廉价购买到超值的商品。"
#define str_exomech_3 "主公在闯关模式(包括精英闯关)胜利后，会随机遇到这个商人。"
#define str_exomech_4 "这位主公请留步,吾观汝骨骼精奇,必是天命所归之人,鄙人愿将家传宝物廉价赠汝!"
#define str_exomech_5 "倒计时"
#define str_exomech_6 "西域商人一直标榜自己是守法的三国好公民，以其独有的畅销走私品行走于三国乱世，曾经获得过三国贸易协会授予的“最良心经营奖”称号。此人经营的物品包括“/#稀有武将碎片/#”、“/#稀有转生道具/#”及/#其他大量珍贵道具/#。"

#define str_sgareanlayer_str1 "次数不够!"
#define str_sgareanlayer_str2 "挑战时间未到!"
#define str_sgareanlayer_str3 "挑战次数:"
#define str_sgareanlayer_str4 "距下次发放奖励:"
#define str_sgareanlayer_str5 "我的排名:"
#define str_sgareanlayer_str6 "排名奖励:"
#define str_sgareanlayer_str7 "乱世商人"
#define str_sgareanlayer_str8 "领取奖励"
#define str_sgareanlayer_str9 "挑战冷却时间:"
#define str_sgareanlayer_str10 "群雄争霸"
#define str_sgareanlayer_str11 "征战之路"
#define str_sgareanlayer_str12 "诸侯割据"
#define str_sgareanlayer_str13 "领取成功!"
#define str_sgareanlayer_str14 "当前没有可领取的征服点!"
#define str_sgareanlayer_str15 "%d小时"
#define str_sgareanlayer_str16 "%d分鐘"
#define str_sgareanlayer_str17 "%d秒"

#define str_sgareanlayer_str18 "挑战次数: %d/%d"
#define str_sgareanlayer_str19 "排名:"
#define str_sgareanlayer_str20 "等级:"
#define str_sgareanlayer_str22 "%d小时内"
#define str_sgareanlayer_str21 "两天以内"

#define str_sgareanlayer_str23 "战力:"
#define str_sgareanlayer_str24 "奖励:"

#define str_sgareanlayer_str25 "跳过战斗"
#define str_sgareanlayer_str26 "挑战次数不足,vip%d以上玩家可购买挑战次数"
#define str_sgareanlayer_str27 "购买成功!"
#define str_sgareanlayer_str28 "元宝不足!"
#define str_sgareanlayer_str29 "%d名"
#define str_sgareanlayer_str30 "查看阵容"
#define str_sgareanlayer_str31 "对战"
#define str_sgareanlayer_str32 "竞技场规则"
#define str_sgareanlayer_str33 "当前可挑战"

#define str_sdk_str1 "请先登陆账号噢"

#endif

#endif









































































